# -*- coding: utf-8 -*-
"""V2.7 Conditional VAE - Latent Diffusion - ResMLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_5O9cjF_UM3Bs5ewZwHcEg9RdLNxPaVs

# Model Overview

This notebook implements a **two-stage Text -> Serum-parameter generator**:

1) **Stage 1: Conditional VAE** learns a compact latent space for synth presets.  
2) **Stage 2: Latent Diffusion** learns to sample high-quality latents from text alone, then decodes them back into full parameter vectors.

The goal is to keep the decoder faithful to the synth's parameter manifold, while letting diffusion handle multi-modality and diversity (many different knob settings can yield similar sounds).

---

## 1. Stage 1: Conditional VAE (Compression Model)

The VAE models a distribution over latents conditioned on both:
- **x**: 202 Serum parameters (continuous, boolean, categorical, plus mod-matrix handling)
- **c**: CLAP text embedding (512-dim)

### Posterior (training-time inference)
- **Posterior**:  \( q(z \mid x, c) \)  
  The encoder consumes **(text embedding + parameter vector)** and outputs \( z\_mean, z\_log\_var \).

### Prior (this version)
- **Standard Normal Prior**:  \( p(z) = \mathcal{N}(0, I) \)  
  In this notebook, the VAE is treated as the **compression stage** for diffusion, so we use a standard Gaussian KL term.

### Decoder
- **Decoder**:  \( p(x \mid z, c) \)  
  The decoder consumes **(latent z + text embedding)** and produces the parameter heads described below.

---

## 2. Conditioning: CLAP + FiLM (Text steers generation)

- **CLAP text encoder**
  Uses `laion/clap-htsat-fused` to convert prompts into stable 512-dim vectors.

- **FiLM in the VAE decoder**
  Instead of only concatenating text, the decoder applies **Feature-wise Linear Modulation (FiLM)** so the text embedding can scale and shift internal activations. This makes the prompt act like a "control signal" throughout decoding, not just an input feature.

- **FiLM in the diffusion denoiser**
  The ResMLP denoiser also uses FiLM-style modulation, conditioned on **(time embedding + text embedding)** so the denoising trajectory stays prompt-consistent at every step.

---

## 3. Activity Gating (Hierarchical constraints)

Serum has an explicit signal path (modules can be off). This notebook includes **group masking** logic so training respects that structure:

- If an enable switch is off (for example Osc A On = 0), then dependent knobs in that module are masked out of reconstruction loss.
- This prevents the model from wasting capacity learning arbitrary settings for silent modules.

---

## 4. Multi-head Outputs (Correct math for each parameter type)

The decoder outputs specialized heads so each parameter type is modeled appropriately:

- **Unipolar continuous knobs (0..1)**  
  Sigmoid output, MSE loss

- **Bipolar mod-matrix amounts (sparse, signed)**  
  Two-head strategy:
  - gate head (logits) trained with focal-style loss to handle sparsity  
  - value head (tanh) trained with regression loss only when the gate is active

- **Boolean switches**  
  Sigmoid output, binary cross-entropy

- **Categorical menus (filter types, rates, modes)**  
  Softmax output per categorical parameter, sparse categorical cross-entropy

---

## 5. Stage 2: Latent Diffusion (Sampling model)

Diffusion is trained in **latent space**, not parameter space:

1) Encode real presets into latents:
   - sample \( z_0 \sim q(z \mid x, c) \) using the frozen VAE encoder
2) Add noise across timesteps:
   - \( z_t = \alpha_t z_0 + \sigma_t \epsilon \)
3) Train a denoiser to predict the noise:
   - denoiser inputs: \( (z_t, t, c) \)
   - objective: MSE between true noise \( \epsilon \) and predicted noise \( \hat{\epsilon} \)

### Denoiser architecture: ResMLP + FiLM
- Sinusoidal time embedding
- Conditioning vector = time embedding + text embedding
- Stack of residual MLP blocks that are FiLM-modulated by the conditioning vector
- Output predicts per-dimension latent noise

### Sampling
At inference:
- Start from random noise \( z_T \)
- Iteratively denoise back to \( z_0 \) using the trained denoiser
- Decode final latent with the frozen VAE decoder to produce the parameter heads

---

## 6. Training stability strategies

- **Beta annealing (Stage 1)**  
  Warm up the KL weight over early epochs to prioritize reconstruction first.

- **Latent dropout (Stage 1)**  
  Occasionally zero out z so the decoder learns to rely on the prompt, not only the latent.

- **Frozen VAE during diffusion (Stage 2)**  
  The denoiser learns the latent distribution while the VAE defines the latent manifold.
"""

# Cell 1.1

# CLEAN START: remove default packages
!pip uninstall -y dopamine-rl flax chex optax orbax-checkpoint tensorflow-hub keras-hub ydf jax jaxlib tf-keras tensorflow-text tensorflow-decision-forests || true

# Install a minimal, compatible stack for Colab
!pip install -q --upgrade pip
!pip install -q "numpy==2.0.2" "tensorflow==2.19.0" \
                "transformers==4.45.2" "sentence-transformers==2.7.0"

# Install CUDA wheels for PyTorch (GPU / T4).
!pip install -q "torch==2.8.0" "torchvision==0.23.0" "torchaudio==2.8.0" \
  --extra-index-url https://download.pytorch.org/whl/cu126

# Sanity check: Print what GPU using
!nvidia-smi -L || true

# Cell 1.2 — GPU Setup

import os
import numpy as np
import tensorflow as tf
from tensorflow import keras

# Tensorflow log level
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

# GPU Setup
gpus = tf.config.list_physical_devices("GPU")
print("GPUs visible to TF:", gpus)
for gpu in gpus:
    try:
        tf.config.experimental.set_memory_growth(gpu, True)
    except Exception as e:
        print("Could not set memory growth:", e)

print("TF:", tf.__version__)
print("tf.keras:", keras.__version__)
print("NumPy:", np.__version__)

# Cell 1.3
# Mount Drive, Setup save directory

import os
from google.colab import drive

# 1. Mount Drive (Force remount to ensure fresh connection)
drive.mount('/content/drive', force_remount=True)

# 2. Define your Save Directory clearly
# Using a variable ensures you don't have typos in different cells
SAVE_DIR = "/content/drive/My Drive/Colab Notebooks/notebooks/models/vae/text_input/V2 - Activity Gating, FiLM/v2p7/output_models"

# 3. Create the directory (and all intermediate folders) if they don't exist
try:
    os.makedirs(SAVE_DIR, exist_ok=True)
    print(f"✅ Directory confirmed: {SAVE_DIR}")
except OSError as e:
    print(f"❌ Error creating directory: {e}")

# 4. Write Test
# Create a dummy file to verify we actually have write permissions before training starts
test_file = os.path.join(SAVE_DIR, "write_test.txt")
try:
    with open(test_file, "w") as f:
        f.write("Access granted.")
    os.remove(test_file) # Clean up
    print("✅ Write access confirmed. You are ready to train.")
except Exception as e:
    print(f"❌ Write access FAILED: {e}")
    print("Check your Drive permissions or path string.")

# Cell 1.4 — Initialize CLAP Text Encoder
# This model converts natural language descriptions into 512-dimensional
# embeddings that will guide the Audio VAE via FiLM layers.

import torch
from transformers import ClapModel, ClapProcessor

# Use GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

# CLAP Model Initialization
# We load the fused version of CLAP (better at capturing fine-grained audio detail)
clap_model_name = "laion/clap-htsat-fused"
clap_model = ClapModel.from_pretrained(clap_model_name).to(device)
clap_processor = ClapProcessor.from_pretrained(clap_model_name)

# Set to 'eval' to disable dropout/batch norm updates; ensures consistent embeddings.
clap_model.eval()

@torch.no_grad() # Disable gradient calculation to save VRAM on the T4
def clap_encode_text(texts, batch_size=128, normalize=True, max_length=None):
    """
    Encodes a list of strings into a NumPy array of embeddings.

    Args:
        texts (list): Sentences describing audio (e.g., "Gritty dubstep bass").
        batch_size (int): Number of texts to process at once on the GPU.
        normalize (bool): If True, output vectors have a unit length of 1.

    Returns:
        np.ndarray: Matrix of shape (len(texts), 512).
    """
    out = []
    for i in range(0, len(texts), batch_size):
        # Ensure all inputs are strings to avoid tokenizer errors
        batch = [str(t) for t in texts[i:i+batch_size]]

        # Tokenize: Convert text to fixed-length tensors for the Transformer
        inputs = clap_processor(
            text=batch,
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=max_length
        ).to(device)

        # Forward pass: Extract the 512-dimensional 'meaning' of the text
        feats = clap_model.get_text_features(**inputs)  # Output shape: [Batch, 512]

        # L2 Normalization: Keeps embedding values stable for the VAE's FiLM layers
        if normalize:
            feats = torch.nn.functional.normalize(feats, dim=-1)

        # Move back to CPU to free up GPU memory for the TensorFlow VAE
        out.append(feats.cpu())

    # Concatenate batches and convert to NumPy (the standard format for TF/Keras)
    return torch.cat(out, dim=0).numpy()

print(f"✅ CLAP loaded and ready on: {device}")

"""# Load Data"""

# Cell 2.1

import numpy as np

# Load the serum parameters
serum_params = np.load(
    '/content/drive/My Drive/Colab Notebooks/data/cleaned/combined/combined_params_categorical.npy',
    allow_pickle=True
).astype('float32')  # enforce float32 as T4 optimized for float32, speeds up training, and don't need more precision for synth params

# Load the preset descriptions
serum_preset_descriptions = np.load(
    '/content/drive/My Drive/Colab Notebooks/data/cleaned/combined/combined_descriptions.npy',
    allow_pickle=True
)

print("Shape of serum_params:", serum_params.shape)
print("Shape of serum_preset_descriptions:", serum_preset_descriptions.shape)

print("\nFirst row of serum_params (parameters for the first preset):")
print(serum_params[0, :10]) # Print first 10 parameters of the first preset

print("\nFirst 5 preset descriptions:")
print(serum_preset_descriptions[:5])

# Cell 2.2
# SERUM_PARAMETERS with the nested structure required for Activity Gating

SERUM_PARAMETERS = {
    "global": [
        {"id": "0", "serum_id": "0", "name": "MasterVol", "type": "continuous"},
        {"id": "1", "serum_id": "65", "name": "PortTime", "type": "continuous"},
        {"id": "2", "serum_id": "66", "name": "PortCurve", "type": "continuous"},
    ],
    "osc_a": [
        {"id": "3", "serum_id": "212", "name": "Osc A On", "type": "boolean"},
        {"id": "4", "serum_id": "1", "name": "A Vol", "type": "continuous"},
        {"id": "5", "serum_id": "2", "name": "A Pan", "type": "continuous"},
        {"id": "6", "serum_id": "3", "name": "A Octave", "type": "categorical", "num_categories": 9},
        {"id": "7", "serum_id": "4", "name": "A Semi", "type": "categorical", "num_categories": 25},
        {"id": "8", "serum_id": "5", "name": "A Fine", "type": "continuous"},
        {"id": "9", "serum_id": "10", "name": "A CoarsePit", "type": "continuous"},
        {"id": "10", "serum_id": "6", "name": "A Unison", "type": "continuous"},
        {"id": "11", "serum_id": "7", "name": "A UniDet", "type": "continuous"},
        {"id": "12", "serum_id": "8", "name": "A UniBlend", "type": "continuous"},
        {"id": "13", "serum_id": "172", "name": "A Uni LR", "type": "continuous"},
        {"id": "14", "serum_id": "174", "name": "A Uni Warp", "type": "continuous"},
        {"id": "15", "serum_id": "176", "name": "A Uni WTPos", "type": "continuous"},
        {"id": "16", "serum_id": "178", "name": "A Uni Stack", "type": "categorical", "num_categories": 9},
        {"id": "17", "serum_id": "11", "name": "A WTPos", "type": "continuous"},
        {"id": "18", "serum_id": "168", "name": "WarpOscA", "type": "categorical", "num_categories": 23},
        {"id": "19", "serum_id": "9", "name": "A Warp", "type": "continuous"},
        {"id": "20", "serum_id": "12", "name": "A RandPhase", "type": "continuous"},
        {"id": "21", "serum_id": "13", "name": "A Phase", "type": "continuous"},
    ],
    "osc_b": [
        {"id": "22", "serum_id": "213", "name": "Osc B On", "type": "boolean"},
        {"id": "23", "serum_id": "14", "name": "B Vol", "type": "continuous"},
        {"id": "24", "serum_id": "15", "name": "B Pan", "type": "continuous"},
        {"id": "25", "serum_id": "16", "name": "B Octave", "type": "categorical", "num_categories": 9},
        {"id": "26", "serum_id": "17", "name": "B Semi", "type": "categorical", "num_categories": 25},
        {"id": "27", "serum_id": "18", "name": "B Fine", "type": "continuous"},
        {"id": "28", "serum_id": "23", "name": "B CoarsePit", "type": "continuous"},
        {"id": "29", "serum_id": "19", "name": "B Unison", "type": "continuous"},
        {"id": "30", "serum_id": "20", "name": "B UniDet", "type": "continuous"},
        {"id": "31", "serum_id": "21", "name": "B UniBlend", "type": "continuous"},
        {"id": "32", "serum_id": "173", "name": "B Uni LR", "type": "continuous"},
        {"id": "33", "serum_id": "175", "name": "B Uni Warp", "type": "continuous"},
        {"id": "34", "serum_id": "177", "name": "B Uni WTPos", "type": "continuous"},
        {"id": "35", "serum_id": "179", "name": "B Uni Stack", "type": "categorical", "num_categories": 9},
        {"id": "36", "serum_id": "24", "name": "B WTPos", "type": "continuous"},
        {"id": "37", "serum_id": "169", "name": "WarpOscB", "type": "categorical", "num_categories": 23},
        {"id": "38", "serum_id": "22", "name": "B Warp", "type": "continuous"},
        {"id": "39", "serum_id": "25", "name": "B RandPhase", "type": "continuous"},
        {"id": "40", "serum_id": "26", "name": "B Phase", "type": "continuous"},
    ],
    "noise_osc": [
        {"id": "41", "serum_id": "214", "name": "Osc N On", "type": "boolean"},
        {"id": "42", "serum_id": "27", "name": "Noise Level", "type": "continuous"},
        {"id": "43", "serum_id": "28", "name": "Noise Pitch", "type": "continuous"},
        {"id": "44", "serum_id": "29", "name": "Noise Fine", "type": "continuous"},
        {"id": "45", "serum_id": "30", "name": "Noise Pan", "type": "continuous"},
        {"id": "46", "serum_id": "31", "name": "Noise RandPhase", "type": "continuous"},
        {"id": "47", "serum_id": "32", "name": "Noise Phase", "type": "continuous"},
    ],
    "sub_osc": [
        {"id": "48", "serum_id": "215", "name": "Osc S On", "type": "boolean"},
        {"id": "49", "serum_id": "33", "name": "Sub Osc Level", "type": "continuous"},
        {"id": "50", "serum_id": "34", "name": "Sub Osc Pan", "type": "continuous"},
        {"id": "51", "serum_id": "170", "name": "SubOscShape", "type": "categorical", "num_categories": 6},
        {"id": "52", "serum_id": "171", "name": "SubOscOctave", "type": "continuous"},
    ],
    "filter": [
        {"id": "53", "serum_id": "216", "name": "Filter On", "type": "boolean"},
        {"id": "54", "serum_id": "44", "name": "Fil Type", "type": "categorical", "num_categories": 95},
        {"id": "55", "serum_id": "40", "name": "OscA>Fil", "type": "boolean"},
        {"id": "56", "serum_id": "41", "name": "OscB>Fil", "type": "boolean"},
        {"id": "57", "serum_id": "42", "name": "OscN>Fil", "type": "boolean"},
        {"id": "58", "serum_id": "43", "name": "OscS>Fil", "type": "boolean"},
        {"id": "59", "serum_id": "45", "name": "Fil Cutoff", "type": "continuous"},
        {"id": "60", "serum_id": "46", "name": "Fil Reso", "type": "continuous"},
        {"id": "61", "serum_id": "47", "name": "Fil Driv", "type": "continuous"},
        {"id": "62", "serum_id": "48", "name": "Fil Var", "type": "continuous"},
        {"id": "63", "serum_id": "49", "name": "Fil Mix", "type": "continuous"},
        {"id": "64", "serum_id": "50", "name": "Fil Stereo", "type": "continuous"},
    ],
    "envelopes": [
        {"id": "65", "serum_id": "35", "name": "Env1 Atk", "type": "continuous"},
        {"id": "66", "serum_id": "36", "name": "Env1 Hold", "type": "continuous"},
        {"id": "67", "serum_id": "37", "name": "Env1 Dec", "type": "continuous"},
        {"id": "68", "serum_id": "38", "name": "Env1 Sus", "type": "continuous"},
        {"id": "69", "serum_id": "39", "name": "Env1 Rel", "type": "continuous"},
        {"id": "70", "serum_id": "51", "name": "Env2 Atk", "type": "continuous"},
        {"id": "71", "serum_id": "52", "name": "Env2 Hold", "type": "continuous"},
        {"id": "72", "serum_id": "53", "name": "Env2 Dec", "type": "continuous"},
        {"id": "73", "serum_id": "54", "name": "Env2 Sus", "type": "continuous"},
        {"id": "74", "serum_id": "55", "name": "Env2 Rel", "type": "continuous"},
    ],
    "lfos": [
        {"id": "75", "serum_id": "61", "name": "LFO1 Rate", "type": "categorical", "num_categories": 19},
        {"id": "76", "serum_id": "273", "name": "LFO1 Rise", "type": "categorical", "num_categories": 20},
        {"id": "77", "serum_id": "281", "name": "LFO1 Delay", "type": "categorical", "num_categories": 20},
        {"id": "78", "serum_id": "223", "name": "LFO1 Smooth", "type": "continuous"},
        {"id": "79", "serum_id": "62", "name": "LFO2 Rate", "type": "categorical", "num_categories": 19},
        {"id": "80", "serum_id": "274", "name": "LFO2 Rise", "type": "categorical", "num_categories": 20},
        {"id": "81", "serum_id": "282", "name": "LFO2 Delay", "type": "categorical", "num_categories": 20},
        {"id": "82", "serum_id": "224", "name": "LFO2 Smooth", "type": "continuous"},
    ],
    "fx_hyper_dimension": [
        {"id": "83", "serum_id": "163", "name": "Hyp Enable", "type": "boolean"},
        {"id": "84", "serum_id": "148", "name": "Hyp_Rate", "type": "continuous"},
        {"id": "85", "serum_id": "149", "name": "Hyp_Detune", "type": "continuous"},
        {"id": "86", "serum_id": "150", "name": "Hyp_Unison", "type": "continuous"},
        {"id": "87", "serum_id": "147", "name": "Hyp_Wet", "type": "continuous"},
        {"id": "88", "serum_id": "152", "name": "HypDim_Size", "type": "continuous"},
        {"id": "89", "serum_id": "153", "name": "HypDim_Mix", "type": "continuous"},
    ],
    "fx_distortion": [
        {"id": "90", "serum_id": "154", "name": "Dist Enable", "type": "boolean"},
        {"id": "91", "serum_id": "96", "name": "Dist_Wet", "type": "continuous"},
        {"id": "92", "serum_id": "97", "name": "Dist_Drv", "type": "continuous"},
        {"id": "93", "serum_id": "99", "name": "Dist_Mode", "type": "categorical", "num_categories": 16},
        {"id": "94", "serum_id": "102", "name": "Dist_PrePost", "type": "categorical", "num_categories": 3},
        {"id": "95", "serum_id": "98", "name": "Dist_L/B/H", "type": "categorical", "num_categories": 3},
        {"id": "96", "serum_id": "100", "name": "Dist_Freq", "type": "continuous"},
        {"id": "97", "serum_id": "101", "name": "Dist_BW", "type": "continuous"},
    ],
    "fx_flanger": [
        {"id": "98", "serum_id": "155", "name": "Flg Enable", "type": "boolean"},
        {"id": "99", "serum_id": "103", "name": "Flg_Wet", "type": "continuous"},
        {"id": "100", "serum_id": "104", "name": "Flg_BPM_Sync", "type": "boolean"},
        {"id": "101", "serum_id": "105", "name": "Flg_Rate", "type": "continuous"},
        {"id": "102", "serum_id": "106", "name": "Flg_Dep", "type": "continuous"},
        {"id": "103", "serum_id": "107", "name": "Flg_Feed", "type": "continuous"},
        {"id": "104", "serum_id": "108", "name": "Flg_Stereo", "type": "continuous"},
    ],
    "fx_phaser": [
        {"id": "105", "serum_id": "156", "name": "Phs Enable", "type": "boolean"},
        {"id": "106", "serum_id": "109", "name": "Phs_Wet", "type": "continuous"},
        {"id": "107", "serum_id": "110", "name": "Phs_BPM_Sync", "type": "boolean"},
        {"id": "108", "serum_id": "111", "name": "Phs_Rate", "type": "continuous"},
        {"id": "109", "serum_id": "112", "name": "Phs_Dpth", "type": "continuous"},
        {"id": "110", "serum_id": "113", "name": "Phs_Frq", "type": "continuous"},
        {"id": "111", "serum_id": "114", "name": "Phs_Feed", "type": "continuous"},
        {"id": "112", "serum_id": "115", "name": "Phs_Stereo", "type": "continuous"},
    ],
    "fx_chorus": [
        {"id": "113", "serum_id": "157", "name": "Cho Enable", "type": "boolean"},
        {"id": "114", "serum_id": "116", "name": "Cho_Wet", "type": "continuous"},
        {"id": "115", "serum_id": "117", "name": "Cho_BPM_Sync", "type": "boolean"},
        {"id": "116", "serum_id": "118", "name": "Cho_Rate", "type": "continuous"},
        {"id": "117", "serum_id": "119", "name": "Cho_Dly", "type": "continuous"},
        {"id": "118", "serum_id": "120", "name": "Cho_Dly2", "type": "continuous"},
        {"id": "119", "serum_id": "121", "name": "Cho_Dep", "type": "continuous"},
        {"id": "120", "serum_id": "122", "name": "Cho_Feed", "type": "continuous"},
        {"id": "121", "serum_id": "123", "name": "Cho_Filt", "type": "continuous"},
    ],
    "fx_delay": [
        {"id": "122", "serum_id": "158", "name": "Dly Enable", "type": "boolean"},
        {"id": "123", "serum_id": "124", "name": "Dly_Wet", "type": "continuous"},
        {"id": "124", "serum_id": "125", "name": "Dly_Freq", "type": "continuous"},
        {"id": "125", "serum_id": "126", "name": "Dly_BW", "type": "continuous"},
        {"id": "126", "serum_id": "127", "name": "Dly_BPM_Sync", "type": "boolean"},
        {"id": "127", "serum_id": "128", "name": "Dly_Link", "type": "boolean"},
        {"id": "128", "serum_id": "129", "name": "Dly_TimL", "type": "categorical", "num_categories": 12},
        {"id": "129", "serum_id": "130", "name": "Dly_TimR", "type": "categorical", "num_categories": 12},
        {"id": "130", "serum_id": "131", "name": "Dly_Mode", "type": "categorical", "num_categories": 3},
        {"id": "131", "serum_id": "132", "name": "Dly_Feed", "type": "continuous"},
        {"id": "132", "serum_id": "133", "name": "Dly_Off L", "type": "continuous"},
        {"id": "133", "serum_id": "134", "name": "Dly_Off R", "type": "continuous"},
    ],
    "fx_compressor": [
        {"id": "134", "serum_id": "159", "name": "Comp Enable", "type": "boolean"},
        {"id": "135", "serum_id": "135", "name": "Cmp_Thr", "type": "continuous"},
        {"id": "136", "serum_id": "136", "name": "Cmp_Rat", "type": "categorical", "num_categories": 21},
        {"id": "137", "serum_id": "137", "name": "Cmp_Att", "type": "continuous"},
        {"id": "138", "serum_id": "138", "name": "Cmp_Rel", "type": "continuous"},
        {"id": "139", "serum_id": "139", "name": "CmpGain", "type": "continuous"},
        {"id": "140", "serum_id": "140", "name": "CmpMBnd", "type": "categorical", "num_categories": 2},
        {"id": "141", "serum_id": "270", "name": "CompMB L", "type": "continuous"},
        {"id": "142", "serum_id": "271", "name": "CompMB M", "type": "continuous"},
        {"id": "143", "serum_id": "272", "name": "CompMB H", "type": "continuous"},
        {"id": "144", "serum_id": "269", "name": "Comp_Wet", "type": "continuous"},
    ],
    "fx_reverb": [
        {"id": "145", "serum_id": "160", "name": "Rev Enable", "type": "boolean"},
        {"id": "146", "serum_id": "81", "name": "Verb Wet", "type": "continuous"},
        {"id": "147", "serum_id": "82", "name": "VerbSize", "type": "continuous"},
        {"id": "148", "serum_id": "83", "name": "Decay", "type": "continuous"},
        {"id": "149", "serum_id": "84", "name": "VerbLoCt", "type": "continuous"},
        {"id": "150", "serum_id": "85", "name": "Spin Rate", "type": "continuous"},
        {"id": "151", "serum_id": "86", "name": "VerbHiCt", "type": "continuous"},
        {"id": "152", "serum_id": "87", "name": "Spin Depth", "type": "continuous"},
    ],
    "fx_eq": [
        {"id": "153", "serum_id": "161", "name": "EQ Enable", "type": "boolean"},
        {"id": "154", "serum_id": "88", "name": "EQ FrqL", "type": "continuous"},
        {"id": "155", "serum_id": "89", "name": "EQ FrqH", "type": "continuous"},
        {"id": "156", "serum_id": "90", "name": "EQ Q L", "type": "continuous"},
        {"id": "157", "serum_id": "91", "name": "EQ Q H", "type": "continuous"},
        {"id": "158", "serum_id": "92", "name": "EQ Vol L", "type": "continuous"},
        {"id": "159", "serum_id": "93", "name": "EQ Vol H", "type": "continuous"},
        {"id": "160", "serum_id": "94", "name": "EQ TypL", "type": "categorical", "num_categories": 3},
        {"id": "161", "serum_id": "95", "name": "EQ TypH", "type": "categorical", "num_categories": 3},
    ],
    "fx_filter": [
        {"id": "162", "serum_id": "162", "name": "FX Fil Enable", "type": "boolean"},
        {"id": "163", "serum_id": "141", "name": "FX Fil Wet", "type": "continuous"},
        {"id": "164", "serum_id": "142", "name": "FX Fil Type", "type": "categorical", "num_categories": 89},
        {"id": "165", "serum_id": "143", "name": "FX Fil Freq", "type": "continuous"},
        {"id": "166", "serum_id": "144", "name": "FX Fil Reso", "type": "continuous"},
        {"id": "167", "serum_id": "145", "name": "FX Fil Drive", "type": "continuous"},
        {"id": "168", "serum_id": "146", "name": "FX Fil Var", "type": "continuous"},
        {"id": "169", "serum_id": "268", "name": "FX Fil Pan", "type": "continuous"},
    ],
    "mod_matrix": [
        {"id": "170", "serum_id": "180", "name": "Mod 1 amt", "type": "continuous"},
        {"id": "171", "serum_id": "182", "name": "Mod 2 amt", "type": "continuous"},
        {"id": "172", "serum_id": "184", "name": "Mod 3 amt", "type": "continuous"},
        {"id": "173", "serum_id": "186", "name": "Mod 4 amt", "type": "continuous"},
        {"id": "174", "serum_id": "188", "name": "Mod 5 amt", "type": "continuous"},
        {"id": "175", "serum_id": "190", "name": "Mod 6 amt", "type": "continuous"},
        {"id": "176", "serum_id": "192", "name": "Mod 7 amt", "type": "continuous"},
        {"id": "177", "serum_id": "194", "name": "Mod 8 amt", "type": "continuous"},
        {"id": "178", "serum_id": "196", "name": "Mod 9 amt", "type": "continuous"},
        {"id": "179", "serum_id": "198", "name": "Mod10 amt", "type": "continuous"},
        {"id": "180", "serum_id": "200", "name": "Mod11 amt", "type": "continuous"},
        {"id": "181", "serum_id": "202", "name": "Mod12 amt", "type": "continuous"},
        {"id": "182", "serum_id": "204", "name": "Mod13 amt", "type": "continuous"},
        {"id": "183", "serum_id": "206", "name": "Mod14 amt", "type": "continuous"},
        {"id": "184", "serum_id": "208", "name": "Mod15 amt", "type": "continuous"},
        {"id": "185", "serum_id": "210", "name": "Mod16 amt", "type": "continuous"},
        {"id": "186", "serum_id": "228", "name": "Mod17 amt", "type": "continuous"},
        {"id": "187", "serum_id": "230", "name": "Mod18 amt", "type": "continuous"},
        {"id": "188", "serum_id": "232", "name": "Mod19 amt", "type": "continuous"},
        {"id": "189", "serum_id": "234", "name": "Mod20 amt", "type": "continuous"},
        {"id": "190", "serum_id": "236", "name": "Mod21 amt", "type": "continuous"},
        {"id": "191", "serum_id": "238", "name": "Mod22 amt", "type": "continuous"},
        {"id": "192", "serum_id": "240", "name": "Mod23 amt", "type": "continuous"},
        {"id": "193", "serum_id": "242", "name": "Mod24 amt", "type": "continuous"},
        {"id": "194", "serum_id": "244", "name": "Mod25 amt", "type": "continuous"},
        {"id": "195", "serum_id": "246", "name": "Mod26 amt", "type": "continuous"},
        {"id": "196", "serum_id": "248", "name": "Mod27 amt", "type": "continuous"},
        {"id": "197", "serum_id": "250", "name": "Mod28 amt", "type": "continuous"},
        {"id": "198", "serum_id": "252", "name": "Mod29 amt", "type": "continuous"},
        {"id": "199", "serum_id": "254", "name": "Mod30 amt", "type": "continuous"},
        {"id": "200", "serum_id": "256", "name": "Mod31 amt", "type": "continuous"},
        {"id": "201", "serum_id": "258", "name": "Mod32 amt", "type": "continuous"},
    ],
}

# --- Index Lists for Type ---
continuous_param_indices = []
boolean_param_indices = []
categorical_param_indices = []
categorical_num_classes = {}

# Calculate total parameters
num_params = sum(len(group) for group in SERUM_PARAMETERS.values())

# Iterate over each group to populate indices
for group_name, params in SERUM_PARAMETERS.items():
    for pinfo in params:
        idx = int(pinfo["id"])
        ptype = pinfo["type"]

        if ptype == "continuous":
            continuous_param_indices.append(idx)
        elif ptype == "boolean":
            boolean_param_indices.append(idx)
        elif ptype == "categorical":
            categorical_param_indices.append(idx)
            categorical_num_classes[idx] = int(pinfo["num_categories"])
        else:
            raise ValueError(f"Unknown parameter type for index {idx}: {ptype}")

# Sorting indices to maintain sequential order in the lists
continuous_param_indices.sort()
boolean_param_indices.sort()
categorical_param_indices.sort()

print("continuous params:", len(continuous_param_indices))
print("boolean params:", len(boolean_param_indices))
print("categorical params:", len(categorical_param_indices))
print("categorical_num_classes:", len(categorical_num_classes))

# --- Group Masking Map ---
def create_group_mask_metadata(SERUM_PARAMETERS):
    group_map = {}
    for group_name, params in SERUM_PARAMETERS.items():
        enable_id = None
        dependent_ids = []
        for p in params:
            param_id = int(p["id"])
            dependent_ids.append(param_id)
            if p["name"].endswith(" On") or p["name"].endswith(" Enable"):
                enable_id = param_id
        if enable_id is not None:
            group_map[enable_id] = dependent_ids
    return group_map

GROUP_MASKING_MAP = create_group_mask_metadata(SERUM_PARAMETERS)

print("\nGroup Masking Map (Enable ID: [Dependent IDs]):")
print(GROUP_MASKING_MAP)

# --- Split Continuous Indices into Unipolar (0-1) and Bipolar (-1 to 1) ---
# Mod Matrix parameters (IDs 170-201) are bipolar. Everything else is unipolar.
mod_matrix_ids = set(range(170, 202))

unipolar_indices = [i for i in continuous_param_indices if i not in mod_matrix_ids]
bipolar_indices = [i for i in continuous_param_indices if i in mod_matrix_ids]

# Sort them to be safe
unipolar_indices.sort()
bipolar_indices.sort()

print(f"Unipolar params: {len(unipolar_indices)}")
print(f"Bipolar params: {len(bipolar_indices)}")

"""# Training

## Split Data
"""

# Cell 3.1 — Load, encode, and split data (INTEGER STRATEGY)

from sklearn.model_selection import train_test_split

# encode text
description_embeddings = clap_encode_text(serum_preset_descriptions)
print("description_embeddings:", description_embeddings.shape)

# Split
X_train, X_val, y_train, y_val = train_test_split(
    description_embeddings,
    serum_params,
    test_size=0.2,
    random_state=42,
)

X_train = X_train.astype('float32')
X_val   = X_val.astype('float32')
y_train = y_train.astype('float32')
y_val   = y_val.astype('float32')

embedding_dim = X_train.shape[1]
print("X_train:", X_train.shape, "X_val:", X_val.shape)
print("y_train:", y_train.shape, "y_val:", y_val.shape)

"""## Define Model Architecture"""

# Cell 3.2 — Conditional VAE & Latent Diffusion Architecture

import tensorflow as tf
import numpy as np
from tensorflow.keras import backend as K
from tensorflow.keras.layers import Layer, Input, Dense, Concatenate, Dropout, BatchNormalization, LayerNormalization, LeakyReLU, Activation, Add, Multiply
from tensorflow.keras.models import Model
from tensorflow.keras.utils import register_keras_serializable
from keras.saving import serialize_keras_object, deserialize_keras_object

# --- 0. HYPERPARAMETER CONSTANTS ---
W_CONT      = 10.0   # Weight for continuous knobs
W_BOOL      = 5.0    # Weight for switches
W_CAT       = 15.0   # Weight for menus
W_MOD_GATE  = 5.0    # Weight for modulation slots

# ==============================================================================
# 1. SHARED LAYERS
# ==============================================================================

@register_keras_serializable(package="custom", name="SliceLayer")
class SliceLayer(Layer):
    """
    Utility layer to slice specific columns from a tensor.
    Used to route specific parameters to specific decoder heads.
    """
    def __init__(self, indices, **kwargs):
        super().__init__(**kwargs)
        self.indices = [int(i) for i in (indices if isinstance(indices, (list, tuple)) else [indices])]

    def call(self, inputs):
        return tf.gather(inputs, self.indices, axis=1)

    def get_config(self):
        config = super().get_config()
        config.update({"indices": self.indices})
        return config

@register_keras_serializable(package="custom", name="FiLMLayer")
class FiLMLayer(Layer):
    """
    Feature-wise Linear Modulation (FiLM) Layer.
    Equation: Output = (Input * Gamma) + Beta
    """
    def call(self, inputs):
        # inputs: [features, gamma, beta]
        x, gamma, beta = inputs
        return x * gamma + beta

# ==============================================================================
# 2. VAE MODEL (Stage 1: Compression)
# ==============================================================================

def sigmoid_focal_crossentropy(y_true, y_pred, alpha=0.25, gamma=2.0, from_logits=True):
    """ Focal Loss for class imbalance (Mod Matrix Gate) """
    if from_logits: y_pred = tf.sigmoid(y_pred)
    bce = K.binary_crossentropy(y_true, y_pred)
    p_t = (y_true * y_pred) + ((1 - y_true) * (1 - y_pred))
    return alpha * K.pow(1.0 - p_t, gamma) * bce

class BetaAnnealing(tf.keras.callbacks.Callback):
    """ Anneals KL weight (beta) linearly over epochs """
    def __init__(self, max_beta=1.0, warmup_epochs=20, mode="linear"):
        super().__init__()
        self.max_beta = max_beta; self.warmup_epochs = warmup_epochs; self.mode = mode
    def on_epoch_begin(self, epoch, logs=None):
        beta = self.max_beta * min(1.0, (epoch + 1) / float(self.warmup_epochs))
        if hasattr(self.model, "beta"): self.model.beta = float(beta)

@register_keras_serializable(package="custom", name="VAE_Text_to_Synth_Standard")
class VAE_Text_to_Synth_Standard(tf.keras.Model):
    """ Stage 1: Standard CVAE with Gaussian Prior """
    def __init__(self, encoder, decoder, unipolar_indices, bipolar_indices,
                 bool_indices, cat_indices, categorical_num_classes, group_masking_map,
                 latent_dim, beta=1.0, latent_dropout_rate=0.0, **kwargs):
        super().__init__(**kwargs)
        self.encoder = encoder
        self.decoder = decoder
        self.unipolar_indices = [int(i) for i in unipolar_indices]
        self.bipolar_indices = [int(i) for i in bipolar_indices]
        self.bool_indices = [int(i) for i in bool_indices]
        self.cat_indices = [int(i) for i in cat_indices]
        self.categorical_num_classes = {int(k): int(v) for k, v in categorical_num_classes.items()}
        self.group_masking_map = {int(k): [int(x) for x in v] for k, v in (group_masking_map or {}).items()}
        self.param_to_enable = {int(pid): int(eid) for eid, mids in self.group_masking_map.items() for pid in mids if int(pid) != int(eid)}
        self.latent_dim = int(latent_dim)
        self.beta = float(beta)
        self.latent_dropout_rate = float(latent_dropout_rate)

        self.total_loss_tracker = tf.keras.metrics.Mean(name="total_loss")
        self.reconstruction_loss_tracker = tf.keras.metrics.Mean(name="reconstruction_loss")
        self.kl_loss_tracker = tf.keras.metrics.Mean(name="kl_loss")

    def call(self, inputs, training=False):
        text_embeddings, params_in = inputs
        z_mean, z_log_var = self.encoder([text_embeddings, params_in])
        eps = tf.random.normal(shape=tf.shape(z_mean))
        z = z_mean + tf.exp(0.5 * z_log_var) * eps
        return self.decoder([z, text_embeddings], training=training)

    def _group_mask_matrix(self, head_indices, y_true):
        batch_size = tf.shape(y_true)[0]
        mask_cols = []
        for pid in head_indices:
            enable_id = self.param_to_enable.get(int(pid), None)
            if enable_id is None: mask_cols.append(tf.ones((batch_size, 1), dtype=tf.float32))
            else:
                enable_val = tf.gather(y_true, indices=[enable_id], axis=1)
                mask_cols.append(tf.cast(enable_val > 0.5, tf.float32))
        return tf.concat(mask_cols, axis=1) if len(mask_cols) > 1 else mask_cols[0]

    def calculate_loss(self, y_true, y_pred_list, z_mean, z_log_var):
        eps = 1e-7
        head_idx = 0
        uni_loss, mod_loss, bool_loss, cat_loss = 0.0, 0.0, 0.0, 0.0

        if self.unipolar_indices:
            y_true_uni = tf.gather(y_true, self.unipolar_indices, axis=1)
            mask = self._group_mask_matrix(self.unipolar_indices, y_true)
            mse = tf.square(y_true_uni - y_pred_list[head_idx]) * mask
            uni_loss = (tf.reduce_sum(mse) / (tf.reduce_sum(mask) + eps)) * W_CONT
            head_idx += 1

        if self.bipolar_indices:
            y_true_bi_raw = tf.gather(y_true, self.bipolar_indices, axis=1)
            pred_gate, pred_val = y_pred_list[head_idx], y_pred_list[head_idx+1]
            head_idx += 2
            minv, maxv = tf.reduce_min(y_true_bi_raw), tf.reduce_max(y_true_bi_raw)
            y_true_bi = tf.cond(tf.logical_and(minv>=0, maxv<=1.0001), lambda: y_true_bi_raw*2-1, lambda: y_true_bi_raw)
            true_gate = tf.cast(tf.abs(y_true_bi) > 0.01, tf.float32)
            gate_loss = tf.reduce_mean(tf.reduce_sum(sigmoid_focal_crossentropy(true_gate, pred_gate), axis=-1))
            val_loss = tf.reduce_mean(tf.reduce_sum(tf.square(y_true_bi - pred_val) * true_gate, axis=-1) / (tf.reduce_sum(true_gate, axis=-1)+eps))
            mod_loss = gate_loss * W_MOD_GATE + val_loss * W_CONT

        if self.bool_indices:
            y_true_bool = tf.gather(y_true, self.bool_indices, axis=1)
            mask = self._group_mask_matrix(self.bool_indices, y_true)
            b_loss = K.binary_crossentropy(y_true_bool, tf.clip_by_value(y_pred_list[head_idx], eps, 1-eps)) * mask
            bool_loss = (tf.reduce_sum(b_loss) / (tf.reduce_sum(mask) + eps)) * W_BOOL
            head_idx += 1

        for j in sorted(self.cat_indices):
            y_true_cat = tf.squeeze(tf.gather(y_true, [j], axis=1), -1)
            y_pred_cat = y_pred_list[head_idx]
            mask = tf.squeeze(self._group_mask_matrix([j], y_true), -1)
            C = self.categorical_num_classes[int(j)]
            labels = tf.cast(tf.where(y_true_cat <= 1.0001, tf.round(y_true_cat*(C-1)), tf.round(y_true_cat)), tf.int32)
            labels = tf.clip_by_value(labels, 0, C-1)
            c_loss = tf.keras.losses.sparse_categorical_crossentropy(labels, y_pred_cat)
            cat_loss += tf.reduce_mean(c_loss * mask) * W_CAT
            head_idx += 1

        recon_loss = uni_loss + mod_loss + bool_loss + cat_loss
        kl_loss = -0.5 * tf.reduce_mean(tf.reduce_sum(1 + z_log_var - tf.square(z_mean) - tf.exp(z_log_var), axis=1))
        total_loss = recon_loss + (self.beta * kl_loss)
        return total_loss, recon_loss, kl_loss

    def train_step(self, data):
        (text_embeds, params_in), y_true = data
        with tf.GradientTape() as tape:
            z_mean, z_log_var = self.encoder([text_embeds, params_in])
            eps = tf.random.normal(shape=tf.shape(z_mean))
            z = z_mean + tf.exp(0.5 * z_log_var) * eps
            mask = tf.cast(tf.random.uniform((tf.shape(z)[0], 1)) >= self.latent_dropout_rate, tf.float32)
            z_dec = z * mask
            y_pred = self.decoder([z_dec, text_embeds], training=True)
            total, recon, kl = self.calculate_loss(y_true, y_pred, z_mean, z_log_var)

        grads = tape.gradient(total, self.trainable_variables)
        self.optimizer.apply_gradients(zip(grads, self.trainable_variables))
        self.total_loss_tracker.update_state(total)
        self.reconstruction_loss_tracker.update_state(recon)
        self.kl_loss_tracker.update_state(kl)
        return {"loss": self.total_loss_tracker.result(), "recon": recon, "kl": kl}

    def test_step(self, data):
        (text_embeds, params_in), y_true = data
        z_mean, z_log_var = self.encoder([text_embeds, params_in])
        eps = tf.random.normal(shape=tf.shape(z_mean))
        z = z_mean + tf.exp(0.5 * z_log_var) * eps
        y_pred = self.decoder([z, text_embeds], training=False)
        total, recon, kl = self.calculate_loss(y_true, y_pred, z_mean, z_log_var)

        self.total_loss_tracker.update_state(total)
        self.reconstruction_loss_tracker.update_state(recon)
        self.kl_loss_tracker.update_state(kl)
        return {"loss": self.total_loss_tracker.result(), "recon": recon, "kl": kl}

    def get_config(self):
        config = super().get_config()
        config.update({
            "encoder": serialize_keras_object(self.encoder),
            "decoder": serialize_keras_object(self.decoder),
            "unipolar_indices": self.unipolar_indices,
            "bipolar_indices": self.bipolar_indices,
            "bool_indices": self.bool_indices,
            "cat_indices": self.cat_indices,
            "categorical_num_classes": self.categorical_num_classes,
            "group_masking_map": self.group_masking_map,
            "latent_dim": self.latent_dim,
            "beta": self.beta,
            "latent_dropout_rate": self.latent_dropout_rate
        })
        return config

    @classmethod
    def from_config(cls, config):
        encoder = deserialize_keras_object(config.pop("encoder"))
        decoder = deserialize_keras_object(config.pop("decoder"))
        return cls(encoder, decoder, **config)


# ==============================================================================
# 3. DIFFUSION COMPONENTS (Stage 2: Denoising)
# ==============================================================================

@register_keras_serializable(package="custom", name="SinusoidalTimeEmbedding")
class SinusoidalTimeEmbedding(Layer):
    """ Standard Sinusoidal Positional Embeddings """
    def __init__(self, dim, **kwargs):
        super().__init__(**kwargs)
        self.dim = dim

    def call(self, time):
        half_dim = self.dim // 2
        embeddings = tf.math.log(10000.0) / (half_dim - 1)
        embeddings = tf.exp(tf.range(half_dim, dtype=tf.float32) * -embeddings)
        embeddings = tf.cast(time, tf.float32) * embeddings[None, :]
        embeddings = tf.concat([tf.sin(embeddings), tf.cos(embeddings)], axis=-1)
        return embeddings

    def get_config(self):
        config = super().get_config()
        config.update({"dim": self.dim})
        return config

@register_keras_serializable(package="custom", name="FiLM_Modulate")
class FiLM_Modulate(Layer):
    """ Used inside ResMLP Denoiser """
    def call(self, inputs):
        x, gammas, betas = inputs
        return (x * (1.0 + gammas)) + betas

@register_keras_serializable(package="custom", name="ResidualBlock")
class ResidualBlock(Layer):
    """ ResMLP Block with FiLM conditioning """
    def __init__(self, width, dropout=0.1, **kwargs):
        super().__init__(**kwargs)
        self.width = width
        self.dropout_rate = dropout

        self.norm1 = LayerNormalization()
        self.dense1 = Dense(width, activation="swish")
        self.drop1 = Dropout(dropout)

        self.norm2 = LayerNormalization()
        self.dense2 = Dense(width, activation="swish")
        self.drop2 = Dropout(dropout)

        self.film_proj = Dense(width * 4, activation=None)

    def call(self, x, conditions):
        residual = x
        film_params = self.film_proj(conditions)
        gam1, bet1, gam2, bet2 = tf.split(film_params, num_or_size_splits=4, axis=-1)

        x = self.norm1(x)
        x = FiLM_Modulate()([x, gam1, bet1])
        x = self.dense1(x)
        x = self.drop1(x)

        x = self.norm2(x)
        x = FiLM_Modulate()([x, gam2, bet2])
        x = self.dense2(x)
        x = self.drop2(x)

        return Add()([residual, x])

    def get_config(self):
        config = super().get_config()
        config.update({"width": self.width, "dropout": self.dropout_rate})
        return config

class DiffusionScheduler:
    """ Handles DDPM forward/reverse process math """
    def __init__(self, timesteps=1000, beta_start=0.0001, beta_end=0.02):
        self.timesteps = timesteps
        self.betas = tf.linspace(beta_start, beta_end, timesteps)
        self.alphas = 1.0 - self.betas
        self.alphas_cumprod = tf.math.cumprod(self.alphas)
        self.sqrt_alphas_cumprod = tf.sqrt(self.alphas_cumprod)
        self.sqrt_one_minus_alphas_cumprod = tf.sqrt(1.0 - self.alphas_cumprod)

    def add_noise(self, original_samples, noise, timesteps):
        sqrt_alpha_prod = tf.gather(self.sqrt_alphas_cumprod, timesteps)
        sqrt_one_minus_alpha_prod = tf.gather(self.sqrt_one_minus_alphas_cumprod, timesteps)
        sqrt_alpha_prod = tf.reshape(sqrt_alpha_prod, [-1, 1])
        sqrt_one_minus_alpha_prod = tf.reshape(sqrt_one_minus_alpha_prod, [-1, 1])
        return sqrt_alpha_prod * original_samples + sqrt_one_minus_alpha_prod * noise

@register_keras_serializable(package="custom", name="LatentDiffusionModel")
class LatentDiffusionModel(tf.keras.Model):
    """ Stage 2: Latent Diffusion Model """
    def __init__(self, vae_encoder, vae_decoder, denoiser, timesteps=1000, **kwargs):
        super().__init__(**kwargs)
        self.vae_encoder = vae_encoder
        self.vae_decoder = vae_decoder
        self.denoiser = denoiser
        self.timesteps = int(timesteps)
        self.scheduler = DiffusionScheduler(timesteps=self.timesteps)
        self.loss_tracker = tf.keras.metrics.Mean(name="loss")

    def call(self, inputs, training=False):
        # Keras requirement. Expected Inputs: [z_t, t, text_embeds]
        return self.denoiser(inputs, training=training)

    def train_step(self, data):
        (text_embeds, params_in), _ = data
        batch_size = tf.shape(params_in)[0]

        # 1. Encode with Frozen VAE
        z_mean, z_log_var = self.vae_encoder([text_embeds, params_in], training=False)
        epsilon = tf.random.normal(shape=tf.shape(z_mean))
        z_0 = z_mean + tf.exp(0.5 * z_log_var) * epsilon

        # 2. Add Noise
        t = tf.random.uniform(minval=0, maxval=self.timesteps, shape=(batch_size,), dtype=tf.int32)
        noise = tf.random.normal(shape=tf.shape(z_0))
        z_t = self.scheduler.add_noise(z_0, noise, t)

        # 3. Train Denoiser
        with tf.GradientTape() as tape:
            pred_noise = self.denoiser([z_t, t, text_embeds], training=True)
            loss = tf.reduce_mean(tf.square(noise - pred_noise))

        gradients = tape.gradient(loss, self.denoiser.trainable_variables)
        self.optimizer.apply_gradients(zip(gradients, self.denoiser.trainable_variables))
        self.loss_tracker.update_state(loss)
        return {"loss": self.loss_tracker.result()}

    def test_step(self, data):
        (text_embeds, params_in), _ = data
        batch_size = tf.shape(params_in)[0]
        z_mean, z_log_var = self.vae_encoder([text_embeds, params_in], training=False)
        epsilon = tf.random.normal(shape=tf.shape(z_mean))
        z_0 = z_mean + tf.exp(0.5 * z_log_var) * epsilon
        t = tf.random.uniform(minval=0, maxval=self.timesteps, shape=(batch_size,), dtype=tf.int32)
        noise = tf.random.normal(shape=tf.shape(z_0))
        z_t = self.scheduler.add_noise(z_0, noise, t)
        pred_noise = self.denoiser([z_t, t, text_embeds], training=False)
        loss = tf.reduce_mean(tf.square(noise - pred_noise))
        self.loss_tracker.update_state(loss)
        return {"loss": self.loss_tracker.result()}

    def generate(self, text_embeds, steps=50):
        """ Inference Loop (Reverse Diffusion) """
        # Ensure inputs are tensors to avoid "mix tensors/non-tensors" error
        text_embeds = tf.convert_to_tensor(text_embeds, dtype=tf.float32)

        batch_size = tf.shape(text_embeds)[0]
        latent_dim = self.vae_encoder.output_shape[0][1]
        z = tf.random.normal(shape=(batch_size, latent_dim))

        for i in reversed(range(0, self.timesteps)):
            t = tf.ones((batch_size,), dtype=tf.int32) * i

            # Predict noise
            pred_noise = self.denoiser([z, t, text_embeds], training=False)

            alpha = tf.gather(self.scheduler.alphas, i)
            alpha_cumprod = tf.gather(self.scheduler.alphas_cumprod, i)
            beta = tf.gather(self.scheduler.betas, i)
            sqrt_one_minus_alpha_cumprod = tf.sqrt(1.0 - alpha_cumprod)

            model_mean = (1 / tf.sqrt(alpha)) * (z - ((1 - alpha) / (sqrt_one_minus_alpha_cumprod)) * pred_noise)

            if i > 0:
                noise = tf.random.normal(shape=tf.shape(z))
                sigma = tf.sqrt(beta)
                z = model_mean + sigma * noise
            else:
                z = model_mean

        decoded = self.vae_decoder([z, text_embeds], training=False)
        return decoded

    def get_config(self):
        config = super().get_config()
        config.update({
            "vae_encoder": serialize_keras_object(self.vae_encoder),
            "vae_decoder": serialize_keras_object(self.vae_decoder),
            "denoiser": serialize_keras_object(self.denoiser),
            "timesteps": self.timesteps
        })
        return config

    @classmethod
    def from_config(cls, config):
        vae_encoder = deserialize_keras_object(config.pop("vae_encoder"))
        vae_decoder = deserialize_keras_object(config.pop("vae_decoder"))
        denoiser = deserialize_keras_object(config.pop("denoiser"))
        return cls(vae_encoder, vae_decoder, denoiser, **config)

"""## Define Model Builders"""

# Cell 3.3 — Model Builders

def build_encoder(embedding_dim, num_params, latent_dim, enc_width, dropout_rate=0.0):
    """ Builds q(z | params, text) """
    text_in = Input(shape=(embedding_dim,), name="encoder_text_input")
    params_in = Input(shape=(num_params,), name="encoder_params_input")
    x = Concatenate(name="encoder_concat")([text_in, params_in])
    x = Dense(enc_width, activation="linear")(x)
    x = LayerNormalization()(x)
    x = Activation("relu")(x)
    x = Dense(enc_width, activation="linear")(x)
    x = LayerNormalization()(x)
    x = Activation("relu")(x)
    z_mu = Dense(latent_dim, name="z_mean")(x)
    z_log = Dense(latent_dim, name="z_log_var")(x)
    return Model([text_in, params_in], [z_mu, z_log], name="encoder")

def build_decoder_film(embedding_dim, latent_dim, dec_width, unipolar_indices, bipolar_indices,
                       bool_indices, cat_indices, categorical_num_classes, dropout_rate=0.0):
    """ Builds p(params | z, text) using FiLM """
    z_in = Input(shape=(latent_dim,), name="latent_input")
    text_in = Input(shape=(embedding_dim,), name="decoder_text_input")

    def film_block(x, text_in, width, block_id):
        x = LayerNormalization(name=f"dec_ln_pre_{block_id}")(x)
        gamma = Dense(width, kernel_initializer="zeros", bias_initializer="ones")(text_in)
        beta = Dense(width, kernel_initializer="zeros", bias_initializer="zeros")(text_in)
        x = FiLMLayer(name=f"film_{block_id}")([x, gamma, beta])
        x = LeakyReLU(alpha=0.2)(x)
        return x

    x = Dense(dec_width)(z_in)
    x = film_block(x, text_in, dec_width, 1)
    x = Dense(dec_width)(x)
    x = film_block(x, text_in, dec_width, 2)
    x = Dense(dec_width)(x)
    x = LayerNormalization()(x)
    x = Activation("relu")(x)

    outs = []
    if unipolar_indices:
        outs.append(Dense(len(unipolar_indices), activation="sigmoid", name="unipolar_outputs")(x))
    if bipolar_indices:
        outs.append(Dense(len(bipolar_indices), activation="linear", name="bipolar_gate")(x))
        outs.append(Dense(len(bipolar_indices), activation="tanh", name="bipolar_value")(x))
    if bool_indices:
        outs.append(Dense(len(bool_indices), activation="sigmoid", name="boolean_outputs")(x))
    for j in sorted(cat_indices):
        outs.append(Dense(categorical_num_classes[int(j)], activation="softmax", name=f"cat_{j}")(x))
    return Model([z_in, text_in], outs, name="decoder_film")

def build_resmlp_denoiser(latent_dim=128, text_embed_dim=512, hidden_dim=512, num_layers=8):
    """ Builds the ResMLP Denoiser """
    z_noisy = Input(shape=(latent_dim,), name="z_noisy")
    t_in = Input(shape=(1,), name="time_input")
    text_emb = Input(shape=(text_embed_dim,), name="text_embedding")

    # 1. Embed Time
    # Output is [Batch, hidden_dim]
    t_emb = SinusoidalTimeEmbedding(dim=hidden_dim)(t_in)

    # Process time embedding
    t_emb = Dense(hidden_dim, activation="swish")(t_emb)

    # 2. Initial Projection
    x = Dense(hidden_dim)(z_noisy)

    # 3. Create Conditioning Vector (Time + Text)
    # We combine them so the Residual Block can project them into Gammas/Betas
    cond_concat = Concatenate()([t_emb, text_emb])
    cond_mapped = Dense(hidden_dim, activation="swish")(cond_concat)
    cond_mapped = Dense(hidden_dim, activation="swish")(cond_mapped)

    # 4. Residual Blocks
    for i in range(num_layers):
        x = ResidualBlock(width=hidden_dim, name=f"res_block_{i}")(x, cond_mapped)

    # 5. Output
    x = LayerNormalization()(x)
    noise_pred = Dense(latent_dim, activation="linear", name="noise_pred")(x)

    return Model(inputs=[z_noisy, t_in, text_emb], outputs=noise_pred, name="resmlp_denoiser")

"""## Compile and Train"""

# Cell 3.4 — Two-Stage Training Loop

import tensorflow as tf
from tensorflow.keras.optimizers import Adam # <--- Added this import
import os

# --- CONFIG ---
latent_dim = 128
vae_epochs = 40       # Phase 1: Train VAE to learn the compression
diffusion_epochs = 60 # Phase 2: Train Denoiser to learn the generation
lr = 1e-3
batch_size = 64

# --- STAGE 1: TRAIN VAE ---
print("\n=== STAGE 1: Training VAE (Compression) ===")

tf.keras.backend.clear_session()

# Build VAE
enc = build_encoder(X_train.shape[1], num_params, latent_dim, 256)
dec = build_decoder_film(X_train.shape[1], latent_dim, 512,
                         unipolar_indices, bipolar_indices, boolean_param_indices,
                         categorical_param_indices, categorical_num_classes)

vae = VAE_Text_to_Synth_Standard(
    encoder=enc, decoder=dec,
    unipolar_indices=unipolar_indices, bipolar_indices=bipolar_indices,
    bool_indices=boolean_param_indices, cat_indices=categorical_param_indices,
    categorical_num_classes=categorical_num_classes, group_masking_map=GROUP_MASKING_MAP,
    latent_dim=latent_dim, beta=1.0, latent_dropout_rate=0.1
)

vae.compile(optimizer=Adam(learning_rate=lr))

callbacks_vae = [
    tf.keras.callbacks.EarlyStopping(monitor="val_loss", patience=5, restore_best_weights=True),
    BetaAnnealing(max_beta=1.0, warmup_epochs=10)
]

# Train VAE
vae.fit(x=[X_train, y_train], y=y_train, epochs=vae_epochs, batch_size=batch_size,
        validation_data=([X_val, y_val], y_val), callbacks=callbacks_vae, verbose=1)

# Save VAE
vae_save_path = os.path.join(SAVE_DIR, "vae_stage1.keras")
vae.save(vae_save_path)
print(f"✅ VAE Saved to {vae_save_path}")

# --- STAGE 2: TRAIN DIFFUSION ---
print("\n=== STAGE 2: Training Diffusion (Generation) ===")

# Freeze VAE (We only train the Denoiser now)
vae.trainable = False
vae.encoder.trainable = False
vae.decoder.trainable = False

# Build Denoiser & LDM Wrapper
denoiser = build_resmlp_denoiser(latent_dim=latent_dim, text_embed_dim=X_train.shape[1])
ldm = LatentDiffusionModel(vae_encoder=vae.encoder, vae_decoder=vae.decoder, denoiser=denoiser, timesteps=1000)

ldm.compile(optimizer=Adam(learning_rate=1e-4)) # Lower LR is usually better for diffusion

# Train LDM (y_train is unused, the model generates its own noise targets)
ldm.fit(x=[X_train, y_train], y=y_train, epochs=diffusion_epochs, batch_size=batch_size,
        validation_split=0.1, verbose=1)

# Save Final LDM and set global variable
ldm_save_path = os.path.join(SAVE_DIR, "ldm_final.keras")
ldm.save(ldm_save_path)
best_model = ldm
print(f"✅ LDM Saved to {ldm_save_path}")

"""## Evaluate and Save Model"""

# Cell 3.5 — Evaluate Diffusion Model

# Validation dataset
val_dataset = tf.data.Dataset.from_tensor_slices(((X_val, y_val), y_val)).batch(16)

total_mse_agg = tf.keras.metrics.Mean()

print("Evaluating Diffusion Model on Validation Set...")

for (text_batch, params_batch), _ in val_dataset:
    # 1. Use the internal VAE encoder (Note: attribute is 'vae_encoder' in LDM)
    z_mean, z_log_var = best_model.vae_encoder([text_batch, params_batch], training=False)

    # 2. Sample Latent (z_0)
    eps = tf.random.normal(shape=tf.shape(z_mean))
    z_0 = z_mean + tf.exp(0.5 * z_log_var) * eps

    # 3. Diffusion Forward Process (Add Noise)
    batch_size = tf.shape(z_0)[0]
    # Sample random timesteps
    t = tf.random.uniform(minval=0, maxval=best_model.timesteps, shape=(batch_size,), dtype=tf.int32)
    # Generate ground truth noise
    noise = tf.random.normal(shape=tf.shape(z_0))

    # Add noise using the scheduler
    z_t = best_model.scheduler.add_noise(z_0, noise, t)

    # 4. Predict Noise using the Denoiser
    # (The LDM stores the denoiser network in 'best_model.denoiser')
    pred_noise = best_model.denoiser([z_t, t, text_batch], training=False)

    # 5. Calculate MSE (Noise Prediction Error)
    loss = tf.reduce_mean(tf.square(noise - pred_noise))
    total_mse_agg.update_state(loss)

print("-" * 30)
print(f"Validation Diffusion MSE: {total_mse_agg.result():.4f}")
print("-" * 30)

# Save is already handled in Cell 3.4, but we can re-save if desired
# best_model.save(os.path.join(SAVE_DIR, "ldm_final_eval.keras"))

"""# Test requests to model

### Subtask:
Implement code to test the end-to-end process with new text descriptions.

"""

# Cell 4.1 — Diffusion Inference Helpers

import numpy as np
import random
import tensorflow as tf
import json
import os
from tensorflow.keras.models import load_model

# ==============================================================================
# 1. HELPER FUNCTIONS
# ==============================================================================

def _safe_probs(raw_head):
    probs = np.array(raw_head, dtype=np.float32).reshape(-1)
    probs[probs < 0] = 0.0
    s = probs.sum()
    if not np.isfinite(s) or s <= 1e-6:
        probs = np.ones_like(probs, dtype=np.float32) / probs.size
    else:
        probs = probs / s
    return probs

def reconstruct_parameters_from_heads(predicted_outputs, parameter_types, categorical_num_classes, sample_categorical=True, noise_level=0.0):
    """
    Reconstructs parameter vector from split heads.
    """
    n_params = len(parameter_types)
    reconstructed = np.zeros(n_params, dtype=np.float32)

    # Extract indices based on parameter definition
    continuous_params = [int(i) for i, p in parameter_types.items() if p["type"] == "continuous"]
    mod_matrix_ids = set(range(170, 202))

    unipolar_indices = sorted([i for i in continuous_params if i not in mod_matrix_ids])
    bipolar_indices = sorted([i for i in continuous_params if i in mod_matrix_ids])
    boolean_params = sorted([int(i) for i, p in parameter_types.items() if p["type"] == "boolean"])
    categorical_params = sorted([int(i) for i, p in parameter_types.items() if p["type"] == "categorical"])

    head_idx = 0

    # 1. Unipolar Continuous
    if unipolar_indices:
        # Flatten predictions
        uni_head = np.array(predicted_outputs[head_idx], dtype=np.float32).reshape(-1)
        for i, param_idx in enumerate(unipolar_indices):
            reconstructed[param_idx] = uni_head[i]
        head_idx += 1

    # 2. Bipolar (Gate + Value)
    if bipolar_indices:
        gate_head = np.array(predicted_outputs[head_idx], dtype=np.float32).reshape(-1)
        val_head = np.array(predicted_outputs[head_idx+1], dtype=np.float32).reshape(-1)
        head_idx += 2
        for i, param_idx in enumerate(bipolar_indices):
            # Sigmoid for gate
            gate = 1.0 / (1.0 + np.exp(-gate_head[i]))
            # Tanh -> 0..1 for value
            val = (val_head[i] + 1.0) / 2.0

            if gate < 0.25:
                reconstructed[param_idx] = 0.5 # Default center
            else:
                reconstructed[param_idx] = val

    # 3. Boolean
    if boolean_params:
        bool_head = np.array(predicted_outputs[head_idx], dtype=np.float32).reshape(-1)
        head_idx += 1
        for i, param_idx in enumerate(boolean_params):
            reconstructed[param_idx] = 1.0 if bool_head[i] > 0.5 else 0.0

    # 4. Categorical
    for param_idx in categorical_params:
        head = predicted_outputs[head_idx]
        if isinstance(head, (list, tuple)): head = head[0]
        probs = _safe_probs(head)
        num_c = categorical_num_classes[param_idx]

        if sample_categorical:
            choice = np.random.choice(len(probs), p=probs)
        else:
            choice = np.argmax(probs)

        if num_c > 1:
            reconstructed[param_idx] = float(choice) / (num_c - 1)
        else:
            reconstructed[param_idx] = 0.0
        head_idx += 1

    return reconstructed

def generate_synth_parameters_vae(text_description, model, parameter_types, categorical_num_classes, sample_categorical=True, noise_level=0.0, seed=None, use_fixed_z=False):
    if seed is not None:
        import torch
        np.random.seed(seed)
        random.seed(seed)
        tf.random.set_seed(seed)
        torch.manual_seed(seed)

    # 1. Encode Text
    emb = clap_encode_text([text_description])

    # 2. Run Diffusion Generation Loop
    print(f"Diffusion Sampling for: '{text_description}'...")

    # !!! CRITICAL FIX: Use .generate(), NOT .predict() !!!
    # .generate() runs the 1000-step denoising loop
    preds = model.generate(emb, steps=1000)

    # 3. Reconstruct
    return reconstruct_parameters_from_heads(preds, parameter_types, categorical_num_classes, sample_categorical=sample_categorical, noise_level=noise_level)

def numpy_to_json(parameter_array, serum_parameters):
    output_json = {}
    flat_lookup = {}
    for group, params in serum_parameters.items():
        for p in params:
            flat_lookup[int(p["id"])] = p

    for idx, val in enumerate(parameter_array):
        if idx in flat_lookup:
            param_def = flat_lookup[idx]
            entry = param_def.copy()
            entry["value"] = float(val)
            output_json[str(idx)] = entry

    return output_json

# ==============================================================================
# 2. LOAD MODEL (If not already in memory)
# ==============================================================================

if 'best_model' not in globals():
    print("Variable 'best_model' not found. Attempting to load LDM...")
    saved_model_path = os.path.join(SAVE_DIR, "ldm_final.keras")

    if os.path.exists(saved_model_path):
        custom_objects = {
            "VAE_Text_to_Synth_Standard": VAE_Text_to_Synth_Standard,
            "LatentDiffusionModel": LatentDiffusionModel,
            "SinusoidalTimeEmbedding": SinusoidalTimeEmbedding,
            "ResidualBlock": ResidualBlock,
            "FiLM_Modulate": FiLM_Modulate,
            "FiLMLayer": FiLMLayer,
            "SliceLayer": SliceLayer
        }
        best_model = load_model(saved_model_path, custom_objects=custom_objects)
        print(f"✅ Loaded: {saved_model_path}")
    else:
        print("❌ Model not found. Run Cell 3.4 to train.")

# --- Run Test ---
test_prompt = "A deep, wobbling reese bass with slow filter movement"
param_map = {int(p['id']): p for g in SERUM_PARAMETERS.values() for p in g}

if 'best_model' in globals():
    generated_params = generate_synth_parameters_vae(
        text_description=test_prompt,
        model=best_model,
        parameter_types=param_map,
        categorical_num_classes=categorical_num_classes,
        sample_categorical=True,
        seed=42
    )

    preset_json = numpy_to_json(generated_params, SERUM_PARAMETERS)

    print("\n--- Generated Parameter Snippet ---")
    # Show first 3 params
    print(json.dumps({k: preset_json[k] for k in list(preset_json.keys())[:3]}, indent=2))

    # Show specific check (Mod Matrix)
    mod_val = preset_json["170"]["value"]
    print(f"\nMod Slot 1 (Gate Check): {mod_val:.4f} (Should be 0.5 if empty, distinct value if active)")

# --- Run a Test Prediction ---
test_prompt = "A deep, wobbling reese bass with slow filter movement"
print(f"Generating preset for: '{test_prompt}'...")

# Use globals to reconstruct types map if needed
param_map = {int(p['id']): p for g in SERUM_PARAMETERS.values() for p in g}

generated_params = generate_synth_parameters_vae(
    text_description=test_prompt,
    model=best_model,
    parameter_types=param_map,
    categorical_num_classes=categorical_num_classes,
    sample_categorical=True,
    noise_level=0.0,
    seed=None
)

preset_json = numpy_to_json(generated_params, SERUM_PARAMETERS)

print("\n--- Sample Results (Gated Mod Matrix) ---")
mod_val = preset_json["170"]["value"]
print(f"Mod 1 Amt (ID 170): {mod_val:.4f} (Should be 0.0 if inactive, or high value if active)")

print("\n--- Full JSON Snippet (First 3 items) ---")
print(json.dumps({k: preset_json[k] for k in list(preset_json.keys())[:203]}, indent=2))

"""# Data Interpolation and Visualization

## Parameter Latent Space Visualization
"""

# Cell 5.2 — 3D Visualization of Pure Latent Space (z_mean)

import numpy as np
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE
import pandas as pd
import seaborn as sns

# --- 0. HELPER FUNCTIONS ---
def get_sound_type(desc):
    d = str(desc).lower()
    if 'bass' in d: return 'Bass'
    if 'lead' in d: return 'Lead'
    if 'pad' in d: return 'Pad'
    if 'pluck' in d: return 'Pluck'
    if 'key' in d: return 'Keys'
    if 'fx' in d: return 'FX'
    if 'seq' in d or 'arp' in d: return 'Seq/Arp'
    if 'drum' in d or 'kick' in d or 'snare' in d: return 'Drums'
    return 'Other'

def get_genre(desc):
    d = str(desc).lower()
    if 'house' in d: return 'House'
    if 'techno' in d: return 'Techno'
    if 'dubstep' in d or 'riddim' in d: return 'Dubstep'
    if 'trap' in d: return 'Trap'
    if 'dnb' in d or 'drum & bass' in d: return 'DnB'
    if 'synthwave' in d or 'vaporwave' in d: return 'Synthwave'
    if 'cinematic' in d or 'ambient' in d: return 'Cinematic'
    if 'hip hop' in d: return 'Hip Hop'
    if 'pop' in d: return 'Pop'
    if 'midtempo' in d: return 'Midtempo'
    if 'future' in d: return 'Future Bass'
    return 'Other'

# --- 1. GENERATE LATENT VECTORS ---
SUBSET_SIZE = 3000
indices = np.random.choice(len(serum_preset_descriptions), size=min(SUBSET_SIZE, len(serum_preset_descriptions)), replace=False)

# Extract inputs
subset_text = description_embeddings[indices]
subset_params = serum_params[indices]
subset_desc = serum_preset_descriptions[indices]

print("Encoding parameters into latent space...")

# !!! FIXED: Access .vae_encoder instead of .encoder
z_mean_pure, _ = best_model.vae_encoder.predict([subset_text, subset_params], verbose=0)

# --- 2. RUN 3D t-SNE ON z_mean ONLY ---
print(f"Running 3D t-SNE on pure latent vectors (shape: {z_mean_pure.shape})...")
tsne_pure = TSNE(n_components=3, random_state=42, perplexity=30, init='pca', learning_rate='auto')
emb_3d_pure = tsne_pure.fit_transform(z_mean_pure)

# --- 3. APPLY LABELS ---
df_latent = pd.DataFrame({
    'x': emb_3d_pure[:, 0],
    'y': emb_3d_pure[:, 1],
    'z': emb_3d_pure[:, 2],
    'Sound Type': [get_sound_type(t) for t in subset_desc],
    'Genre': [get_genre(t) for t in subset_desc]
})

# --- 4. PLOTTING FUNCTION ---
def plot_pure_latent(df, category_col, title):
    fig = plt.figure(figsize=(12, 10))
    ax = fig.add_subplot(111, projection='3d')
    df_clean = df[df[category_col] != 'Other']
    unique_cats = sorted(df_clean[category_col].unique())
    palette = sns.color_palette("tab10", len(unique_cats))

    for idx, cat in enumerate(unique_cats):
        subset = df_clean[df_clean[category_col] == cat]
        ax.scatter(subset['x'], subset['y'], subset['z'], label=cat, s=25, alpha=0.8, c=[palette[idx]])

    ax.set_title(title, fontsize=15)
    ax.view_init(elev=20, azim=45)
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.show()

# Visualize
plot_pure_latent(df_latent, 'Sound Type', '3D Pure Latent Space: Organised by Sound Type')

"""## Merged Latent Space Visualization"""

# Cell 5.3 — 3D Visualization of the Decoder "Merged" Space (Text + Latent)

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D  # noqa: F401
from sklearn.manifold import TSNE
import pandas as pd
import seaborn as sns
from tensorflow.keras.models import Model

# --- 1. CONFIGURATION & DATA PREP ---
SUBSET_SIZE = 3000
np.random.seed(42)

if 'best_model' in globals():
    # Pick random indices
    indices = np.random.choice(
        len(serum_preset_descriptions),
        size=min(SUBSET_SIZE, len(serum_preset_descriptions)),
        replace=False
    )

    subset_text   = description_embeddings[indices]
    subset_desc   = serum_preset_descriptions[indices]
    subset_params = serum_params[indices]

    print(f"Using {len(subset_desc)} points from the dataset...")

    # --- 2. ENCODE ---
    print("Step 1: Generating latent vectors (z_mean) from encoder...")
    # !!! FIXED: .vae_encoder
    z_mean, _ = best_model.vae_encoder.predict([subset_text, subset_params], verbose=0)

    # --- 3. EXTRACT MERGED DECODER FEATURES ---
    # !!! FIXED: .vae_decoder
    decoder = best_model.vae_decoder

    # In the new FiLM architecture, text and z are not concatenated simply.
    # We will visualize the Latent Space itself (z_mean) as the primary manifold.
    # If specific intermediate layers are needed, we can target "dec_dense_mid"
    target_layer = None
    for layer in decoder.layers:
        if "dec_dense_mid" in layer.name: # Intermediate dense layer
            target_layer = layer
            break

    if target_layer is not None:
        print(f"Step 2: Extracting features from layer: {target_layer.name}")
        vis_model = Model(inputs=decoder.inputs, outputs=target_layer.output)
        merged_features = vis_model.predict([z_mean, subset_text], verbose=0)
    else:
        print("Warning: Intermediate layer not found, using z_mean directly.")
        merged_features = z_mean

    # --- 4. RUN 3D t-SNE ---
    print(f"Running 3D t-SNE on {merged_features.shape[0]} points...")
    tsne_3d = TSNE(n_components=3, random_state=42, perplexity=30, init='pca', learning_rate='auto')
    emb_3d = tsne_3d.fit_transform(merged_features)

    # --- 5. LABEL EXTRACTION ---
    # (Helper functions assumed defined in previous cells or above)
    def get_descriptor(desc):
        d = str(desc).lower()
        if 'metallic' in d: return 'Metallic'
        if 'bright' in d: return 'Bright'
        if 'dark' in d: return 'Dark'
        if 'warm' in d: return 'Warm'
        if 'dirty' in d: return 'Dirty'
        if 'clean' in d: return 'Clean'
        if 'aggressive' in d: return 'Aggressive'
        if 'soft' in d: return 'Soft'
        if 'deep' in d: return 'Deep'
        return 'Other'

    df_3d = pd.DataFrame({
        'x': emb_3d[:, 0], 'y': emb_3d[:, 1], 'z': emb_3d[:, 2],
        'Sound Type': [get_sound_type(t) for t in subset_desc],
        'Genre': [get_genre(t) for t in subset_desc],
        'Descriptor': [get_descriptor(t) for t in subset_desc]
    })

    # --- 6. PLOTTING ---
    def plot_3d_scatter(df, category_col, title):
        fig = plt.figure(figsize=(12, 10))
        ax = fig.add_subplot(111, projection='3d')
        df_clean = df[df[category_col] != 'Other']
        unique_cats = sorted(df_clean[category_col].unique())
        palette = sns.color_palette("tab10", len(unique_cats))

        for idx, cat in enumerate(unique_cats):
            subset = df_clean[df_clean[category_col] == cat]
            ax.scatter(subset['x'], subset['y'], subset['z'], label=cat, s=20, alpha=0.7, c=[palette[idx]])

        df_other = df[df[category_col] == 'Other']
        if len(df_other) > 0:
            ax.scatter(df_other['x'], df_other['y'], df_other['z'], c='lightgrey', s=5, alpha=0.1)

        ax.set_title(title, fontsize=15)
        ax.view_init(elev=30, azim=120)
        plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
        plt.show()

    print("Generating Decoder Image 1: Sound Type...")
    plot_3d_scatter(df_3d, 'Sound Type', '3D Space: Sound Type')

    print("Generating Decoder Image 2: Genre...")
    plot_3d_scatter(df_3d, 'Genre', '3D Space: Genre')

else:
    print("Error: 'best_model' not found.")

"""## Interpolations"""

# Cell 5.4 — Latent Space Interpolation & Visualization

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

def interpolate_prompts(model, start_prompt, end_prompt, steps=10, z_seed=42):
    """
    Morphs between two text descriptions using the VAE Decoder.
    Note: This bypasses the Diffusion Denoiser to show the VAE's smooth latent manifold.
    """
    # 1. Encode both prompts
    emb_start = clap_encode_text([start_prompt])[0]
    emb_end = clap_encode_text([end_prompt])[0]

    # 2. Fixed Z (use mean 0 for "standard" representation)
    np.random.seed(z_seed)
    z_fixed = np.random.normal(size=(1, int(model.vae_encoder.output_shape[0][1]))).astype('float32')

    # 3. Linear Interpolation
    interpolated_params = []
    alphas = np.linspace(0, 1, steps)

    print(f"Morphing: '{start_prompt}' -> '{end_prompt}'")

    for alpha in alphas:
        # Interpolate text embedding
        emb_interp = (1 - alpha) * emb_start + alpha * emb_end
        emb_interp = emb_interp.reshape(1, -1)

        # !!! FIXED: Use .vae_decoder
        preds = model.vae_decoder.predict([z_fixed, emb_interp], verbose=0)

        # Reconstruct
        param_map = {int(p['id']): p for g in SERUM_PARAMETERS.values() for p in g}
        params = reconstruct_parameters_from_heads(
            preds,
            parameter_types=param_map,
            categorical_num_classes=categorical_num_classes,
            sample_categorical=False, # Deterministic for smooth plots
            noise_level=0.0
        )
        interpolated_params.append(params)

    return np.array(interpolated_params), alphas

# --- CONFIG ---
prompt_a = "Aggressive, Dubstep, Bass"
prompt_b = "Soft, Ambient, Pad"

if 'best_model' in globals():
    interp_data, alphas = interpolate_prompts(best_model, prompt_a, prompt_b, steps=20)

    # --- PARAMETERS TO TRACK ---
    params_to_plot = [
        {"id": 6,   "name": "Osc A Octave",     "color": "blue"},
        {"id": 49,  "name": "Sub Osc Level",    "color": "darkgreen"},
        {"id": 59,  "name": "Filter Cutoff",    "color": "red"},
        {"id": 60,  "name": "Filter Resonance", "color": "orange"},
        {"id": 65,  "name": "Env1 Attack",      "color": "purple"},
        {"id": 75,  "name": "LFO1 Rate",        "color": "brown"},
        {"id": 91,  "name": "Dist Wet",         "color": "pink"},
        {"id": 147, "name": "Reverb Size",      "color": "cyan"},
    ]

    # --- PLOTTING ---
    plt.figure(figsize=(12, 6))
    for p in params_to_plot:
        col_idx = p["id"]
        values = interp_data[:, col_idx]
        plt.plot(alphas, values, marker='o', label=p["name"], color=p["color"], linewidth=2, alpha=0.8)

    plt.title(f"Parameter Morphing:\n'{prompt_a}'  >>>  '{prompt_b}'")
    plt.xlabel("Interpolation Alpha")
    plt.ylabel("Normalized Parameter Value (0-1)")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.show()
else:
    print("Model not loaded.")

