# -*- coding: utf-8 -*-
"""V2.7 REFINED OSC WER - Latent Diffusion - ResMLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I0DoH7lWcSBCiKNyzIqEBgYtizlZrmyc

# Model Overview

This notebook implements a **two-stage Text -> Serum-parameter generator**:

1) **Stage 1: Conditional VAE** learns a compact latent space for synth presets.  
2) **Stage 2: Latent Diffusion** learns to sample high-quality latents from text alone, then decodes them back into full parameter vectors.

The goal is to keep the decoder faithful to the synth's parameter manifold, while letting diffusion handle multi-modality and diversity (many different knob settings can yield similar sounds).

---

## 1. Stage 1: Conditional VAE (Compression Model)

The VAE models a distribution over latents conditioned on both:
- **x**: 202 Serum parameters (continuous, boolean, categorical, plus mod-matrix handling)
- **c**: CLAP text embedding (512-dim)

### Posterior (training-time inference)
- **Posterior**:  \( q(z \mid x, c) \)  
  The encoder consumes **(text embedding + parameter vector)** and outputs \( z\_mean, z\_log\_var \).

### Prior (this version)
- **Standard Normal Prior**:  \( p(z) = \mathcal{N}(0, I) \)  
  In this notebook, the VAE is treated as the **compression stage** for diffusion, so we use a standard Gaussian KL term.

### Decoder
- **Decoder**:  \( p(x \mid z, c) \)  
  The decoder consumes **(latent z + text embedding)** and produces the parameter heads described below.

---

## 2. Conditioning: CLAP + FiLM (Text steers generation)

- **CLAP text encoder**
  Uses `laion/clap-htsat-fused` to convert prompts into stable 512-dim vectors.

- **FiLM in the VAE decoder**
  Instead of only concatenating text, the decoder applies **Feature-wise Linear Modulation (FiLM)** so the text embedding can scale and shift internal activations. This makes the prompt act like a "control signal" throughout decoding, not just an input feature.

- **FiLM in the diffusion denoiser**
  The ResMLP denoiser also uses FiLM-style modulation, conditioned on **(time embedding + text embedding)** so the denoising trajectory stays prompt-consistent at every step.

---

## 3. Activity Gating (Hierarchical constraints)

Serum has an explicit signal path (modules can be off). This notebook includes **group masking** logic so training respects that structure:

- If an enable switch is off (for example Osc A On = 0), then dependent knobs in that module are masked out of reconstruction loss.
- This prevents the model from wasting capacity learning arbitrary settings for silent modules.

---

## 4. Multi-head Outputs (Correct math for each parameter type)

The decoder outputs specialized heads so each parameter type is modeled appropriately:

- **Unipolar continuous knobs (0..1)**  
  Sigmoid output, MSE loss

- **Bipolar mod-matrix amounts (sparse, signed)**  
  Two-head strategy:
  - gate head (logits) trained with focal-style loss to handle sparsity  
  - value head (tanh) trained with regression loss only when the gate is active

- **Boolean switches**  
  Sigmoid output, binary cross-entropy

- **Categorical menus (filter types, rates, modes)**  
  Softmax output per categorical parameter, sparse categorical cross-entropy

---

## 5. Stage 2: Latent Diffusion (Sampling model)

Diffusion is trained in **latent space**, not parameter space:

1) Encode real presets into latents:
   - sample \( z_0 \sim q(z \mid x, c) \) using the frozen VAE encoder
2) Add noise across timesteps:
   - \( z_t = \alpha_t z_0 + \sigma_t \epsilon \)
3) Train a denoiser to predict the noise:
   - denoiser inputs: \( (z_t, t, c) \)
   - objective: MSE between true noise \( \epsilon \) and predicted noise \( \hat{\epsilon} \)

### Denoiser architecture: ResMLP + FiLM
- Sinusoidal time embedding
- Conditioning vector = time embedding + text embedding
- Stack of residual MLP blocks that are FiLM-modulated by the conditioning vector
- Output predicts per-dimension latent noise

### Sampling
At inference:
- Start from random noise \( z_T \)
- Iteratively denoise back to \( z_0 \) using the trained denoiser
- Decode final latent with the frozen VAE decoder to produce the parameter heads

---

## 6. Training stability strategies

- **Beta annealing (Stage 1)**  
  Warm up the KL weight over early epochs to prioritize reconstruction first.

- **Latent dropout (Stage 1)**  
  Occasionally zero out z so the decoder learns to rely on the prompt, not only the latent.

- **Frozen VAE during diffusion (Stage 2)**  
  The denoiser learns the latent distribution while the VAE defines the latent manifold.
"""

# Cell 1.1

# CLEAN START: remove default packages
!pip uninstall -y dopamine-rl flax chex optax orbax-checkpoint tensorflow-hub keras-hub ydf jax jaxlib tf-keras tensorflow-text tensorflow-decision-forests || true

# Install a minimal, compatible stack for Colab
!pip install -q --upgrade pip
!pip install -q "numpy==2.0.2" "tensorflow==2.19.0" \
                "transformers==4.45.2" "sentence-transformers==2.7.0"

# Install CUDA wheels for PyTorch (GPU / T4).
!pip install -q "torch==2.8.0" "torchvision==0.23.0" "torchaudio==2.8.0" \
  --extra-index-url https://download.pytorch.org/whl/cu126

# Sanity check: Print what GPU using
!nvidia-smi -L || true

# Cell 1.2 — GPU Setup

import os
import numpy as np
import tensorflow as tf
from tensorflow import keras

# Tensorflow log level
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

# GPU Setup
gpus = tf.config.list_physical_devices("GPU")
print("GPUs visible to TF:", gpus)
for gpu in gpus:
    try:
        tf.config.experimental.set_memory_growth(gpu, True)
    except Exception as e:
        print("Could not set memory growth:", e)

print("TF:", tf.__version__)
print("tf.keras:", keras.__version__)
print("NumPy:", np.__version__)

# Cell 1.3
# Mount Drive, Setup save directory

import os
from google.colab import drive

# 1. Mount Drive (Force remount to ensure fresh connection)
drive.mount('/content/drive', force_remount=True)

# 2. Define your Save Directory clearly
# Using a variable ensures you don't have typos in different cells
SAVE_DIR = "/content/drive/My Drive/Colab Notebooks/notebooks/models/vae/text_input/V2 - Activity Gating, FiLM/v2p7 - REFINED OSC VECTORS/output_models"

# 3. Create the directory (and all intermediate folders) if they don't exist
try:
    os.makedirs(SAVE_DIR, exist_ok=True)
    print(f"✅ Directory confirmed: {SAVE_DIR}")
except OSError as e:
    print(f"❌ Error creating directory: {e}")

# 4. Write Test
# Create a dummy file to verify we actually have write permissions before training starts
test_file = os.path.join(SAVE_DIR, "write_test.txt")
try:
    with open(test_file, "w") as f:
        f.write("Access granted.")
    os.remove(test_file) # Clean up
    print("✅ Write access confirmed. You are ready to train.")
except Exception as e:
    print(f"❌ Write access FAILED: {e}")
    print("Check your Drive permissions or path string.")

# Cell 1.4 — Initialize CLAP Text Encoder
import torch
from transformers import ClapModel, ClapProcessor

# Use GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

# CLAP Model Initialization
clap_model_name = "laion/clap-htsat-fused"
clap_model = ClapModel.from_pretrained(clap_model_name).to(device)
clap_processor = ClapProcessor.from_pretrained(clap_model_name)

# Set to 'eval' to disable dropout/batch norm updates
clap_model.eval()

@torch.no_grad()
def clap_encode_text(texts, batch_size=128, normalize=True, max_length=77):
    """
    Encodes a list of strings into a NumPy array of embeddings.
    """
    out = []
    # Ensure inputs are a list of strings
    if isinstance(texts, np.ndarray):
        texts = texts.tolist()

    for i in range(0, len(texts), batch_size):
        batch = [str(t) for t in texts[i:i+batch_size]]

        # FIX 1: Force max_length padding.
        # This ensures every batch output has shape (B, 77, ...) preventing cat errors
        # even if we accidentally grab the sequence hidden states.
        inputs = clap_processor(
            text=batch,
            return_tensors="pt",
            padding="max_length", # <--- FORCE FIXED LENGTH
            truncation=True,
            max_length=max_length
        ).to(device)

        # Forward pass
        outputs = clap_model.get_text_features(**inputs)

        # FIX 2: Explicitly handle output types to ensure (Batch, 512)
        if isinstance(outputs, torch.Tensor):
            feats = outputs
        elif hasattr(outputs, 'text_embeds'):
            feats = outputs.text_embeds
        elif hasattr(outputs, 'text_features'): # Sometimes named this
            feats = outputs.text_features
        else:
             # Fallback: If we got a sequence (B, T, D), assume [0] is expected output or pool it
            temp = outputs[0]
            if len(temp.shape) == 3:
                # If we accidentally got (Batch, Seq, Dim), take the CLS token or mean
                # CLAP usually uses the projection, but if we are here, something is odd.
                # Take the first token (CLS equivalent) or max pool
                feats = temp.mean(dim=1)
            else:
                feats = temp

        # Verify shape is 2D (Batch, Dim) before normalizing
        if len(feats.shape) == 3:
             feats = feats.mean(dim=1) # Flatten if still 3D

        # L2 Normalization
        if normalize:
            feats = torch.nn.functional.normalize(feats, dim=-1)

        out.append(feats.cpu())

    # Concatenate - now safe because size is fixed
    return torch.cat(out, dim=0).numpy()

print(f"✅ CLAP loaded and ready on: {device}")

"""# Load Data"""

# Cell 2.1

import numpy as np
import os

# 1. Load the Serum parameters (Targets A)
serum_params = np.load(
    '/content/drive/My Drive/Colab Notebooks/data/vectors/cleaned/combined/combined_params_categorical.npy',
    allow_pickle=True
).astype('float32')

# 2. Load the Preset Descriptions (Input Text)
serum_preset_descriptions = np.load(
    '/content/drive/My Drive/Colab Notebooks/data/vectors/cleaned/combined/combined_descriptions.npy',
    allow_pickle=True
)

# 3. Load the Oscillator CLAP Embeddings (Targets B)
# Shape: (N, 3, 512) -> [Osc A, Osc B, Noise]
osc_embeddings = np.load(
    '/content/drive/My Drive/Colab Notebooks/data/vectors/combined_clap_embeddings.npy',
    allow_pickle=True
).astype('float32')

# 4. Load the Validity Mask
# Shape: (N, 3) -> 1.0 if oscillator exists, 0.0 if silent/missing
osc_masks = np.load(
    '/content/drive/My Drive/Colab Notebooks/data/vectors/combined_clap_validity_mask.npy',
    allow_pickle=True
).astype('float32')

# ==============================================================================
# 5. NEW: Load Default Wavetable/Noise Libraries (For Inference Lookup)
# ==============================================================================
LIB_DIR = '/content/drive/My Drive/Colab Notebooks/data/vectors'

try:
    WT_LIB_NAMES = np.load(os.path.join(LIB_DIR, 'default_wavetable_names.npy'), allow_pickle=True)
    WT_LIB_EMBEDS = np.load(os.path.join(LIB_DIR, 'default_wavetable_embeddings.npy'), allow_pickle=True).astype('float32')
    NOISE_LIB_NAMES = np.load(os.path.join(LIB_DIR, 'default_noise_names.npy'), allow_pickle=True)
    NOISE_LIB_EMBEDS = np.load(os.path.join(LIB_DIR, 'default_noise_embeddings.npy'), allow_pickle=True).astype('float32')
    print("✅ Default Audio Libraries Loaded Successfully.")
except FileNotFoundError as e:
    print(f"⚠️ Reference libraries not found. Inference matching will fail. Error: {e}")
    WT_LIB_NAMES, WT_LIB_EMBEDS, NOISE_LIB_NAMES, NOISE_LIB_EMBEDS = None, None, None, None

# ==============================================================================

print("\n--- Original Data Shapes ---")
print(f"Serum Params:       {serum_params.shape}")
print(f"Descriptions:       {serum_preset_descriptions.shape}")
print(f"Osc Embeddings:     {osc_embeddings.shape}")
print(f"Osc Masks:          {osc_masks.shape}")

# --- APPLY VALIDITY MASK FILTERING ---
# We only want to train on presets where ALL oscillators (A, B, Noise) are present.
# We look for rows where the mask is [1, 1, 1]
valid_indices = np.all(osc_masks > 0.5, axis=1)

# Apply filter to all arrays
serum_params = serum_params[valid_indices]
serum_preset_descriptions = serum_preset_descriptions[valid_indices]
osc_embeddings = osc_embeddings[valid_indices]
osc_masks = osc_masks[valid_indices]

print("\n--- Filtered Data Shapes (Fully Valid Only) ---")
print(f"Serum Params:       {serum_params.shape}")
print(f"Descriptions:       {serum_preset_descriptions.shape}")
print(f"Osc Embeddings:     {osc_embeddings.shape}")

# Flatten the embeddings for the Encoder Input: (N, 3, 512) -> (N, 1536)
osc_embeddings_flat = osc_embeddings.reshape(osc_embeddings.shape[0], -1)
print(f"Osc Flat Input:     {osc_embeddings_flat.shape}")

# Cell 2.2
# SERUM_PARAMETERS - MANUALLY CLEANED AND RE-INDEXED (0-201)

SERUM_PARAMETERS = {
    "global": [
        {"id": "0", "serum_id": "0", "name": "MasterVol", "type": "continuous"},
        {"id": "1", "serum_id": "65", "name": "PortTime", "type": "continuous"},
        {"id": "2", "serum_id": "66", "name": "PortCurve", "type": "continuous"}
    ],
    "osc_a": [
        {"id": "3", "serum_id": "212", "name": "Osc A On", "type": "boolean"},
        {"id": "4", "serum_id": "1", "name": "A Vol", "type": "continuous"},
        {"id": "5", "serum_id": "2", "name": "A Pan", "type": "continuous"},
        {"id": "6", "serum_id": "3", "name": "A Octave", "type": "categorical", "num_categories": 9},
        {"id": "7", "serum_id": "4", "name": "A Semi", "type": "categorical", "num_categories": 25},
        {"id": "8", "serum_id": "5", "name": "A Fine", "type": "continuous"},
        {"id": "9", "serum_id": "10", "name": "A CoarsePit", "type": "continuous"},
        {"id": "10", "serum_id": "6", "name": "A Unison", "type": "continuous"},
        {"id": "11", "serum_id": "7", "name": "A UniDet", "type": "continuous"},
        {"id": "12", "serum_id": "8", "name": "A UniBlend", "type": "continuous"},
        {"id": "13", "serum_id": "172", "name": "A Uni LR", "type": "continuous"},
        {"id": "14", "serum_id": "174", "name": "A Uni Warp", "type": "continuous"},
        {"id": "15", "serum_id": "176", "name": "A Uni WTPos", "type": "continuous"},
        {"id": "16", "serum_id": "178", "name": "A Uni Stack", "type": "categorical", "num_categories": 9},
        {"id": "17", "serum_id": "11", "name": "A WTPos", "type": "continuous"},
        {"id": "18", "serum_id": "168", "name": "WarpOscA", "type": "categorical", "num_categories": 23},
        {"id": "19", "serum_id": "9", "name": "A Warp", "type": "continuous"},
        {"id": "20", "serum_id": "12", "name": "A RandPhase", "type": "continuous"},
        {"id": "21", "serum_id": "13", "name": "A Phase", "type": "continuous"}
    ],
    "osc_b": [
        {"id": "22", "serum_id": "213", "name": "Osc B On", "type": "boolean"},
        {"id": "23", "serum_id": "14", "name": "B Vol", "type": "continuous"},
        {"id": "24", "serum_id": "15", "name": "B Pan", "type": "continuous"},
        {"id": "25", "serum_id": "16", "name": "B Octave", "type": "categorical", "num_categories": 9},
        {"id": "26", "serum_id": "17", "name": "B Semi", "type": "categorical", "num_categories": 25},
        {"id": "27", "serum_id": "18", "name": "B Fine", "type": "continuous"},
        {"id": "28", "serum_id": "23", "name": "B CoarsePit", "type": "continuous"},
        {"id": "29", "serum_id": "19", "name": "B Unison", "type": "continuous"},
        {"id": "30", "serum_id": "20", "name": "B UniDet", "type": "continuous"},
        {"id": "31", "serum_id": "21", "name": "B UniBlend", "type": "continuous"},
        {"id": "32", "serum_id": "173", "name": "B Uni LR", "type": "continuous"},
        {"id": "33", "serum_id": "175", "name": "B Uni Warp", "type": "continuous"},
        {"id": "34", "serum_id": "177", "name": "B Uni WTPos", "type": "continuous"},
        {"id": "35", "serum_id": "179", "name": "B Uni Stack", "type": "categorical", "num_categories": 9},
        {"id": "36", "serum_id": "24", "name": "B WTPos", "type": "continuous"},
        {"id": "37", "serum_id": "169", "name": "WarpOscB", "type": "categorical", "num_categories": 23},
        {"id": "38", "serum_id": "22", "name": "B Warp", "type": "continuous"},
        {"id": "39", "serum_id": "25", "name": "B RandPhase", "type": "continuous"},
        {"id": "40", "serum_id": "26", "name": "B Phase", "type": "continuous"}
    ],
    "noise_osc": [
        {"id": "41", "serum_id": "214", "name": "Osc N On", "type": "boolean"},
        {"id": "42", "serum_id": "27", "name": "Noise Level", "type": "continuous"},
        {"id": "43", "serum_id": "28", "name": "Noise Pitch", "type": "continuous"},
        {"id": "44", "serum_id": "29", "name": "Noise Fine", "type": "continuous"},
        {"id": "45", "serum_id": "30", "name": "Noise Pan", "type": "continuous"},
        {"id": "46", "serum_id": "31", "name": "Noise RandPhase", "type": "continuous"},
        {"id": "47", "serum_id": "32", "name": "Noise Phase", "type": "continuous"}
    ],
    "sub_osc": [
        {"id": "48", "serum_id": "215", "name": "Osc S On", "type": "boolean"},
        {"id": "49", "serum_id": "33", "name": "Sub Osc Level", "type": "continuous"},
        {"id": "50", "serum_id": "34", "name": "Sub Osc Pan", "type": "continuous"},
        {"id": "51", "serum_id": "170", "name": "SubOscShape", "type": "categorical", "num_categories": 6},
        {"id": "52", "serum_id": "171", "name": "SubOscOctave", "type": "continuous"}
    ],
    "filter": [
        {"id": "53", "serum_id": "216", "name": "Filter On", "type": "boolean"},
        {"id": "54", "serum_id": "44", "name": "Fil Type", "type": "categorical", "num_categories": 95},
        {"id": "55", "serum_id": "40", "name": "OscA>Fil", "type": "boolean"},
        {"id": "56", "serum_id": "41", "name": "OscB>Fil", "type": "boolean"},
        {"id": "57", "serum_id": "42", "name": "OscN>Fil", "type": "boolean"},
        {"id": "58", "serum_id": "43", "name": "OscS>Fil", "type": "boolean"},
        {"id": "59", "serum_id": "45", "name": "Fil Cutoff", "type": "continuous"},
        {"id": "60", "serum_id": "46", "name": "Fil Reso", "type": "continuous"},
        {"id": "61", "serum_id": "47", "name": "Fil Driv", "type": "continuous"},
        {"id": "62", "serum_id": "48", "name": "Fil Var", "type": "continuous"},
        {"id": "63", "serum_id": "49", "name": "Fil Mix", "type": "continuous"},
        {"id": "64", "serum_id": "50", "name": "Fil Stereo", "type": "continuous"}
    ],
    "envelopes": [
        {"id": "65", "serum_id": "35", "name": "Env1 Atk", "type": "continuous"},
        {"id": "66", "serum_id": "36", "name": "Env1 Hold", "type": "continuous"},
        {"id": "67", "serum_id": "37", "name": "Env1 Dec", "type": "continuous"},
        {"id": "68", "serum_id": "38", "name": "Env1 Sus", "type": "continuous"},
        {"id": "69", "serum_id": "39", "name": "Env1 Rel", "type": "continuous"},
        {"id": "70", "serum_id": "51", "name": "Env2 Atk", "type": "continuous"},
        {"id": "71", "serum_id": "52", "name": "Env2 Hold", "type": "continuous"},
        {"id": "72", "serum_id": "53", "name": "Env2 Dec", "type": "continuous"},
        {"id": "73", "serum_id": "54", "name": "Env2 Sus", "type": "continuous"},
        {"id": "74", "serum_id": "55", "name": "Env2 Rel", "type": "continuous"}
    ],
    "lfos": [
        {"id": "75", "serum_id": "61", "name": "LFO1 Rate", "type": "categorical", "num_categories": 19},
        {"id": "76", "serum_id": "273", "name": "LFO1 Rise", "type": "categorical", "num_categories": 20},
        {"id": "77", "serum_id": "281", "name": "LFO1 Delay", "type": "categorical", "num_categories": 20},
        {"id": "78", "serum_id": "223", "name": "LFO1 Smooth", "type": "continuous"},
        {"id": "79", "serum_id": "62", "name": "LFO2 Rate", "type": "categorical", "num_categories": 19},
        {"id": "80", "serum_id": "274", "name": "LFO2 Rise", "type": "categorical", "num_categories": 20},
        {"id": "81", "serum_id": "282", "name": "LFO2 Delay", "type": "categorical", "num_categories": 20},
        {"id": "82", "serum_id": "224", "name": "LFO2 Smooth", "type": "continuous"}
    ],
    "fx_hyper_dimension": [
        {"id": "83", "serum_id": "163", "name": "Hyp Enable", "type": "boolean"},
        {"id": "84", "serum_id": "148", "name": "Hyp_Rate", "type": "continuous"},
        {"id": "85", "serum_id": "149", "name": "Hyp_Detune", "type": "continuous"},
        {"id": "86", "serum_id": "150", "name": "Hyp_Unison", "type": "continuous"},
        {"id": "87", "serum_id": "147", "name": "Hyp_Wet", "type": "continuous"},
        {"id": "88", "serum_id": "152", "name": "HypDim_Size", "type": "continuous"},
        {"id": "89", "serum_id": "153", "name": "HypDim_Mix", "type": "continuous"}
    ],
    "fx_distortion": [
        {"id": "90", "serum_id": "154", "name": "Dist Enable", "type": "boolean"},
        {"id": "91", "serum_id": "96", "name": "Dist_Wet", "type": "continuous"},
        {"id": "92", "serum_id": "97", "name": "Dist_Drv", "type": "continuous"},
        {"id": "93", "serum_id": "99", "name": "Dist_Mode", "type": "categorical", "num_categories": 16},
        {"id": "94", "serum_id": "102", "name": "Dist_PrePost", "type": "categorical", "num_categories": 3},
        {"id": "95", "serum_id": "98", "name": "Dist_L/B/H", "type": "categorical", "num_categories": 3},
        {"id": "96", "serum_id": "100", "name": "Dist_Freq", "type": "continuous"},
        {"id": "97", "serum_id": "101", "name": "Dist_BW", "type": "continuous"}
    ],
    "fx_flanger": [
        {"id": "98", "serum_id": "155", "name": "Flg Enable", "type": "boolean"},
        {"id": "99", "serum_id": "103", "name": "Flg_Wet", "type": "continuous"},
        {"id": "100", "serum_id": "104", "name": "Flg_BPM_Sync", "type": "boolean"},
        {"id": "101", "serum_id": "105", "name": "Flg_Rate", "type": "continuous"},
        {"id": "102", "serum_id": "106", "name": "Flg_Dep", "type": "continuous"},
        {"id": "103", "serum_id": "107", "name": "Flg_Feed", "type": "continuous"},
        {"id": "104", "serum_id": "108", "name": "Flg_Stereo", "type": "continuous"}
    ],
    "fx_phaser": [
        {"id": "105", "serum_id": "156", "name": "Phs Enable", "type": "boolean"},
        {"id": "106", "serum_id": "109", "name": "Phs_Wet", "type": "continuous"},
        {"id": "107", "serum_id": "110", "name": "Phs_BPM_Sync", "type": "boolean"},
        {"id": "108", "serum_id": "111", "name": "Phs_Rate", "type": "continuous"},
        {"id": "109", "serum_id": "112", "name": "Phs_Dpth", "type": "continuous"},
        {"id": "110", "serum_id": "113", "name": "Phs_Frq", "type": "continuous"},
        {"id": "111", "serum_id": "114", "name": "Phs_Feed", "type": "continuous"},
        {"id": "112", "serum_id": "115", "name": "Phs_Stereo", "type": "continuous"}
    ],
    "fx_chorus": [
        {"id": "113", "serum_id": "157", "name": "Cho Enable", "type": "boolean"},
        {"id": "114", "serum_id": "116", "name": "Cho_Wet", "type": "continuous"},
        {"id": "115", "serum_id": "117", "name": "Cho_BPM_Sync", "type": "boolean"},
        {"id": "116", "serum_id": "118", "name": "Cho_Rate", "type": "continuous"},
        {"id": "117", "serum_id": "119", "name": "Cho_Dly", "type": "continuous"},
        {"id": "118", "serum_id": "120", "name": "Cho_Dly2", "type": "continuous"},
        {"id": "119", "serum_id": "121", "name": "Cho_Dep", "type": "continuous"},
        {"id": "120", "serum_id": "122", "name": "Cho_Feed", "type": "continuous"},
        {"id": "121", "serum_id": "123", "name": "Cho_Filt", "type": "continuous"}
    ],
    "fx_delay": [
        {"id": "122", "serum_id": "158", "name": "Dly Enable", "type": "boolean"},
        {"id": "123", "serum_id": "124", "name": "Dly_Wet", "type": "continuous"},
        {"id": "124", "serum_id": "125", "name": "Dly_Freq", "type": "continuous"},
        {"id": "125", "serum_id": "126", "name": "Dly_BW", "type": "continuous"},
        {"id": "126", "serum_id": "127", "name": "Dly_BPM_Sync", "type": "boolean"},
        {"id": "127", "serum_id": "128", "name": "Dly_Link", "type": "boolean"},
        {"id": "128", "serum_id": "129", "name": "Dly_TimL", "type": "categorical", "num_categories": 12},
        {"id": "129", "serum_id": "130", "name": "Dly_TimR", "type": "categorical", "num_categories": 12},
        {"id": "130", "serum_id": "131", "name": "Dly_Mode", "type": "categorical", "num_categories": 3},
        {"id": "131", "serum_id": "132", "name": "Dly_Feed", "type": "continuous"},
        {"id": "132", "serum_id": "133", "name": "Dly_Off L", "type": "continuous"},
        {"id": "133", "serum_id": "134", "name": "Dly_Off R", "type": "continuous"}
    ],
    "fx_compressor": [
        {"id": "134", "serum_id": "159", "name": "Comp Enable", "type": "boolean"},
        {"id": "135", "serum_id": "135", "name": "Cmp_Thr", "type": "continuous"},
        {"id": "136", "serum_id": "136", "name": "Cmp_Rat", "type": "categorical", "num_categories": 21},
        {"id": "137", "serum_id": "137", "name": "Cmp_Att", "type": "continuous"},
        {"id": "138", "serum_id": "138", "name": "Cmp_Rel", "type": "continuous"},
        {"id": "139", "serum_id": "139", "name": "CmpGain", "type": "continuous"},
        {"id": "140", "serum_id": "140", "name": "CmpMBnd", "type": "categorical", "num_categories": 2},
        {"id": "141", "serum_id": "270", "name": "CompMB L", "type": "continuous"},
        {"id": "142", "serum_id": "271", "name": "CompMB M", "type": "continuous"},
        {"id": "143", "serum_id": "272", "name": "CompMB H", "type": "continuous"},
        {"id": "144", "serum_id": "269", "name": "Comp_Wet", "type": "continuous"}
    ],
    "fx_reverb": [
        {"id": "145", "serum_id": "160", "name": "Rev Enable", "type": "boolean"},
        {"id": "146", "serum_id": "81", "name": "Verb Wet", "type": "continuous"},
        {"id": "147", "serum_id": "82", "name": "VerbSize", "type": "continuous"},
        {"id": "148", "serum_id": "83", "name": "Decay", "type": "continuous"},
        {"id": "149", "serum_id": "84", "name": "VerbLoCt", "type": "continuous"},
        {"id": "150", "serum_id": "85", "name": "Spin Rate", "type": "continuous"},
        {"id": "151", "serum_id": "86", "name": "VerbHiCt", "type": "continuous"},
        {"id": "152", "serum_id": "87", "name": "Spin Depth", "type": "continuous"}
    ],
    "fx_eq": [
        {"id": "153", "serum_id": "161", "name": "EQ Enable", "type": "boolean"},
        {"id": "154", "serum_id": "88", "name": "EQ FrqL", "type": "continuous"},
        {"id": "155", "serum_id": "89", "name": "EQ FrqH", "type": "continuous"},
        {"id": "156", "serum_id": "90", "name": "EQ Q L", "type": "continuous"},
        {"id": "157", "serum_id": "91", "name": "EQ Q H", "type": "continuous"},
        {"id": "158", "serum_id": "92", "name": "EQ Vol L", "type": "continuous"},
        {"id": "159", "serum_id": "93", "name": "EQ Vol H", "type": "continuous"},
        {"id": "160", "serum_id": "94", "name": "EQ TypL", "type": "categorical", "num_categories": 3},
        {"id": "161", "serum_id": "95", "name": "EQ TypH", "type": "categorical", "num_categories": 3}
    ],
    "fx_filter": [
        {"id": "162", "serum_id": "162", "name": "FX Fil Enable", "type": "boolean"},
        {"id": "163", "serum_id": "141", "name": "FX Fil Wet", "type": "continuous"},
        {"id": "164", "serum_id": "142", "name": "FX Fil Type", "type": "categorical", "num_categories": 89},
        {"id": "165", "serum_id": "143", "name": "FX Fil Freq", "type": "continuous"},
        {"id": "166", "serum_id": "144", "name": "FX Fil Reso", "type": "continuous"},
        {"id": "167", "serum_id": "145", "name": "FX Fil Drive", "type": "continuous"},
        {"id": "168", "serum_id": "146", "name": "FX Fil Var", "type": "continuous"},
        {"id": "169", "serum_id": "268", "name": "FX Fil Pan", "type": "continuous"}
    ],
    "mod_matrix": [
        {"id": str(i), "serum_id": str(180 + (i-170)*2), "name": f"Mod {i-169} amt", "type": "continuous"}
        for i in range(170, 202)
    ]
}

# --- Index Lists for Type ---
continuous_param_indices = []
boolean_param_indices = []
categorical_param_indices = []
categorical_num_classes = {}

# Iterate over each group to populate indices
for group_name, params in SERUM_PARAMETERS.items():
    for pinfo in params:
        idx = int(pinfo["id"])
        ptype = pinfo["type"]

        if ptype == "continuous":
            continuous_param_indices.append(idx)
        elif ptype == "boolean":
            boolean_param_indices.append(idx)
        elif ptype == "categorical":
            categorical_param_indices.append(idx)
            categorical_num_classes[idx] = int(pinfo["num_categories"])
        else:
            raise ValueError(f"Unknown parameter type for index {idx}: {ptype}")

# Sorting indices to maintain sequential order in the lists
continuous_param_indices.sort()
boolean_param_indices.sort()
categorical_param_indices.sort()

print("continuous params:", len(continuous_param_indices))
print("boolean params:", len(boolean_param_indices))
print("categorical params:", len(categorical_param_indices))
print("categorical_num_classes:", len(categorical_num_classes))

# --- Group Masking Map ---
def create_group_mask_metadata(SERUM_PARAMETERS):
    group_map = {}
    for group_name, params in SERUM_PARAMETERS.items():
        enable_id = None
        dependent_ids = []
        for p in params:
            param_id = int(p["id"])
            dependent_ids.append(param_id)
            if p["name"].endswith(" On") or p["name"].endswith(" Enable"):
                enable_id = param_id
        if enable_id is not None:
            group_map[enable_id] = dependent_ids
    return group_map

GROUP_MASKING_MAP = create_group_mask_metadata(SERUM_PARAMETERS)

print("\nGroup Masking Map (Enable ID: [Dependent IDs]):")
print(GROUP_MASKING_MAP)

# --- Split Continuous Indices into Unipolar (0-1) and Bipolar (-1 to 1) ---
# Mod Matrix is IDs 170 to 201 (inclusive), range stops at 202
mod_matrix_ids = set(range(170, 202))

unipolar_indices = [i for i in continuous_param_indices if i not in mod_matrix_ids]
bipolar_indices = [i for i in continuous_param_indices if i in mod_matrix_ids]

# Sort them to be safe
unipolar_indices.sort()
bipolar_indices.sort()

print(f"Unipolar params: {len(unipolar_indices)}")
print(f"Bipolar params: {len(bipolar_indices)} (Should be 32)")

"""# Training

## Split Data
"""

# Cell 3.1

from sklearn.model_selection import train_test_split

# 1. Encode Text
# This now encodes only the valid descriptions
description_embeddings = clap_encode_text(serum_preset_descriptions)
print("Text Embeddings:", description_embeddings.shape)

# 2. Split ALL arrays consistently
# We pack inputs into variables to ensure they are split using the same indices
X_train_text, X_val_text, \
X_train_params, X_val_params, \
X_train_audio, X_val_audio, \
X_train_mask, X_val_mask = train_test_split(
    description_embeddings,
    serum_params,
    osc_embeddings_flat,
    osc_masks,
    test_size=0.2,
    random_state=42,
)

# Cast everything to float32 for T4 efficiency
X_train_text = X_train_text.astype('float32')
X_val_text   = X_val_text.astype('float32')

X_train_params = X_train_params.astype('float32')
X_val_params   = X_val_params.astype('float32')

X_train_audio = X_train_audio.astype('float32')
X_val_audio   = X_val_audio.astype('float32')

X_train_mask = X_train_mask.astype('float32')
X_val_mask   = X_val_mask.astype('float32')

print("-" * 30)
print(f"Train Text:   {X_train_text.shape}")
print(f"Train Params: {X_train_params.shape}")
print(f"Train Audio:  {X_train_audio.shape}")
print(f"Train Mask:   {X_train_mask.shape}")
print("-" * 30)

"""## Define Model Architecture"""

# Cell 3.2

import tensorflow as tf
import numpy as np
from tensorflow.keras import backend as K
from tensorflow.keras.layers import Layer, Input, Dense, Concatenate, Dropout, BatchNormalization, LayerNormalization, LeakyReLU, Activation, Add, Multiply, Reshape
from tensorflow.keras.models import Model
from tensorflow.keras.utils import register_keras_serializable
from keras.saving import serialize_keras_object, deserialize_keras_object

# --- 0. HYPERPARAMETER CONSTANTS ---
W_CONT      = 10.0
W_BOOL      = 5.0
W_CAT       = 15.0
W_MOD_GATE  = 5.0
W_AUDIO     = 1.0

# ==============================================================================
# 1. SHARED LAYERS
# ==============================================================================

@register_keras_serializable(package="custom", name="FiLMLayer")
class FiLMLayer(Layer):
    def call(self, inputs):
        x, gamma, beta = inputs
        return x * gamma + beta

@register_keras_serializable(package="custom", name="StopGradient")
class StopGradient(Layer):
    def call(self, inputs):
        return tf.stop_gradient(inputs)

def sigmoid_focal_crossentropy(y_true, y_pred, alpha=0.25, gamma=2.0, from_logits=True):
    if from_logits: y_pred = tf.sigmoid(y_pred)
    bce = K.binary_crossentropy(y_true, y_pred)
    p_t = (y_true * y_pred) + ((1 - y_true) * (1 - y_pred))
    return alpha * K.pow(1.0 - p_t, gamma) * bce

class BetaAnnealing(tf.keras.callbacks.Callback):
    def __init__(self, max_beta=1.0, warmup_epochs=20, mode="linear"):
        super().__init__()
        self.max_beta = max_beta; self.warmup_epochs = warmup_epochs; self.mode = mode
    def on_epoch_begin(self, epoch, logs=None):
        beta = self.max_beta * min(1.0, (epoch + 1) / float(self.warmup_epochs))
        if hasattr(self.model, "beta"): self.model.beta = float(beta)

# ==============================================================================
# 2. VAE MODEL (Stage 1: Compression)
# ==============================================================================

@register_keras_serializable(package="custom", name="VAE_Text_to_Synth_Audio")
class VAE_Text_to_Synth_Audio(tf.keras.Model):
    def __init__(self, encoder, decoder, unipolar_indices, bipolar_indices,
                 bool_indices, cat_indices, categorical_num_classes, group_masking_map,
                 latent_dim_params, latent_dim_audio, latent_dim_total,
                 beta=1.0, latent_dropout_rate=0.0, **kwargs):
        super().__init__(**kwargs)
        self.encoder = encoder
        self.decoder = decoder
        self.unipolar_indices = [int(i) for i in unipolar_indices]
        self.bipolar_indices = [int(i) for i in bipolar_indices]
        self.bool_indices = [int(i) for i in bool_indices]
        self.cat_indices = [int(i) for i in cat_indices]
        self.categorical_num_classes = {int(k): int(v) for k, v in categorical_num_classes.items()}
        self.group_masking_map = {int(k): [int(x) for x in v] for k, v in (group_masking_map or {}).items()}
        self.param_to_enable = {int(pid): int(eid) for eid, mids in self.group_masking_map.items() for pid in mids if int(pid) != int(eid)}

        self.latent_dim_params = int(latent_dim_params)
        self.latent_dim_audio = int(latent_dim_audio)
        self.latent_dim_total = int(latent_dim_total)

        self.beta = float(beta)
        self.latent_dropout_rate = float(latent_dropout_rate)

        self.total_loss_tracker = tf.keras.metrics.Mean(name="total_loss")
        self.reconstruction_loss_tracker = tf.keras.metrics.Mean(name="reconstruction_loss")
        self.kl_loss_tracker = tf.keras.metrics.Mean(name="kl_loss")
        self.audio_loss_tracker = tf.keras.metrics.Mean(name="audio_loss")

    def call(self, inputs, training=False):
        text_embeddings, params_in, audio_in = inputs
        zp_mu, zp_log, za_mu, za_log = self.encoder([text_embeddings, params_in, audio_in])
        zp = zp_mu + tf.exp(0.5 * zp_log) * tf.random.normal(shape=tf.shape(zp_mu))
        za = za_mu + tf.exp(0.5 * za_log) * tf.random.normal(shape=tf.shape(za_mu))
        z_combined = tf.concat([zp, za], axis=-1)
        return self.decoder([z_combined, text_embeddings], training=training)

    def _group_mask_matrix(self, head_indices, y_true):
        batch_size = tf.shape(y_true)[0]
        mask_cols = []
        for pid in head_indices:
            enable_id = self.param_to_enable.get(int(pid), None)
            if enable_id is None: mask_cols.append(tf.ones((batch_size, 1), dtype=tf.float32))
            else:
                enable_val = tf.gather(y_true, indices=[enable_id], axis=1)
                mask_cols.append(tf.cast(enable_val > 0.5, tf.float32))
        return tf.concat(mask_cols, axis=1) if len(mask_cols) > 1 else mask_cols[0]

    def calculate_loss(self, y_true_params, y_true_audio, y_true_mask, y_pred_list,
                       zp_mu, zp_log, za_mu, za_log):
        eps = 1e-7
        head_idx = 0
        uni_loss, mod_loss, bool_loss, cat_loss, audio_loss = 0.0, 0.0, 0.0, 0.0, 0.0

        if self.unipolar_indices:
            y_true_uni = tf.gather(y_true_params, self.unipolar_indices, axis=1)
            mask = self._group_mask_matrix(self.unipolar_indices, y_true_params)
            mse = tf.square(y_true_uni - y_pred_list[head_idx]) * mask
            uni_loss = (tf.reduce_sum(mse) / (tf.reduce_sum(mask) + eps)) * W_CONT
            head_idx += 1

        if self.bipolar_indices:
            y_true_bi_raw = tf.gather(y_true_params, self.bipolar_indices, axis=1)
            pred_gate, pred_val = y_pred_list[head_idx], y_pred_list[head_idx+1]
            head_idx += 2
            # REPLACED LAMBDA with tf.where for robustness
            is_normalized = tf.logical_and(tf.reduce_min(y_true_bi_raw) >= 0, tf.reduce_max(y_true_bi_raw) <= 1.0001)
            y_true_bi = tf.where(is_normalized, y_true_bi_raw * 2 - 1, y_true_bi_raw)
            true_gate = tf.cast(tf.abs(y_true_bi) > 0.01, tf.float32)
            gate_loss = tf.reduce_mean(tf.reduce_sum(sigmoid_focal_crossentropy(true_gate, pred_gate), axis=-1))
            val_loss = tf.reduce_mean(tf.reduce_sum(tf.square(y_true_bi - pred_val) * true_gate, axis=-1) / (tf.reduce_sum(true_gate, axis=-1)+eps))
            mod_loss = gate_loss * W_MOD_GATE + val_loss * W_CONT

        if self.bool_indices:
            y_true_bool = tf.gather(y_true_params, self.bool_indices, axis=1)
            mask = self._group_mask_matrix(self.bool_indices, y_true_params)
            b_loss = K.binary_crossentropy(y_true_bool, tf.clip_by_value(y_pred_list[head_idx], eps, 1-eps)) * mask
            bool_loss = (tf.reduce_sum(b_loss) / (tf.reduce_sum(mask) + eps)) * W_BOOL
            head_idx += 1

        for j in sorted(self.cat_indices):
            y_true_cat = tf.squeeze(tf.gather(y_true_params, [j], axis=1), -1)
            mask = tf.squeeze(self._group_mask_matrix([j], y_true_params), -1)
            C = self.categorical_num_classes[int(j)]
            labels = tf.cast(tf.where(y_true_cat <= 1.0001, tf.round(y_true_cat*(C-1)), tf.round(y_true_cat)), tf.int32)
            labels = tf.clip_by_value(labels, 0, C-1)
            c_loss = tf.keras.losses.sparse_categorical_crossentropy(labels, y_pred_list[head_idx])
            cat_loss += tf.reduce_mean(c_loss * mask) * W_CAT
            head_idx += 1

        true_audio_3d = tf.reshape(y_true_audio, [-1, 3, 512])
        loss_a = tf.reduce_sum(tf.square(true_audio_3d[:,0,:] - y_pred_list[head_idx]) * tf.expand_dims(y_true_mask[:,0], -1)) / (tf.reduce_sum(y_true_mask[:,0]) * 512 + eps)
        loss_b = tf.reduce_sum(tf.square(true_audio_3d[:,1,:] - y_pred_list[head_idx+1]) * tf.expand_dims(y_true_mask[:,1], -1)) / (tf.reduce_sum(y_true_mask[:,1]) * 512 + eps)
        loss_n = tf.reduce_sum(tf.square(true_audio_3d[:,2,:] - y_pred_list[head_idx+2]) * tf.expand_dims(y_true_mask[:,2], -1)) / (tf.reduce_sum(y_true_mask[:,2]) * 512 + eps)
        audio_loss = (loss_a + loss_b + loss_n) * W_AUDIO

        recon_loss = uni_loss + mod_loss + bool_loss + cat_loss + audio_loss
        kl_p = -0.5 * tf.reduce_mean(tf.reduce_sum(1 + zp_log - tf.square(zp_mu) - tf.exp(zp_log), axis=1))
        kl_a = -0.5 * tf.reduce_mean(tf.reduce_sum(1 + za_log - tf.square(za_mu) - tf.exp(za_log), axis=1))
        total_loss = recon_loss + (self.beta * (kl_p + kl_a))

        return total_loss, recon_loss, (kl_p + kl_a), audio_loss

    def train_step(self, data):
        inputs = data[0]
        text, params, audio, mask = inputs[0], inputs[1], inputs[2], inputs[3]
        with tf.GradientTape() as tape:
            zp_mu, zp_log, za_mu, za_log = self.encoder([text, params, audio])
            zp = zp_mu + tf.exp(0.5 * zp_log) * tf.random.normal(shape=tf.shape(zp_mu))
            za = za_mu + tf.exp(0.5 * za_log) * tf.random.normal(shape=tf.shape(za_mu))
            z_combined = tf.concat([zp, za], axis=-1)
            dropout_mask = tf.cast(tf.random.uniform((tf.shape(z_combined)[0], 1)) >= self.latent_dropout_rate, tf.float32)
            y_pred = self.decoder([z_combined * dropout_mask, text], training=True)
            total, recon, kl, aud = self.calculate_loss(params, audio, mask, y_pred, zp_mu, zp_log, za_mu, za_log)
        grads = tape.gradient(total, self.trainable_variables)
        self.optimizer.apply_gradients(zip(grads, self.trainable_variables))
        self.total_loss_tracker.update_state(total); self.reconstruction_loss_tracker.update_state(recon)
        self.kl_loss_tracker.update_state(kl); self.audio_loss_tracker.update_state(aud)
        return {"loss": self.total_loss_tracker.result(), "recon": recon, "kl": kl, "audio": aud}

    def test_step(self, data):
        inputs = data[0]
        text, params, audio, mask = inputs[0], inputs[1], inputs[2], inputs[3]
        zp_mu, zp_log, za_mu, za_log = self.encoder([text, params, audio])
        zp = zp_mu + tf.exp(0.5 * zp_log) * tf.random.normal(shape=tf.shape(zp_mu))
        za = za_mu + tf.exp(0.5 * za_log) * tf.random.normal(shape=tf.shape(za_mu))
        y_pred = self.decoder([tf.concat([zp, za], axis=-1), text], training=False)
        total, recon, kl, aud = self.calculate_loss(params, audio, mask, y_pred, zp_mu, zp_log, za_mu, za_log)
        self.total_loss_tracker.update_state(total); self.reconstruction_loss_tracker.update_state(recon)
        self.kl_loss_tracker.update_state(kl); self.audio_loss_tracker.update_state(aud)
        return {"loss": self.total_loss_tracker.result(), "recon": recon, "kl": kl, "audio": aud}

    def get_config(self):
        config = super().get_config()
        config.update({
            "encoder": serialize_keras_object(self.encoder), "decoder": serialize_keras_object(self.decoder),
            "unipolar_indices": self.unipolar_indices, "bipolar_indices": self.bipolar_indices,
            "bool_indices": self.bool_indices, "cat_indices": self.cat_indices,
            "categorical_num_classes": self.categorical_num_classes, "group_masking_map": self.group_masking_map,
            "latent_dim_params": self.latent_dim_params, "latent_dim_audio": self.latent_dim_audio,
            "latent_dim_total": self.latent_dim_total, "beta": self.beta, "latent_dropout_rate": self.latent_dropout_rate
        })
        return config

    @classmethod
    def from_config(cls, config):
        encoder = deserialize_keras_object(config.pop("encoder"))
        decoder = deserialize_keras_object(config.pop("decoder"))
        return cls(encoder, decoder, **config)

"""## Define Model Builders"""

# Cell 3.3 — Model Builders

@register_keras_serializable(package="custom", name="SplitLatentLayer")
class SplitLatentLayer(Layer):
    """
    A Custom Layer to split a concatenated latent vector into two parts.
    Replaces Lambda(lambda x: x[:, :split]) for better serialization.
    """
    def __init__(self, split_index, part="first", **kwargs):
        super().__init__(**kwargs)
        self.split_index = split_index
        self.part = part

    def call(self, inputs):
        if self.part == "first":
            return inputs[:, :self.split_index]
        return inputs[:, self.split_index:]

    def get_config(self):
        config = super().get_config()
        config.update({"split_index": self.split_index, "part": self.part})
        return config

def build_encoder(embedding_dim, num_params, audio_dim, latent_dim_params, latent_dim_audio, enc_width, dropout_rate=0.0):
    text_in = Input(shape=(embedding_dim,), name="encoder_text_input")
    params_in = Input(shape=(num_params,), name="encoder_params_input")
    audio_in = Input(shape=(audio_dim,), name="encoder_audio_input")

    x = Concatenate(name="encoder_concat")([text_in, params_in, audio_in])
    x = Dense(enc_width, activation="linear")(x)
    x = LayerNormalization()(x)
    x = Activation("relu")(x)
    x = Dense(enc_width, activation="linear")(x)
    x = LayerNormalization()(x)
    x = Activation("relu")(x)

    # HEAD 1: PARAMETERS
    x_p = Dense(enc_width // 2, activation="relu", name="pre_latent_params")(x)
    zp_mu = Dense(latent_dim_params, name="zp_mean")(x_p)
    zp_log = Dense(latent_dim_params, name="zp_log_var")(x_p)

    # HEAD 2: AUDIO
    x_a = Dense(enc_width // 2, activation="relu", name="pre_latent_audio")(x)
    za_mu = Dense(latent_dim_audio, name="za_mean")(x_a)
    za_log = Dense(latent_dim_audio, name="za_log_var")(x_a)

    return Model([text_in, params_in, audio_in], [zp_mu, zp_log, za_mu, za_log], name="encoder")

def build_decoder_film(embedding_dim, latent_dim_total, latent_dim_params, dec_width,
                       unipolar_indices, bipolar_indices, bool_indices, cat_indices, categorical_num_classes, dropout_rate=0.0):
    z_in = Input(shape=(latent_dim_total,), name="latent_input")
    text_in = Input(shape=(embedding_dim,), name="decoder_text_input")

    # REPLACED LAMBDA with Custom SplitLatentLayer
    z_p = SplitLatentLayer(split_index=latent_dim_params, part="first", name="slice_params")(z_in)
    z_a = SplitLatentLayer(split_index=latent_dim_params, part="second", name="slice_audio")(z_in)

    def film_block(x, text_in, width, block_id):
        x = LayerNormalization(name=f"dec_ln_pre_{block_id}")(x)
        gamma = Dense(width, kernel_initializer="zeros", bias_initializer="ones")(text_in)
        beta = Dense(width, kernel_initializer="zeros", bias_initializer="zeros")(text_in)
        x = FiLMLayer(name=f"film_{block_id}")([x, gamma, beta])
        x = LeakyReLU(negative_slope=0.2)(x)
        return x

    # PATH A: PARAMETERS (Uses z_p)
    x = Dense(dec_width)(z_p)
    x = film_block(x, text_in, dec_width, "params_1")
    x = Dense(dec_width)(x)
    x = film_block(x, text_in, dec_width, "params_2")
    x = LayerNormalization()(x)
    x = Activation("relu")(x)

    outs = []
    if unipolar_indices: outs.append(Dense(len(unipolar_indices), activation="sigmoid", name="unipolar_outputs")(x))
    if bipolar_indices:
        outs.append(Dense(len(bipolar_indices), activation="linear", name="bipolar_gate")(x))
        outs.append(Dense(len(bipolar_indices), activation="tanh", name="bipolar_value")(x))
    if bool_indices: outs.append(Dense(len(bool_indices), activation="sigmoid", name="boolean_outputs")(x))
    for j in sorted(cat_indices): outs.append(Dense(categorical_num_classes[int(j)], activation="softmax", name=f"cat_{j}")(x))

    # PATH B: AUDIO (Uses z_a)
    x_aud = Dense(dec_width)(z_a)
    x_aud = film_block(x_aud, text_in, dec_width, "audio_1")
    x_aud = Dense(dec_width)(x_aud)
    x_aud = film_block(x_aud, text_in, dec_width, "audio_2")
    x_aud = LayerNormalization()(x_aud)
    x_aud = Activation("relu")(x_aud)

    outs.append(Dense(512, activation="linear", name="osc_a_embed")(x_aud))
    outs.append(Dense(512, activation="linear", name="osc_b_embed")(x_aud))
    outs.append(Dense(512, activation="linear", name="osc_n_embed")(x_aud))

    return Model([z_in, text_in], outs, name="decoder_film")

def build_resmlp_denoiser(latent_dim, text_embed_dim=512, hidden_dim=512, num_layers=8):
    z_noisy = Input(shape=(latent_dim,), name="z_noisy")
    t_in = Input(shape=(1,), name="time_input")
    text_emb = Input(shape=(text_embed_dim,), name="text_embedding")
    t_emb = SinusoidalTimeEmbedding(dim=hidden_dim)(t_in)
    t_emb = Dense(hidden_dim, activation="swish")(t_emb)
    x = Dense(hidden_dim)(z_noisy)
    cond_concat = Concatenate()([t_emb, text_emb])
    cond_mapped = Dense(hidden_dim, activation="swish")(cond_concat)
    cond_mapped = Dense(hidden_dim, activation="swish")(cond_mapped)
    for i in range(num_layers): x = ResidualBlock(width=hidden_dim, name=f"res_block_{i}")(x, cond_mapped)
    x = LayerNormalization()(x)
    noise_pred = Dense(latent_dim, activation="linear", name="noise_pred")(x)
    return Model(inputs=[z_noisy, t_in, text_emb], outputs=noise_pred, name="resmlp_denoiser")

"""## Compile and Train"""

# Cell 3.4 — VAE Hyperparameter Grid Search (The "Battle")

import tensorflow as tf
from tensorflow.keras.optimizers import Adam
import pandas as pd
import os
import time

# --- 1. SETUP DATA SHAPES ---
actual_num_params = X_train_params.shape[1]
audio_dim = X_train_audio.shape[1]

# Filter indices safely (as before)
def filter_indices(indices, limit):
    return [i for i in indices if i < limit]

safe_unipolar = filter_indices(unipolar_indices, actual_num_params)
safe_bipolar = filter_indices(bipolar_indices, actual_num_params)
safe_bool = filter_indices(boolean_param_indices, actual_num_params)
safe_cat = filter_indices(categorical_param_indices, actual_num_params)
safe_classes = {k: v for k, v in categorical_num_classes.items() if k < actual_num_params}

# --- 2. DEFINE THE GRID SEARCH ---
# HYPOTHESIS:
# Params need 128 dims to look good (based on previous run).
# Audio needs its OWN space so it doesn't crush params.

SEARCH_GRID = [
    {"latent_p": 128, "latent_a": 128, "w_audio": 1.0}, # Balanced Split
    # {"latent_p": 128, "latent_a": 64, "w_audio": 1.0},  # Compress Audio more
]

results = []
best_loss = float('inf')
best_config = None

print(f"⚔️ STARTING HYPERPARAMETER BATTLE: {len(SEARCH_GRID)} Candidates\n")

for i, config in enumerate(SEARCH_GRID):
    l_p = config["latent_p"]
    l_a = config["latent_a"]
    w_aud = config["w_audio"]
    l_total = l_p + l_a

    print(f"--- Round {i+1}: Latent Params={l_p}, Latent Audio={l_a} (Total {l_total}) ---")

    # 1. Update Global Hyperparameter
    global W_AUDIO
    W_AUDIO = w_aud

    # 2. Build Fresh Model
    tf.keras.backend.clear_session()

    # Pass SPLIT dimensions to Encoder
    enc = build_encoder(X_train_text.shape[1], actual_num_params, audio_dim,
                        latent_dim_params=l_p, latent_dim_audio=l_a,
                        enc_width=512) # Wider encoder to handle branching

    # Pass SPLIT dimensions to Decoder
    dec = build_decoder_film(X_train_text.shape[1],
                             latent_dim_total=l_total,
                             latent_dim_params=l_p,
                             dec_width=512,
                             unipolar_indices=safe_unipolar, bipolar_indices=safe_bipolar,
                             bool_indices=safe_bool, cat_indices=safe_cat,
                             categorical_num_classes=safe_classes)

    vae = VAE_Text_to_Synth_Audio(
        encoder=enc, decoder=dec,
        unipolar_indices=safe_unipolar, bipolar_indices=safe_bipolar,
        bool_indices=safe_bool, cat_indices=safe_cat,
        categorical_num_classes=safe_classes, group_masking_map=GROUP_MASKING_MAP,
        latent_dim_params=l_p, latent_dim_audio=l_a, latent_dim_total=l_total,
        beta=1.0, latent_dropout_rate=0.0
    )

    vae.compile(optimizer=Adam(learning_rate=1e-3))

    # 3. Fast Training Sprint (5 Epochs only)
    hist = vae.fit(
        x=[X_train_text, X_train_params, X_train_audio, X_train_mask],
        epochs=5,
        batch_size=64,
        validation_data=([X_val_text, X_val_params, X_val_audio, X_val_mask], None),
        verbose=0 # Silent training
    )

    # 4. Capture Metrics from last epoch
    final_val_loss = hist.history['val_loss'][-1]
    final_recon = hist.history['val_recon'][-1]
    final_audio_loss = hist.history['val_audio'][-1]

    print(f"   Result -> Total Val Loss: {final_val_loss:.4f} | Recon (Knobs): {final_recon:.4f} | Audio: {final_audio_loss:.4f}")

    results.append({
        "latent_p": l_p, "latent_a": l_a,
        "w_audio": w_aud,
        "val_loss": final_val_loss,
        "val_recon": final_recon,
        "val_audio": final_audio_loss
    })

    if final_val_loss < best_loss:
        best_loss = final_val_loss
        best_config = config

# --- 3. RESULTS SUMMARY ---
print("\n🏆 BATTLE RESULTS 🏆")
df_res = pd.DataFrame(results).sort_values("val_loss")
print(df_res)

# --- 4. RETRAIN WINNER (Full Training) ---
print(f"\n🚀 Retraining WINNER for full 40 epochs...")

W_AUDIO = best_config["w_audio"]
l_p = best_config["latent_p"]
l_a = best_config["latent_a"]
l_total = l_p + l_a

tf.keras.backend.clear_session()

enc = build_encoder(X_train_text.shape[1], actual_num_params, audio_dim, l_p, l_a, 512)
dec = build_decoder_film(X_train_text.shape[1], l_total, l_p, 512,
                         safe_unipolar, safe_bipolar, safe_bool,
                         safe_cat, safe_classes)

vae = VAE_Text_to_Synth_Audio(
    encoder=enc, decoder=dec,
    unipolar_indices=safe_unipolar, bipolar_indices=safe_bipolar,
    bool_indices=safe_bool, cat_indices=safe_cat,
    categorical_num_classes=safe_classes, group_masking_map=GROUP_MASKING_MAP,
    latent_dim_params=l_p, latent_dim_audio=l_a, latent_dim_total=l_total,
    beta=1.0, latent_dropout_rate=0.0
)

vae.compile(optimizer=Adam(learning_rate=1e-3))

callbacks_vae = [
    tf.keras.callbacks.EarlyStopping(monitor="val_loss", patience=5, restore_best_weights=True),
    BetaAnnealing(max_beta=1.0, warmup_epochs=10)
]

vae.fit(
    x=[X_train_text, X_train_params, X_train_audio, X_train_mask],
    epochs=40,
    batch_size=64,
    validation_data=([X_val_text, X_val_params, X_val_audio, X_val_mask], None),
    callbacks=callbacks_vae,
    verbose=1
)

vae.save(os.path.join(SAVE_DIR, "vae_stage1_tuned.keras"))

# --- 5. TRAIN DIFFUSION (Using Tuned VAE) ---
print("\n=== STAGE 2: Training Diffusion (Generation) ===")
vae.trainable = False

# Note: Diffusion now learns on LATENT_TOTAL dims (e.g. 256)
denoiser = build_resmlp_denoiser(latent_dim=l_total, text_embed_dim=X_train_text.shape[1])
ldm = LatentDiffusionModel(vae_encoder=vae.encoder, vae_decoder=vae.decoder, denoiser=denoiser, timesteps=1000)

ldm.compile(optimizer=Adam(learning_rate=1e-4))

ldm.fit(
    x=[X_train_text, X_train_params, X_train_audio, X_train_mask],
    epochs=60,
    batch_size=64,
    validation_data=([X_val_text, X_val_params, X_val_audio, X_val_mask], None),
    verbose=1
)

ldm.save(os.path.join(SAVE_DIR, "ldm_final_tuned.keras"))
best_model = ldm

"""## Evaluate and Save Model"""

# Cell 3.5 — Evaluate Diffusion Model

# 1. Create Dataset using the NEW variable names from Cell 3.1
# Input structure: (Text, Params, Audio, Mask)
val_dataset = tf.data.Dataset.from_tensor_slices((
    (X_val_text, X_val_params, X_val_audio, X_val_mask),
    X_val_params # Dummy target (unused in test step)
)).batch(16)

total_mse_agg = tf.keras.metrics.Mean()

print("Evaluating Diffusion Model on Validation Set...")

# 2. Unpack the batch (4 items now)
for (text_batch, params_batch, audio_batch, mask_batch), _ in val_dataset:

    # 3. Use the internal VAE encoder
    # ENCODER NOW RETURNS 4 VALUES (Split Architecture)
    zp_mu, zp_log, za_mu, za_log = best_model.vae_encoder([text_batch, params_batch, audio_batch], training=False)

    # 4. Sample Latents independently
    eps_p = tf.random.normal(shape=tf.shape(zp_mu))
    zp = zp_mu + tf.exp(0.5 * zp_log) * eps_p

    eps_a = tf.random.normal(shape=tf.shape(za_mu))
    za = za_mu + tf.exp(0.5 * za_log) * eps_a

    # 5. Concatenate for Diffusion
    # Diffusion learns the joint distribution of [Params | Audio]
    z_0 = tf.concat([zp, za], axis=-1)

    # 6. Diffusion Forward Process (Add Noise)
    batch_size = tf.shape(z_0)[0]
    t = tf.random.uniform(minval=0, maxval=best_model.timesteps, shape=(batch_size,), dtype=tf.int32)
    noise = tf.random.normal(shape=tf.shape(z_0))
    z_t = best_model.scheduler.add_noise(z_0, noise, t)

    # 7. Predict Noise using the Denoiser
    pred_noise = best_model.denoiser([z_t, t, text_batch], training=False)

    # 8. Calculate MSE
    loss = tf.reduce_mean(tf.square(noise - pred_noise))
    total_mse_agg.update_state(loss)

print("-" * 30)
print(f"Validation Diffusion MSE: {total_mse_agg.result():.4f}")
print("-" * 30)

"""# Test requests to model

### Subtask:
Implement code to test the end-to-end process with new text descriptions.

"""

# Cell 4.1 — Diffusion Inference Helpers

import numpy as np
import random
import tensorflow as tf
import json
import os
from tensorflow.keras.models import load_model

# ==============================================================================
# 1. HELPER FUNCTIONS
# ==============================================================================

def _safe_probs(raw_head):
    probs = np.array(raw_head, dtype=np.float32).reshape(-1)
    probs[probs < 0] = 0.0
    s = probs.sum()
    if not np.isfinite(s) or s <= 1e-6:
        probs = np.ones_like(probs, dtype=np.float32) / probs.size
    else:
        probs = probs / s
    return probs

def find_nearest_matches(query_vec, library_embeds, library_names, top_k=3):
    """
    Finds the top_k most similar audio files using Cosine Similarity.
    """
    if library_embeds is None or library_names is None:
        return ["Library Not Loaded"] * top_k

    # 1. Normalize Query
    query_norm = np.linalg.norm(query_vec)
    if query_norm > 1e-6:
        query_vec = query_vec / query_norm

    # 2. Normalize Library
    lib_norms = np.linalg.norm(library_embeds, axis=1, keepdims=True)
    lib_embeds_norm = library_embeds / (lib_norms + 1e-6)

    # 3. Cosine Similarity
    scores = np.dot(lib_embeds_norm, query_vec)

    # 4. Get Top K indices
    top_indices = np.argsort(scores)[-top_k:][::-1]

    # 5. Retrieve Names and Scores
    matches = []
    for idx in top_indices:
        matches.append({
            "name": str(library_names[idx]),
            "score": float(scores[idx])
        })
    return matches

def reconstruct_parameters_from_heads(predicted_outputs, parameter_types, categorical_num_classes, sample_categorical=True, noise_level=0.0):
    """
    Reconstructs parameter vector from split heads AND retrieves audio embeddings + matches.
    Assumes parameter_types is ALREADY CLEAN (ids 0-201).
    """
    n_params = len(parameter_types)
    reconstructed = np.zeros(n_params, dtype=np.float32)

    # We use the clean dictionary directly
    valid_param_types = parameter_types

    continuous_params = [int(i) for i, p in valid_param_types.items() if p["type"] == "continuous"]

    # Recalculate Mod Matrix Range based on cleaned indices (starts at 170)
    mod_matrix_ids = set(range(170, 202))

    unipolar_indices = sorted([i for i in continuous_params if i not in mod_matrix_ids])
    bipolar_indices = sorted([i for i in continuous_params if i in mod_matrix_ids])
    boolean_params = sorted([int(i) for i, p in valid_param_types.items() if p["type"] == "boolean"])
    categorical_params = sorted([int(i) for i, p in valid_param_types.items() if p["type"] == "categorical"])

    head_idx = 0

    # --- 1. RECONSTRUCT KNOBS ---

    # A. Unipolar
    if unipolar_indices:
        uni_head = np.array(predicted_outputs[head_idx], dtype=np.float32).reshape(-1)
        count = min(len(unipolar_indices), len(uni_head))
        for i in range(count):
            param_idx = unipolar_indices[i]
            if param_idx < n_params:
                reconstructed[param_idx] = uni_head[i]
        head_idx += 1

    # B. Bipolar (Gate + Value)
    if bipolar_indices:
        gate_head = np.array(predicted_outputs[head_idx], dtype=np.float32).reshape(-1)
        val_head = np.array(predicted_outputs[head_idx+1], dtype=np.float32).reshape(-1)
        head_idx += 2
        count = min(len(bipolar_indices), len(gate_head))
        for i in range(count):
            param_idx = bipolar_indices[i]
            if param_idx < n_params:
                gate = 1.0 / (1.0 + np.exp(-gate_head[i]))
                val = (val_head[i] + 1.0) / 2.0
                reconstructed[param_idx] = val if gate >= 0.25 else 0.5

    # C. Boolean
    if boolean_params:
        bool_head = np.array(predicted_outputs[head_idx], dtype=np.float32).reshape(-1)
        count = min(len(boolean_params), len(bool_head))
        for i in range(count):
            param_idx = boolean_params[i]
            if param_idx < n_params:
                reconstructed[param_idx] = 1.0 if bool_head[i] > 0.5 else 0.0
        head_idx += 1

    # D. Categorical
    max_param_heads = len(predicted_outputs) - 3
    for param_idx in categorical_params:
        if head_idx >= max_param_heads: break

        head = predicted_outputs[head_idx]
        if isinstance(head, (list, tuple)): head = head[0]
        probs = _safe_probs(head)
        num_c = categorical_num_classes.get(param_idx, len(probs))

        if sample_categorical: choice = np.random.choice(len(probs), p=probs)
        else: choice = np.argmax(probs)

        if param_idx < n_params:
            reconstructed[param_idx] = float(choice) / max(1, (num_c - 1))
        head_idx += 1

    # --- 2. RETRIEVE AUDIO EMBEDDINGS ---
    def extract_embed(h):
        return np.array(h, dtype=np.float32).reshape(512)

    try:
        osc_a_vec = extract_embed(predicted_outputs[-3])
        osc_b_vec = extract_embed(predicted_outputs[-2])
        osc_n_vec = extract_embed(predicted_outputs[-1])

        a_matches = find_nearest_matches(osc_a_vec, WT_LIB_EMBEDS, WT_LIB_NAMES)
        b_matches = find_nearest_matches(osc_b_vec, WT_LIB_EMBEDS, WT_LIB_NAMES)
        n_matches = find_nearest_matches(osc_n_vec, NOISE_LIB_EMBEDS, NOISE_LIB_NAMES)

        audio_dict = {
            "vectors": { "osc_a": osc_a_vec, "osc_b": osc_b_vec, "noise": osc_n_vec },
            "matches": { "osc_a": a_matches, "osc_b": b_matches, "noise": n_matches }
        }
    except IndexError:
        print("Warning: Audio heads not found in output.")
        audio_dict = None

    return reconstructed, audio_dict

def generate_synth_parameters_vae(text_description, model, parameter_types, categorical_num_classes, sample_categorical=True, noise_level=0.0, seed=None):
    if seed is not None:
        import torch
        np.random.seed(seed)
        random.seed(seed)
        tf.random.set_seed(seed)
        torch.manual_seed(seed)

    emb = clap_encode_text([text_description])
    print(f"Diffusion Sampling for: '{text_description}'...")
    preds = model.generate(emb, steps=1000)
    return reconstruct_parameters_from_heads(preds, parameter_types, categorical_num_classes, sample_categorical=sample_categorical, noise_level=noise_level)

def numpy_to_json(parameter_array, serum_parameters):
    output_json = {}
    flat_lookup = {}
    for group, params in serum_parameters.items():
        for p in params:
            flat_lookup[int(p["id"])] = p

    for idx, val in enumerate(parameter_array):
        if idx in flat_lookup:
            param_def = flat_lookup[idx]
            entry = param_def.copy()
            entry["value"] = float(val)
            output_json[str(idx)] = entry
    return output_json

# ==============================================================================
# 2. LOAD MODEL
# ==============================================================================

if 'best_model' not in globals():
    print("Variable 'best_model' not found. Attempting to load LDM...")
    saved_model_path = os.path.join(SAVE_DIR, "ldm_final_audio.keras")

    if os.path.exists(saved_model_path):
        custom_objects = {
            "VAE_Text_to_Synth_Audio": VAE_Text_to_Synth_Audio,
            "LatentDiffusionModel": LatentDiffusionModel,
            "SinusoidalTimeEmbedding": SinusoidalTimeEmbedding,
            "ResidualBlock": ResidualBlock,
            "FiLM_Modulate": FiLM_Modulate,
            "FiLMLayer": FiLMLayer
        }
        best_model = load_model(saved_model_path, custom_objects=custom_objects)
        print(f"✅ Loaded: {saved_model_path}")
    else:
        print("❌ Model not found. Run Cell 3.4 to train.")

# --- Run Test ---
test_prompt = "A deep, wobbling reese bass with slow filter movement"
param_map = {int(p['id']): p for g in SERUM_PARAMETERS.values() for p in g}

if 'best_model' in globals():
    generated_params, generated_audio = generate_synth_parameters_vae(
        text_description=test_prompt,
        model=best_model,
        parameter_types=param_map,
        categorical_num_classes=categorical_num_classes,
        sample_categorical=True,
        seed=42
    )

    preset_json = numpy_to_json(generated_params, SERUM_PARAMETERS)

    print("\n--- Generated Parameter Snippet ---")
    print(json.dumps({k: preset_json[k] for k in list(preset_json.keys())[:3]}, indent=2))

    if generated_audio and "matches" in generated_audio:
        matches = generated_audio["matches"]
        print("\n[Oscillator A Matches]:")
        for m in matches["osc_a"]: print(f"  - {m['name']} ({m['score']:.3f})")

# Cell 4.2

# --- Run a Test Prediction ---
test_prompt = "A deep, wobbling reese bass with slow filter movement"
print(f"Generating preset for: '{test_prompt}'...")

# Use globals to reconstruct types map if needed
param_map = {int(p['id']): p for g in SERUM_PARAMETERS.values() for p in g}

# !!! FIX: Unpack the two return values (Params, Audio)
generated_params, generated_audio = generate_synth_parameters_vae(
    text_description=test_prompt,
    model=best_model,
    parameter_types=param_map,
    categorical_num_classes=categorical_num_classes,
    sample_categorical=True,
    noise_level=0.0,
    seed=None
)

# Now generated_params is just the array, so this works:
preset_json = numpy_to_json(generated_params, SERUM_PARAMETERS)

print("\n--- Sample Results (Gated Mod Matrix) ---")
# Check a Mod Matrix value (ID 173 is Mod 1 Amt)
mod_val = preset_json["173"]["value"]
print(f"Mod 1 Amt (ID 173): {mod_val:.4f} (Should be 0.0 if inactive, or high value if active)")

print("\n--- Audio Embeddings & Matches ---")
if generated_audio:
    # 1. Print Vector Shapes (Access via ['vectors'])
    print(f"Osc A Vector: {generated_audio['vectors']['osc_a'].shape}")
    print(f"Osc B Vector: {generated_audio['vectors']['osc_b'].shape}")
    print(f"Noise Vector: {generated_audio['vectors']['noise'].shape}")

    # 2. Print Matches (Access via ['matches'])
    if "matches" in generated_audio:
        matches = generated_audio["matches"]

        print("\n[Oscillator A Top 3 Matches]:")
        for m in matches["osc_a"]:
            print(f"  - {m['name']} (Score: {m['score']:.3f})")

        print("\n[Oscillator B Top 3 Matches]:")
        for m in matches["osc_b"]:
            print(f"  - {m['name']} (Score: {m['score']:.3f})")

        print("\n[Noise Oscillator Top 3 Matches]:")
        for m in matches["noise"]:
            print(f"  - {m['name']} (Score: {m['score']:.3f})")

print("\n--- Full JSON Snippet (First 3 items) ---")
print(json.dumps({k: preset_json[k] for k in list(preset_json.keys())[:]}, indent=2))

"""# Data Interpolation and Visualization

## Interpolations
"""

# Cell 5.1 — Latent Space Interpolation & Visualization

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# --- 1. Helper to find correct indices ---
def get_param_index(target_name, serum_parameters):
    """
    Finds the array index of a parameter by name.
    """
    for group_name, params in serum_parameters.items():
        for p in params:
            if p['name'] == target_name:
                return int(p['id'])
    return None

# --- 2. Interpolation Function ---
def interpolate_prompts(model, start_prompt, end_prompt, steps=10, z_seed=42):
    """
    Morphs between two text descriptions using the VAE Decoder.
    """
    # A. Encode both prompts
    # Use the robust function we fixed in Cell 1.4
    emb_start = clap_encode_text([start_prompt])[0]
    emb_end = clap_encode_text([end_prompt])[0]

    # B. Fixed Z
    np.random.seed(z_seed)

    # --- FIX IS HERE ---
    # We must match the Decoder's input size (Total Latent Dim: 256)
    # The decoder input_shape is a list: [(None, 256), (None, 512)]
    # We grab the dimension from the first input.
    total_latent_dim = model.vae_decoder.input_shape[0][1]

    z_fixed = np.random.normal(size=(1, total_latent_dim)).astype('float32')
    # -------------------

    # C. Linear Interpolation
    interpolated_params = []
    alphas = np.linspace(0, 1, steps)

    print(f"Morphing: '{start_prompt}' -> '{end_prompt}'")

    for alpha in alphas:
        # Interpolate text embedding
        emb_interp = (1 - alpha) * emb_start + alpha * emb_end
        emb_interp = emb_interp.reshape(1, -1)

        # Predict
        preds = model.vae_decoder.predict([z_fixed, emb_interp], verbose=0)

        # Reconstruct
        param_map = {int(p['id']): p for g in SERUM_PARAMETERS.values() for p in g}

        params, _ = reconstruct_parameters_from_heads(
            preds,
            parameter_types=param_map,
            categorical_num_classes=categorical_num_classes,
            sample_categorical=False, # Deterministic for smooth plots
            noise_level=0.0
        )
        interpolated_params.append(params)

    return np.array(interpolated_params), alphas

# --- CONFIG ---
prompt_a = "Aggressive, Dubstep, Bass"
prompt_b = "Soft, Ambient, Pad"

if 'best_model' in globals():
    interp_data, alphas = interpolate_prompts(best_model, prompt_a, prompt_b, steps=20)

    # --- PARAMETERS TO TRACK ---
    target_params = [
        {"name": "A Octave",       "color": "blue"},
        {"name": "Sub Osc Level",  "color": "darkgreen"},
        {"name": "Fil Cutoff",     "color": "red"},
        {"name": "Fil Reso",       "color": "orange"},
        {"name": "Env1 Atk",       "color": "purple"},
        {"name": "LFO1 Rate",      "color": "brown"},
        {"name": "Dist_Wet",       "color": "pink"},
        {"name": "VerbSize",       "color": "cyan"},
    ]

    # --- PLOTTING ---
    plt.figure(figsize=(12, 6))

    for p in target_params:
        col_idx = get_param_index(p["name"], SERUM_PARAMETERS)

        if col_idx is not None and col_idx < interp_data.shape[1]:
            values = interp_data[:, col_idx]
            plt.plot(alphas, values, marker='o', label=p["name"], color=p["color"], linewidth=2, alpha=0.8)
        else:
            print(f"Warning: Could not find parameter '{p['name']}' or index out of bounds.")

    plt.title(f"Parameter Morphing:\n'{prompt_a}'  >>>  '{prompt_b}'")
    plt.xlabel("Interpolation Alpha")
    plt.ylabel("Normalized Parameter Value (0-1)")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.show()
else:
    print("Model not loaded.")

