# -*- coding: utf-8 -*-
"""V2.7 Conditional VAE - Latent Diffusion - ResMLP - Retrained - SOTA - RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hj9tVIu8U3TAUp1zC-m_paQ7vM5nNJwT

# Model Overview

This notebook implements a **Two-Stage Latent Diffusion Model (LDM)** for generating Serum synthesizer patches from text.

### The Architecture Strategy

Directly predicting 200+ complex synthesizer parameters from text is unstable. Instead, this model uses a "Compress then Generate" strategy:

1.  **Compression (VAE):** Compresses the complex, non-linear parameter space into a smooth, lower-dimensional "Latent Space."
2.  **Generation (Diffusion):** Learns to navigate this latent space based on text prompts.

---

## 1. Stage 1: Conditional FiLM VAE (The Compressor)

The VAE learns a bi-directional mapping between **Serum Parameters** and **Latent Factors**.

* **Encoder \( q(z \mid x, c) \):**
    * **Inputs:** 202 Serum parameters + CLAP text embedding.
    * **Output:** A probabilistic latent distribution \( z \) (128-dim).
    * **Constraint:** Uses activity masking to ignore parameters for modules that are turned off (e.g., masking Oscillator B parameters if `Osc B On == False`).

* **Decoder \( p(x \mid z, c) \):**
    * **Inputs:** Latent vector \( z \) + CLAP text embedding.
    * **Conditioning:** Uses **FiLM (Feature-wise Linear Modulation)**. The text embedding predicts Gamma (scale) and Beta (shift) factors that modulate the neural network activations layer-by-layer. This ensures the text exerts control at every depth of the decoding process.
    * **Multi-Head Output:** The final layer splits into specialized heads to handle different data types (Sigmoid for knobs, Softmax for menus, Focal Loss for sparse Mod Matrix gates).

---

## 2. Stage 2: Latent Diffusion (The Generator)

Once the VAE is trained, we freeze it. The Diffusion model replaces the standard Gaussian prior, allowing us to sample high-fidelity latents conditioned on text.

* **Forward Process:**
    * We take real preset latents \( z_0 \) and gradually add Gaussian noise until they become pure random noise \( z_T \).

* **Reverse Process (The Denoiser):**
    * **Architecture:** A **ResMLP (Residual MLP)** network.
    * **Conditioning:** The network is conditioned on **Time** (noise level) and **Text** (CLAP embedding) via FiLM layers.
    * **Objective:** The model predicts the noise component \( \epsilon \) present in the noisy latent \( z_t \). By subtracting this predicted noise over 1000 timesteps, we navigate from random chaos back to a structured preset latent.

---

## 3. Inference Pipeline

1.  **Encode Text:** Convert user prompt to CLAP embedding.
2.  **Sample Noise:** Initialize a random latent vector \( z_T \).
3.  **Denoise:** Use the Stage 2 Denoiser to iteratively remove noise, guided by the text embedding, arriving at \( z_0 \).
4.  **Decode:** Pass \( z_0 \) through the frozen Stage 1 VAE Decoder to reconstruct the valid Serum parameter set.
"""

# Cell 1.1

# CLEAN START: remove default packages
!pip uninstall -y dopamine-rl flax chex optax orbax-checkpoint tensorflow-hub keras-hub ydf jax jaxlib tf-keras tensorflow-text tensorflow-decision-forests || true

# Install a minimal, compatible stack for Colab
!pip install -q --upgrade pip
!pip install -q "numpy==2.0.2" "tensorflow==2.19.0" \
                "transformers==4.45.2" "sentence-transformers==2.7.0"

# Install CUDA wheels for PyTorch (GPU / T4).
!pip install -q "torch==2.8.0" "torchvision==0.23.0" "torchaudio==2.8.0" \
  --extra-index-url https://download.pytorch.org/whl/cu126

# Sanity check: Print what GPU using
!nvidia-smi -L || true

# Cell 1.2 — GPU Setup

import os
import numpy as np
import tensorflow as tf
from tensorflow import keras

# Tensorflow log level
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

# GPU Setup
gpus = tf.config.list_physical_devices("GPU")
print("GPUs visible to TF:", gpus)
for gpu in gpus:
    try:
        tf.config.experimental.set_memory_growth(gpu, True)
    except Exception as e:
        print("Could not set memory growth:", e)

print("TF:", tf.__version__)
print("tf.keras:", keras.__version__)
print("NumPy:", np.__version__)

# Cell 1.3
# Mount Drive, Setup save directory

import os
from google.colab import drive

# 1. Mount Drive (Force remount to ensure fresh connection)
drive.mount('/content/drive', force_remount=True)

# 2. Define your Save Directory clearly
# Using a variable ensures you don't have typos in different cells
SAVE_DIR = "/content/drive/My Drive/Colab Notebooks/notebooks/models/vae/text_input/V2 - Activity Gating, FiLM/v2p7 - retrained - rag/output_models"

# 3. Create the directory (and all intermediate folders) if they don't exist
try:
    os.makedirs(SAVE_DIR, exist_ok=True)
    print(f"✅ Directory confirmed: {SAVE_DIR}")
except OSError as e:
    print(f"❌ Error creating directory: {e}")

# 4. Write Test
# Create a dummy file to verify we actually have write permissions before training starts
test_file = os.path.join(SAVE_DIR, "write_test.txt")
try:
    with open(test_file, "w") as f:
        f.write("Access granted.")
    os.remove(test_file) # Clean up
    print("✅ Write access confirmed. You are ready to train.")
except Exception as e:
    print(f"❌ Write access FAILED: {e}")
    print("Check your Drive permissions or path string.")

# Cell 1.4 — Initialize CLAP Text Encoder
# This model converts natural language descriptions into 512-dimensional
# embeddings that will guide the Audio VAE via FiLM layers.

import torch
from transformers import ClapModel, ClapProcessor

# Use GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

# CLAP Model Initialization
# We load the fused version of CLAP (better at capturing fine-grained audio detail)
clap_model_name = "laion/clap-htsat-fused"
clap_model = ClapModel.from_pretrained(clap_model_name).to(device)
clap_processor = ClapProcessor.from_pretrained(clap_model_name)

# Set to 'eval' to disable dropout/batch norm updates; ensures consistent embeddings.
clap_model.eval()

@torch.no_grad() # Disable gradient calculation to save VRAM on the T4
def clap_encode_text(texts, batch_size=128, normalize=True, max_length=None):
    """
    Encodes a list of strings into a NumPy array of embeddings.

    Args:
        texts (list): Sentences describing audio (e.g., "Gritty dubstep bass").
        batch_size (int): Number of texts to process at once on the GPU.
        normalize (bool): If True, output vectors have a unit length of 1.

    Returns:
        np.ndarray: Matrix of shape (len(texts), 512).
    """
    out = []
    for i in range(0, len(texts), batch_size):
        # Ensure all inputs are strings to avoid tokenizer errors
        batch = [str(t) for t in texts[i:i+batch_size]]

        # Tokenize: Convert text to fixed-length tensors for the Transformer
        inputs = clap_processor(
            text=batch,
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=max_length
        ).to(device)

        # Forward pass: Extract the 512-dimensional 'meaning' of the text
        feats = clap_model.get_text_features(**inputs)  # Output shape: [Batch, 512]

        # L2 Normalization: Keeps embedding values stable for the VAE's FiLM layers
        if normalize:
            feats = torch.nn.functional.normalize(feats, dim=-1)

        # Move back to CPU to free up GPU memory for the TensorFlow VAE
        out.append(feats.cpu())

    # Concatenate batches and convert to NumPy (the standard format for TF/Keras)
    return torch.cat(out, dim=0).numpy()

print(f"✅ CLAP loaded and ready on: {device}")

"""# Load Data"""

# Cell 2.1 (Updated: Filter FIRST, then Expand)

import numpy as np
import os

# 1. Load the Serum parameters (Targets)
# Shape: (N, 202)
serum_params_original = np.load(
    '/content/drive/My Drive/Colab Notebooks/data/vectors/cleaned/combined/combined_params_categorical.npy',
    allow_pickle=True
).astype('float32')

# 2. Load the Perturbed Descriptions (Input Text)
try:
    serum_preset_descriptions_perturbed = np.load(
        '/content/drive/My Drive/Colab Notebooks/data/vectors/cleaned/combined/combined_perturbed_descriptions.npy',
        allow_pickle=True
    )
    print(f"✅ Loaded Perturbed Descriptions. Shape: {serum_preset_descriptions_perturbed.shape}")
except FileNotFoundError:
    print("❌ Error: Perturbed descriptions file not found. Falling back to duplication.")
    # Fallback: Load original and tile it to match shape
    original_desc = np.load('/content/drive/My Drive/Colab Notebooks/data/vectors/cleaned/combined/combined_descriptions.npy', allow_pickle=True)
    # Assume we want (5, N) for fallback consistency
    serum_preset_descriptions_perturbed = np.tile(original_desc, (5, 1))

# 3. Load Masks (for filtering)
osc_masks_original = np.load(
    '/content/drive/My Drive/Colab Notebooks/data/vectors/combined_clap_validity_mask.npy',
    allow_pickle=True
).astype('float32')

# ==============================================================================
# STEP 1: APPLY VALIDITY MASK (Before Expansion)
# ==============================================================================
print(f"\n--- Pre-Filter Shapes ---")
print(f"Params: {serum_params_original.shape}")
print(f"Masks:  {osc_masks_original.shape}")
print(f"Descs:  {serum_preset_descriptions_perturbed.shape}")

# Create mask: Find rows where Osc A, B, and Noise are all active
# Shape: (N,) - Boolean array
valid_indices = np.all(osc_masks_original > 0.5, axis=1)

# Apply mask to Parameters (Filters rows)
serum_params_filtered = serum_params_original[valid_indices]

# Apply mask to Descriptions (Handles both shape possibilities)
if serum_preset_descriptions_perturbed.shape[0] == 5:
    # Shape is (5, N). We slice columns (axis 1).
    serum_preset_descriptions_filtered = serum_preset_descriptions_perturbed[:, valid_indices]
else:
    # Shape is (N, 5). We slice rows (axis 0).
    serum_preset_descriptions_filtered = serum_preset_descriptions_perturbed[valid_indices, :]

print(f"\n--- Post-Filter Shapes (Valid Presets Only) ---")
print(f"Params: {serum_params_filtered.shape}")
print(f"Descs:  {serum_preset_descriptions_filtered.shape}")

# ==============================================================================
# STEP 2: EXPANSION & FLATTENING (1x -> 5x)
# ==============================================================================

# A. Expand Parameters (Repeat valid rows 5 times)
# Example: [PresetA, PresetB] -> [PresetA, PresetA, PresetA, PresetA, PresetA, PresetB...]
serum_params = np.repeat(serum_params_filtered, 5, axis=0)

# B. Flatten Descriptions
# We want the order to match np.repeat: All 5 variants of Preset A, then all 5 of Preset B.
if serum_preset_descriptions_filtered.shape[0] == 5:
    # Shape is (5, N_valid). Transpose to (N_valid, 5) then flatten.
    # This ensures [P1_v1, P1_v2... P1_v5, P2_v1...] order.
    serum_preset_descriptions = serum_preset_descriptions_filtered.T.flatten()
else:
    # Shape is (N_valid, 5). Just flatten (defaults to row-major order).
    serum_preset_descriptions = serum_preset_descriptions_filtered.flatten()

# ==============================================================================
# STEP 3: SLICING (Optional)
# ==============================================================================
# If you need to skip the first X presets (e.g. for validation holdout).
# NOTE: start_index is now in "expanded" space (5x).
start_index = 0
# start_index = 4252 * 5

serum_params = serum_params[start_index:]
serum_preset_descriptions = serum_preset_descriptions[start_index:]

# ==============================================================================
# 4. Load Default Wavetable/Noise Libraries (Unchanged)
# ==============================================================================
LIB_DIR = '/content/drive/My Drive/Colab Notebooks/data/vectors'
try:
    WT_LIB_NAMES = np.load(os.path.join(LIB_DIR, 'default_wavetable_names.npy'), allow_pickle=True)
    WT_LIB_EMBEDS = np.load(os.path.join(LIB_DIR, 'default_wavetable_embeddings.npy'), allow_pickle=True).astype('float32')
    NOISE_LIB_NAMES = np.load(os.path.join(LIB_DIR, 'default_noise_names.npy'), allow_pickle=True)
    NOISE_LIB_EMBEDS = np.load(os.path.join(LIB_DIR, 'default_noise_embeddings.npy'), allow_pickle=True).astype('float32')
    print("✅ Default Audio Libraries Loaded Successfully.")
except FileNotFoundError:
    WT_LIB_NAMES, WT_LIB_EMBEDS, NOISE_LIB_NAMES, NOISE_LIB_EMBEDS = None, None, None, None

# ==============================================================================

print("\n--- Final Training Data Shapes ---")
print(f"Serum Params (X):      {serum_params.shape}")
print(f"Descriptions (Y):      {serum_preset_descriptions.shape}")

# Cell 2.2
# SERUM_PARAMETERS with the nested structure required for Activity Gating

SERUM_PARAMETERS = {
    "global": [
        {"id": "0", "serum_id": "0", "name": "MasterVol", "type": "continuous"},
        {"id": "1", "serum_id": "65", "name": "PortTime", "type": "continuous"},
        {"id": "2", "serum_id": "66", "name": "PortCurve", "type": "continuous"},
    ],
    "osc_a": [
        {"id": "3", "serum_id": "212", "name": "Osc A On", "type": "boolean"},
        {"id": "4", "serum_id": "1", "name": "A Vol", "type": "continuous"},
        {"id": "5", "serum_id": "2", "name": "A Pan", "type": "continuous"},
        {"id": "6", "serum_id": "3", "name": "A Octave", "type": "categorical", "num_categories": 9},
        {"id": "7", "serum_id": "4", "name": "A Semi", "type": "categorical", "num_categories": 25},
        {"id": "8", "serum_id": "5", "name": "A Fine", "type": "continuous"},
        {"id": "9", "serum_id": "10", "name": "A CoarsePit", "type": "continuous"},
        {"id": "10", "serum_id": "6", "name": "A Unison", "type": "continuous"},
        {"id": "11", "serum_id": "7", "name": "A UniDet", "type": "continuous"},
        {"id": "12", "serum_id": "8", "name": "A UniBlend", "type": "continuous"},
        {"id": "13", "serum_id": "172", "name": "A Uni LR", "type": "continuous"},
        {"id": "14", "serum_id": "174", "name": "A Uni Warp", "type": "continuous"},
        {"id": "15", "serum_id": "176", "name": "A Uni WTPos", "type": "continuous"},
        {"id": "16", "serum_id": "178", "name": "A Uni Stack", "type": "categorical", "num_categories": 9},
        {"id": "17", "serum_id": "11", "name": "A WTPos", "type": "continuous"},
        {"id": "18", "serum_id": "168", "name": "WarpOscA", "type": "categorical", "num_categories": 23},
        {"id": "19", "serum_id": "9", "name": "A Warp", "type": "continuous"},
        {"id": "20", "serum_id": "12", "name": "A RandPhase", "type": "continuous"},
        {"id": "21", "serum_id": "13", "name": "A Phase", "type": "continuous"},
    ],
    "osc_b": [
        {"id": "22", "serum_id": "213", "name": "Osc B On", "type": "boolean"},
        {"id": "23", "serum_id": "14", "name": "B Vol", "type": "continuous"},
        {"id": "24", "serum_id": "15", "name": "B Pan", "type": "continuous"},
        {"id": "25", "serum_id": "16", "name": "B Octave", "type": "categorical", "num_categories": 9},
        {"id": "26", "serum_id": "17", "name": "B Semi", "type": "categorical", "num_categories": 25},
        {"id": "27", "serum_id": "18", "name": "B Fine", "type": "continuous"},
        {"id": "28", "serum_id": "23", "name": "B CoarsePit", "type": "continuous"},
        {"id": "29", "serum_id": "19", "name": "B Unison", "type": "continuous"},
        {"id": "30", "serum_id": "20", "name": "B UniDet", "type": "continuous"},
        {"id": "31", "serum_id": "21", "name": "B UniBlend", "type": "continuous"},
        {"id": "32", "serum_id": "173", "name": "B Uni LR", "type": "continuous"},
        {"id": "33", "serum_id": "175", "name": "B Uni Warp", "type": "continuous"},
        {"id": "34", "serum_id": "177", "name": "B Uni WTPos", "type": "continuous"},
        {"id": "35", "serum_id": "179", "name": "B Uni Stack", "type": "categorical", "num_categories": 9},
        {"id": "36", "serum_id": "24", "name": "B WTPos", "type": "continuous"},
        {"id": "37", "serum_id": "169", "name": "WarpOscB", "type": "categorical", "num_categories": 23},
        {"id": "38", "serum_id": "22", "name": "B Warp", "type": "continuous"},
        {"id": "39", "serum_id": "25", "name": "B RandPhase", "type": "continuous"},
        {"id": "40", "serum_id": "26", "name": "B Phase", "type": "continuous"},
    ],
    "noise_osc": [
        {"id": "41", "serum_id": "214", "name": "Osc N On", "type": "boolean"},
        {"id": "42", "serum_id": "27", "name": "Noise Level", "type": "continuous"},
        {"id": "43", "serum_id": "28", "name": "Noise Pitch", "type": "continuous"},
        {"id": "44", "serum_id": "29", "name": "Noise Fine", "type": "continuous"},
        {"id": "45", "serum_id": "30", "name": "Noise Pan", "type": "continuous"},
        {"id": "46", "serum_id": "31", "name": "Noise RandPhase", "type": "continuous"},
        {"id": "47", "serum_id": "32", "name": "Noise Phase", "type": "continuous"},
    ],
    "sub_osc": [
        {"id": "48", "serum_id": "215", "name": "Osc S On", "type": "boolean"},
        {"id": "49", "serum_id": "33", "name": "Sub Osc Level", "type": "continuous"},
        {"id": "50", "serum_id": "34", "name": "Sub Osc Pan", "type": "continuous"},
        {"id": "51", "serum_id": "170", "name": "SubOscShape", "type": "categorical", "num_categories": 6},
        {"id": "52", "serum_id": "171", "name": "SubOscOctave", "type": "continuous"},
    ],
    "filter": [
        {"id": "53", "serum_id": "216", "name": "Filter On", "type": "boolean"},
        {"id": "54", "serum_id": "44", "name": "Fil Type", "type": "categorical", "num_categories": 95},
        {"id": "55", "serum_id": "40", "name": "OscA>Fil", "type": "boolean"},
        {"id": "56", "serum_id": "41", "name": "OscB>Fil", "type": "boolean"},
        {"id": "57", "serum_id": "42", "name": "OscN>Fil", "type": "boolean"},
        {"id": "58", "serum_id": "43", "name": "OscS>Fil", "type": "boolean"},
        {"id": "59", "serum_id": "45", "name": "Fil Cutoff", "type": "continuous"},
        {"id": "60", "serum_id": "46", "name": "Fil Reso", "type": "continuous"},
        {"id": "61", "serum_id": "47", "name": "Fil Driv", "type": "continuous"},
        {"id": "62", "serum_id": "48", "name": "Fil Var", "type": "continuous"},
        {"id": "63", "serum_id": "49", "name": "Fil Mix", "type": "continuous"},
        {"id": "64", "serum_id": "50", "name": "Fil Stereo", "type": "continuous"},
    ],
    "envelopes": [
        {"id": "65", "serum_id": "35", "name": "Env1 Atk", "type": "continuous"},
        {"id": "66", "serum_id": "36", "name": "Env1 Hold", "type": "continuous"},
        {"id": "67", "serum_id": "37", "name": "Env1 Dec", "type": "continuous"},
        {"id": "68", "serum_id": "38", "name": "Env1 Sus", "type": "continuous"},
        {"id": "69", "serum_id": "39", "name": "Env1 Rel", "type": "continuous"},
        {"id": "70", "serum_id": "51", "name": "Env2 Atk", "type": "continuous"},
        {"id": "71", "serum_id": "52", "name": "Env2 Hold", "type": "continuous"},
        {"id": "72", "serum_id": "53", "name": "Env2 Dec", "type": "continuous"},
        {"id": "73", "serum_id": "54", "name": "Env2 Sus", "type": "continuous"},
        {"id": "74", "serum_id": "55", "name": "Env2 Rel", "type": "continuous"},
    ],
    "lfos": [
        {"id": "75", "serum_id": "61", "name": "LFO1 Rate", "type": "categorical", "num_categories": 19},
        {"id": "76", "serum_id": "273", "name": "LFO1 Rise", "type": "categorical", "num_categories": 20},
        {"id": "77", "serum_id": "281", "name": "LFO1 Delay", "type": "categorical", "num_categories": 20},
        {"id": "78", "serum_id": "223", "name": "LFO1 Smooth", "type": "continuous"},
        {"id": "79", "serum_id": "62", "name": "LFO2 Rate", "type": "categorical", "num_categories": 19},
        {"id": "80", "serum_id": "274", "name": "LFO2 Rise", "type": "categorical", "num_categories": 20},
        {"id": "81", "serum_id": "282", "name": "LFO2 Delay", "type": "categorical", "num_categories": 20},
        {"id": "82", "serum_id": "224", "name": "LFO2 Smooth", "type": "continuous"},
    ],
    "fx_hyper_dimension": [
        {"id": "83", "serum_id": "163", "name": "Hyp Enable", "type": "boolean"},
        {"id": "84", "serum_id": "148", "name": "Hyp_Rate", "type": "continuous"},
        {"id": "85", "serum_id": "149", "name": "Hyp_Detune", "type": "continuous"},
        {"id": "86", "serum_id": "150", "name": "Hyp_Unison", "type": "continuous"},
        {"id": "87", "serum_id": "147", "name": "Hyp_Wet", "type": "continuous"},
        {"id": "88", "serum_id": "152", "name": "HypDim_Size", "type": "continuous"},
        {"id": "89", "serum_id": "153", "name": "HypDim_Mix", "type": "continuous"},
    ],
    "fx_distortion": [
        {"id": "90", "serum_id": "154", "name": "Dist Enable", "type": "boolean"},
        {"id": "91", "serum_id": "96", "name": "Dist_Wet", "type": "continuous"},
        {"id": "92", "serum_id": "97", "name": "Dist_Drv", "type": "continuous"},
        {"id": "93", "serum_id": "99", "name": "Dist_Mode", "type": "categorical", "num_categories": 16},
        {"id": "94", "serum_id": "102", "name": "Dist_PrePost", "type": "categorical", "num_categories": 3},
        {"id": "95", "serum_id": "98", "name": "Dist_L/B/H", "type": "categorical", "num_categories": 3},
        {"id": "96", "serum_id": "100", "name": "Dist_Freq", "type": "continuous"},
        {"id": "97", "serum_id": "101", "name": "Dist_BW", "type": "continuous"},
    ],
    "fx_flanger": [
        {"id": "98", "serum_id": "155", "name": "Flg Enable", "type": "boolean"},
        {"id": "99", "serum_id": "103", "name": "Flg_Wet", "type": "continuous"},
        {"id": "100", "serum_id": "104", "name": "Flg_BPM_Sync", "type": "boolean"},
        {"id": "101", "serum_id": "105", "name": "Flg_Rate", "type": "continuous"},
        {"id": "102", "serum_id": "106", "name": "Flg_Dep", "type": "continuous"},
        {"id": "103", "serum_id": "107", "name": "Flg_Feed", "type": "continuous"},
        {"id": "104", "serum_id": "108", "name": "Flg_Stereo", "type": "continuous"},
    ],
    "fx_phaser": [
        {"id": "105", "serum_id": "156", "name": "Phs Enable", "type": "boolean"},
        {"id": "106", "serum_id": "109", "name": "Phs_Wet", "type": "continuous"},
        {"id": "107", "serum_id": "110", "name": "Phs_BPM_Sync", "type": "boolean"},
        {"id": "108", "serum_id": "111", "name": "Phs_Rate", "type": "continuous"},
        {"id": "109", "serum_id": "112", "name": "Phs_Dpth", "type": "continuous"},
        {"id": "110", "serum_id": "113", "name": "Phs_Frq", "type": "continuous"},
        {"id": "111", "serum_id": "114", "name": "Phs_Feed", "type": "continuous"},
        {"id": "112", "serum_id": "115", "name": "Phs_Stereo", "type": "continuous"},
    ],
    "fx_chorus": [
        {"id": "113", "serum_id": "157", "name": "Cho Enable", "type": "boolean"},
        {"id": "114", "serum_id": "116", "name": "Cho_Wet", "type": "continuous"},
        {"id": "115", "serum_id": "117", "name": "Cho_BPM_Sync", "type": "boolean"},
        {"id": "116", "serum_id": "118", "name": "Cho_Rate", "type": "continuous"},
        {"id": "117", "serum_id": "119", "name": "Cho_Dly", "type": "continuous"},
        {"id": "118", "serum_id": "120", "name": "Cho_Dly2", "type": "continuous"},
        {"id": "119", "serum_id": "121", "name": "Cho_Dep", "type": "continuous"},
        {"id": "120", "serum_id": "122", "name": "Cho_Feed", "type": "continuous"},
        {"id": "121", "serum_id": "123", "name": "Cho_Filt", "type": "continuous"},
    ],
    "fx_delay": [
        {"id": "122", "serum_id": "158", "name": "Dly Enable", "type": "boolean"},
        {"id": "123", "serum_id": "124", "name": "Dly_Wet", "type": "continuous"},
        {"id": "124", "serum_id": "125", "name": "Dly_Freq", "type": "continuous"},
        {"id": "125", "serum_id": "126", "name": "Dly_BW", "type": "continuous"},
        {"id": "126", "serum_id": "127", "name": "Dly_BPM_Sync", "type": "boolean"},
        {"id": "127", "serum_id": "128", "name": "Dly_Link", "type": "boolean"},
        {"id": "128", "serum_id": "129", "name": "Dly_TimL", "type": "categorical", "num_categories": 12},
        {"id": "129", "serum_id": "130", "name": "Dly_TimR", "type": "categorical", "num_categories": 12},
        {"id": "130", "serum_id": "131", "name": "Dly_Mode", "type": "categorical", "num_categories": 3},
        {"id": "131", "serum_id": "132", "name": "Dly_Feed", "type": "continuous"},
        {"id": "132", "serum_id": "133", "name": "Dly_Off L", "type": "continuous"},
        {"id": "133", "serum_id": "134", "name": "Dly_Off R", "type": "continuous"},
    ],
    "fx_compressor": [
        {"id": "134", "serum_id": "159", "name": "Comp Enable", "type": "boolean"},
        {"id": "135", "serum_id": "135", "name": "Cmp_Thr", "type": "continuous"},
        {"id": "136", "serum_id": "136", "name": "Cmp_Rat", "type": "categorical", "num_categories": 21},
        {"id": "137", "serum_id": "137", "name": "Cmp_Att", "type": "continuous"},
        {"id": "138", "serum_id": "138", "name": "Cmp_Rel", "type": "continuous"},
        {"id": "139", "serum_id": "139", "name": "CmpGain", "type": "continuous"},
        {"id": "140", "serum_id": "140", "name": "CmpMBnd", "type": "categorical", "num_categories": 2},
        {"id": "141", "serum_id": "270", "name": "CompMB L", "type": "continuous"},
        {"id": "142", "serum_id": "271", "name": "CompMB M", "type": "continuous"},
        {"id": "143", "serum_id": "272", "name": "CompMB H", "type": "continuous"},
        {"id": "144", "serum_id": "269", "name": "Comp_Wet", "type": "continuous"},
    ],
    "fx_reverb": [
        {"id": "145", "serum_id": "160", "name": "Rev Enable", "type": "boolean"},
        {"id": "146", "serum_id": "81", "name": "Verb Wet", "type": "continuous"},
        {"id": "147", "serum_id": "82", "name": "VerbSize", "type": "continuous"},
        {"id": "148", "serum_id": "83", "name": "Decay", "type": "continuous"},
        {"id": "149", "serum_id": "84", "name": "VerbLoCt", "type": "continuous"},
        {"id": "150", "serum_id": "85", "name": "Spin Rate", "type": "continuous"},
        {"id": "151", "serum_id": "86", "name": "VerbHiCt", "type": "continuous"},
        {"id": "152", "serum_id": "87", "name": "Spin Depth", "type": "continuous"},
    ],
    "fx_eq": [
        {"id": "153", "serum_id": "161", "name": "EQ Enable", "type": "boolean"},
        {"id": "154", "serum_id": "88", "name": "EQ FrqL", "type": "continuous"},
        {"id": "155", "serum_id": "89", "name": "EQ FrqH", "type": "continuous"},
        {"id": "156", "serum_id": "90", "name": "EQ Q L", "type": "continuous"},
        {"id": "157", "serum_id": "91", "name": "EQ Q H", "type": "continuous"},
        {"id": "158", "serum_id": "92", "name": "EQ Vol L", "type": "continuous"},
        {"id": "159", "serum_id": "93", "name": "EQ Vol H", "type": "continuous"},
        {"id": "160", "serum_id": "94", "name": "EQ TypL", "type": "categorical", "num_categories": 3},
        {"id": "161", "serum_id": "95", "name": "EQ TypH", "type": "categorical", "num_categories": 3},
    ],
    "fx_filter": [
        {"id": "162", "serum_id": "162", "name": "FX Fil Enable", "type": "boolean"},
        {"id": "163", "serum_id": "141", "name": "FX Fil Wet", "type": "continuous"},
        {"id": "164", "serum_id": "142", "name": "FX Fil Type", "type": "categorical", "num_categories": 89},
        {"id": "165", "serum_id": "143", "name": "FX Fil Freq", "type": "continuous"},
        {"id": "166", "serum_id": "144", "name": "FX Fil Reso", "type": "continuous"},
        {"id": "167", "serum_id": "145", "name": "FX Fil Drive", "type": "continuous"},
        {"id": "168", "serum_id": "146", "name": "FX Fil Var", "type": "continuous"},
        {"id": "169", "serum_id": "268", "name": "FX Fil Pan", "type": "continuous"},
    ],
    "mod_matrix": [
        {"id": "170", "serum_id": "180", "name": "Mod 1 amt", "type": "continuous"},
        {"id": "171", "serum_id": "182", "name": "Mod 2 amt", "type": "continuous"},
        {"id": "172", "serum_id": "184", "name": "Mod 3 amt", "type": "continuous"},
        {"id": "173", "serum_id": "186", "name": "Mod 4 amt", "type": "continuous"},
        {"id": "174", "serum_id": "188", "name": "Mod 5 amt", "type": "continuous"},
        {"id": "175", "serum_id": "190", "name": "Mod 6 amt", "type": "continuous"},
        {"id": "176", "serum_id": "192", "name": "Mod 7 amt", "type": "continuous"},
        {"id": "177", "serum_id": "194", "name": "Mod 8 amt", "type": "continuous"},
        {"id": "178", "serum_id": "196", "name": "Mod 9 amt", "type": "continuous"},
        {"id": "179", "serum_id": "198", "name": "Mod10 amt", "type": "continuous"},
        {"id": "180", "serum_id": "200", "name": "Mod11 amt", "type": "continuous"},
        {"id": "181", "serum_id": "202", "name": "Mod12 amt", "type": "continuous"},
        {"id": "182", "serum_id": "204", "name": "Mod13 amt", "type": "continuous"},
        {"id": "183", "serum_id": "206", "name": "Mod14 amt", "type": "continuous"},
        {"id": "184", "serum_id": "208", "name": "Mod15 amt", "type": "continuous"},
        {"id": "185", "serum_id": "210", "name": "Mod16 amt", "type": "continuous"},
        {"id": "186", "serum_id": "228", "name": "Mod17 amt", "type": "continuous"},
        {"id": "187", "serum_id": "230", "name": "Mod18 amt", "type": "continuous"},
        {"id": "188", "serum_id": "232", "name": "Mod19 amt", "type": "continuous"},
        {"id": "189", "serum_id": "234", "name": "Mod20 amt", "type": "continuous"},
        {"id": "190", "serum_id": "236", "name": "Mod21 amt", "type": "continuous"},
        {"id": "191", "serum_id": "238", "name": "Mod22 amt", "type": "continuous"},
        {"id": "192", "serum_id": "240", "name": "Mod23 amt", "type": "continuous"},
        {"id": "193", "serum_id": "242", "name": "Mod24 amt", "type": "continuous"},
        {"id": "194", "serum_id": "244", "name": "Mod25 amt", "type": "continuous"},
        {"id": "195", "serum_id": "246", "name": "Mod26 amt", "type": "continuous"},
        {"id": "196", "serum_id": "248", "name": "Mod27 amt", "type": "continuous"},
        {"id": "197", "serum_id": "250", "name": "Mod28 amt", "type": "continuous"},
        {"id": "198", "serum_id": "252", "name": "Mod29 amt", "type": "continuous"},
        {"id": "199", "serum_id": "254", "name": "Mod30 amt", "type": "continuous"},
        {"id": "200", "serum_id": "256", "name": "Mod31 amt", "type": "continuous"},
        {"id": "201", "serum_id": "258", "name": "Mod32 amt", "type": "continuous"},
    ],
}

# Cell 2.2 (Part 2) - Logic Update

# --- Index Lists for Type ---
continuous_param_indices = []
boolean_param_indices = []
categorical_param_indices = []
categorical_num_classes = {}

# Calculate total parameters
num_params = sum(len(group) for group in SERUM_PARAMETERS.values())

# Iterate over each group to populate indices
for group_name, params in SERUM_PARAMETERS.items():
    for pinfo in params:
        idx = int(pinfo["id"])
        ptype = pinfo["type"]

        if ptype == "continuous":
            continuous_param_indices.append(idx)
        elif ptype == "boolean":
            boolean_param_indices.append(idx)
        elif ptype == "categorical":
            categorical_param_indices.append(idx)
            categorical_num_classes[idx] = int(pinfo["num_categories"])
        else:
            raise ValueError(f"Unknown parameter type for index {idx}: {ptype}")

# Sorting indices to maintain sequential order in the lists
continuous_param_indices.sort()
boolean_param_indices.sort()
categorical_param_indices.sort()

print("continuous params:", len(continuous_param_indices))
print("boolean params:", len(boolean_param_indices))
print("categorical params:", len(categorical_param_indices))
print("categorical_num_classes:", len(categorical_num_classes))

# --- Group Masking Map ---
def create_group_mask_metadata(SERUM_PARAMETERS):
    group_map = {}
    for group_name, params in SERUM_PARAMETERS.items():
        enable_id = None
        dependent_ids = []
        for p in params:
            param_id = int(p["id"])
            dependent_ids.append(param_id)
            if p["name"].endswith(" On") or p["name"].endswith(" Enable"):
                enable_id = param_id
        if enable_id is not None:
            group_map[enable_id] = dependent_ids
    return group_map

GROUP_MASKING_MAP = create_group_mask_metadata(SERUM_PARAMETERS)

print("\nGroup Masking Map (Enable ID: [Dependent IDs]):")
print(GROUP_MASKING_MAP)

# --- Split Continuous Indices into Unipolar (0-1) and Bipolar (-1 to 1) ---
# UPDATED LOGIC: Mod Matrix parameters are now IDs 173 to 204.
# Range is exclusive at the stop, so we use 205.
mod_matrix_ids = set(range(170, 202))

unipolar_indices = [i for i in continuous_param_indices if i not in mod_matrix_ids]
bipolar_indices = [i for i in continuous_param_indices if i in mod_matrix_ids]

# Sort them to be safe
unipolar_indices.sort()
bipolar_indices.sort()

print(f"Unipolar params: {len(unipolar_indices)}")
print(f"Bipolar params: {len(bipolar_indices)} (Should be 32)")

"""# Training

## Split Data
"""

# Cell 3.1 — Load, encode, and split data (LEAK-PROOF STRATEGY)

from sklearn.model_selection import train_test_split

# 1. Encode All Text First
# (We encode everything first for speed, then slice based on indices)
description_embeddings = clap_encode_text(serum_preset_descriptions)
print("Total Embeddings:", description_embeddings.shape)

# 2. DEFINE GROUPS (The Leak Fix)
# We know every 5 rows belong to the same preset.
# Total Presets = Total Rows / 5
num_total_rows = len(serum_params)
samples_per_preset = 5
num_unique_presets = num_total_rows // samples_per_preset

print(f"Unique Presets: {num_unique_presets}")

# 3. Create Indices for Splitting
indices = np.arange(num_unique_presets)

# 4. Split indices (e.g. Preset 1 goes to Train, Preset 2 goes to Val)
train_indices_packed, val_indices_packed = train_test_split(
    indices,
    test_size=0.2,
    random_state=42
)

# 5. Expand Indices back to Rows
# If index 0 is in Train, we want rows 0, 1, 2, 3, 4.
def expand_indices(packed_indices, scale=5):
    expanded = []
    for idx in packed_indices:
        start = idx * scale
        end = start + scale
        expanded.extend(range(start, end))
    return np.array(expanded)

train_indices = expand_indices(train_indices_packed, scale=samples_per_preset)
val_indices = expand_indices(val_indices_packed, scale=samples_per_preset)

# 6. Apply Split
X_train = description_embeddings[train_indices].astype('float32')
y_train = serum_params[train_indices].astype('float32')

X_val = description_embeddings[val_indices].astype('float32')
y_val = serum_params[val_indices].astype('float32')

print("-" * 30)
print(f"Train Rows: {len(X_train)} (from {len(train_indices_packed)} unique presets)")
print(f"Val Rows:   {len(X_val)}   (from {len(val_indices_packed)} unique presets)")
print("-" * 30)

"""## Define Model Architecture"""

# Cell 3.2 — Conditional VAE & Latent Diffusion Architecture

import tensorflow as tf
import numpy as np
from tensorflow.keras import backend as K

from tensorflow.keras.layers import (
    Layer, Input, Dense, Concatenate, Dropout, BatchNormalization,
    LayerNormalization, LeakyReLU, Activation, Add, Multiply,
    Reshape, Flatten, MultiHeadAttention  # <--- Added these 3
)

from tensorflow.keras.models import Model
from tensorflow.keras.utils import register_keras_serializable
from keras.saving import serialize_keras_object, deserialize_keras_object

# --- 0. HYPERPARAMETER CONSTANTS ---
W_CONT      = 10.0
W_BOOL      = 5.0
W_CAT       = 15.0
W_MOD_GATE  = 5.0

# ==============================================================================
# 1. SHARED LAYERS
# ==============================================================================

@register_keras_serializable(package="custom", name="SliceLayer")
class SliceLayer(Layer):
    def __init__(self, indices, **kwargs):
        super().__init__(**kwargs)
        self.indices = [int(i) for i in (indices if isinstance(indices, (list, tuple)) else [indices])]
    def call(self, inputs):
        return tf.gather(inputs, self.indices, axis=1)
    def get_config(self):
        config = super().get_config()
        config.update({"indices": self.indices})
        return config

@register_keras_serializable(package="custom", name="FiLMLayer")
class FiLMLayer(Layer):
    def call(self, inputs):
        x, gamma, beta = inputs
        return x * gamma + beta

# ==============================================================================
# 2. VAE MODEL
# ==============================================================================

def sigmoid_focal_crossentropy(y_true, y_pred, alpha=0.25, gamma=2.0, from_logits=True):
    if from_logits: y_pred = tf.sigmoid(y_pred)
    bce = K.binary_crossentropy(y_true, y_pred)
    p_t = (y_true * y_pred) + ((1 - y_true) * (1 - y_pred))
    return alpha * K.pow(1.0 - p_t, gamma) * bce

@register_keras_serializable(package="custom", name="VAE_Text_to_Synth_Standard")
class VAE_Text_to_Synth_Standard(tf.keras.Model):
    def __init__(self, encoder, decoder, unipolar_indices, bipolar_indices,
                 bool_indices, cat_indices, categorical_num_classes, group_masking_map,
                 latent_dim, beta=1.0, latent_dropout_rate=0.0, **kwargs):
        super().__init__(**kwargs)
        self.encoder = encoder
        self.decoder = decoder
        self.unipolar_indices = [int(i) for i in unipolar_indices]
        self.bipolar_indices = [int(i) for i in bipolar_indices]
        self.bool_indices = [int(i) for i in bool_indices]
        self.cat_indices = [int(i) for i in cat_indices]
        self.categorical_num_classes = {int(k): int(v) for k, v in categorical_num_classes.items()}
        self.group_masking_map = {int(k): [int(x) for x in v] for k, v in (group_masking_map or {}).items()}
        self.param_to_enable = {int(pid): int(eid) for eid, mids in self.group_masking_map.items() for pid in mids if int(pid) != int(eid)}
        self.latent_dim = int(latent_dim)
        self.beta = tf.Variable(float(beta), trainable=False, dtype=tf.float32)
        self.latent_dropout_rate = float(latent_dropout_rate)

        self.total_loss_tracker = tf.keras.metrics.Mean(name="total_loss")
        self.reconstruction_loss_tracker = tf.keras.metrics.Mean(name="reconstruction_loss")
        self.kl_loss_tracker = tf.keras.metrics.Mean(name="kl_loss")

    def sanitize_inputs(self, params):
        mask_columns = []
        batch_len = tf.shape(params)[0]
        for i in range(params.shape[1]):
            parent_idx = self.param_to_enable.get(i)
            if parent_idx is not None:
                parent_col = params[:, parent_idx]
                gate = tf.cast(parent_col > 0.5, tf.float32)
                mask_columns.append(gate)
            else:
                mask_columns.append(tf.ones((batch_len,), dtype=tf.float32))
        mask_tensor = tf.stack(mask_columns, axis=1)
        return params * mask_tensor

    def call(self, inputs, training=False):
        text_embeddings, params_in = inputs
        params_clean = self.sanitize_inputs(params_in)
        z_mean, z_log_var = self.encoder([text_embeddings, params_clean])
        eps = tf.random.normal(shape=tf.shape(z_mean))
        z = z_mean + tf.exp(0.5 * z_log_var) * eps
        return self.decoder([z, text_embeddings], training=training)

    def _group_mask_matrix(self, head_indices, y_true):
        batch_size = tf.shape(y_true)[0]
        mask_cols = []
        for pid in head_indices:
            enable_id = self.param_to_enable.get(int(pid), None)
            if enable_id is None: mask_cols.append(tf.ones((batch_size, 1), dtype=tf.float32))
            else:
                enable_val = tf.gather(y_true, indices=[enable_id], axis=1)
                mask_cols.append(tf.cast(enable_val > 0.5, tf.float32))
        return tf.concat(mask_cols, axis=1) if len(mask_cols) > 1 else mask_cols[0]

    def calculate_loss(self, y_true, y_pred_list, z_mean, z_log_var):
        y_true_clean = self.sanitize_inputs(y_true)
        eps = 1e-7
        head_idx = 0
        uni_loss, mod_loss, bool_loss, cat_loss = 0.0, 0.0, 0.0, 0.0

        if self.unipolar_indices:
            y_true_uni = tf.gather(y_true_clean, self.unipolar_indices, axis=1)
            mask = self._group_mask_matrix(self.unipolar_indices, y_true_clean)
            mse = tf.square(y_true_uni - y_pred_list[head_idx]) * mask
            uni_loss = (tf.reduce_sum(mse) / (tf.reduce_sum(mask) + eps)) * W_CONT
            head_idx += 1

        if self.bipolar_indices:
            y_true_bi_raw = tf.gather(y_true_clean, self.bipolar_indices, axis=1)
            pred_gate, pred_val = y_pred_list[head_idx], y_pred_list[head_idx+1]
            head_idx += 2
            minv, maxv = tf.reduce_min(y_true_bi_raw), tf.reduce_max(y_true_bi_raw)
            y_true_bi = tf.cond(tf.logical_and(minv>=0, maxv<=1.0001), lambda: y_true_bi_raw*2-1, lambda: y_true_bi_raw)
            true_gate = tf.cast(tf.abs(y_true_bi) > 0.01, tf.float32)
            gate_loss = tf.reduce_mean(tf.reduce_sum(sigmoid_focal_crossentropy(true_gate, pred_gate), axis=-1))
            val_loss = tf.reduce_mean(tf.reduce_sum(tf.square(y_true_bi - pred_val) * true_gate, axis=-1) / (tf.reduce_sum(true_gate, axis=-1)+eps))
            mod_loss = gate_loss * W_MOD_GATE + val_loss * W_CONT

        if self.bool_indices:
            y_true_bool = tf.gather(y_true_clean, self.bool_indices, axis=1)
            mask = self._group_mask_matrix(self.bool_indices, y_true_clean)
            b_loss = K.binary_crossentropy(y_true_bool, tf.clip_by_value(y_pred_list[head_idx], eps, 1-eps)) * mask
            bool_loss = (tf.reduce_sum(b_loss) / (tf.reduce_sum(mask) + eps)) * W_BOOL
            head_idx += 1

        for j in sorted(self.cat_indices):
            y_true_cat = tf.squeeze(tf.gather(y_true_clean, [j], axis=1), -1)
            y_pred_cat = y_pred_list[head_idx]
            mask = tf.squeeze(self._group_mask_matrix([j], y_true_clean), -1)
            C = self.categorical_num_classes[int(j)]
            labels = tf.cast(tf.where(y_true_cat <= 1.0001, tf.round(y_true_cat*(C-1)), tf.round(y_true_cat)), tf.int32)
            labels = tf.clip_by_value(labels, 0, C-1)
            c_loss = tf.keras.losses.sparse_categorical_crossentropy(labels, y_pred_cat)
            cat_loss += tf.reduce_mean(c_loss * mask) * W_CAT
            head_idx += 1

        recon_loss = uni_loss + mod_loss + bool_loss + cat_loss
        kl_loss = -0.5 * tf.reduce_mean(tf.reduce_sum(1 + z_log_var - tf.square(z_mean) - tf.exp(z_log_var), axis=1))
        total_loss = recon_loss + (self.beta * kl_loss)
        return total_loss, recon_loss, kl_loss

    def train_step(self, data):
        (text_embeds, params_in), y_true = data
        params_clean = self.sanitize_inputs(params_in)

        # 2. GAUSSIAN NOISE FIX (Replaces Dropout)
        noise_amount = 0.1
        noise = tf.random.normal(shape=tf.shape(params_clean), stddev=noise_amount)
        params_noisy = params_clean + noise

        with tf.GradientTape() as tape:
            z_mean, z_log_var = self.encoder([text_embeds, params_noisy])
            eps = tf.random.normal(shape=tf.shape(z_mean))
            z = z_mean + tf.exp(0.5 * z_log_var) * eps
            mask = tf.cast(tf.random.uniform((tf.shape(z)[0], 1)) >= self.latent_dropout_rate, tf.float32)
            z_dec = z * mask
            y_pred = self.decoder([z_dec, text_embeds], training=True)
            total, recon, kl = self.calculate_loss(y_true, y_pred, z_mean, z_log_var)

        grads = tape.gradient(total, self.trainable_variables)
        self.optimizer.apply_gradients(zip(grads, self.trainable_variables))
        self.total_loss_tracker.update_state(total)
        self.reconstruction_loss_tracker.update_state(recon)
        self.kl_loss_tracker.update_state(kl)
        return {"loss": self.total_loss_tracker.result(), "recon": recon, "kl": kl}

    def test_step(self, data):
        (text_embeds, params_in), y_true = data
        params_clean = self.sanitize_inputs(params_in)
        z_mean, z_log_var = self.encoder([text_embeds, params_clean])
        eps = tf.random.normal(shape=tf.shape(z_mean))
        z = z_mean + tf.exp(0.5 * z_log_var) * eps
        y_pred = self.decoder([z, text_embeds], training=False)
        total, recon, kl = self.calculate_loss(y_true, y_pred, z_mean, z_log_var)
        self.total_loss_tracker.update_state(total)
        self.reconstruction_loss_tracker.update_state(recon)
        self.kl_loss_tracker.update_state(kl)
        return {"loss": self.total_loss_tracker.result(), "recon": recon, "kl": kl}

    def get_config(self):
        config = super().get_config()
        config.update({
            "encoder": serialize_keras_object(self.encoder),
            "decoder": serialize_keras_object(self.decoder),
            "unipolar_indices": self.unipolar_indices,
            "bipolar_indices": self.bipolar_indices,
            "bool_indices": self.bool_indices,
            "cat_indices": self.cat_indices,
            "categorical_num_classes": self.categorical_num_classes,
            "group_masking_map": self.group_masking_map,
            "latent_dim": self.latent_dim,
            "beta": float(self.beta.numpy()),
            "latent_dropout_rate": self.latent_dropout_rate
        })
        return config

    @classmethod
    def from_config(cls, config):
        encoder = deserialize_keras_object(config.pop("encoder"))
        decoder = deserialize_keras_object(config.pop("decoder"))
        return cls(encoder, decoder, **config)

# ==============================================================================
# 3. DIFFUSION COMPONENTS (Stage 2: Denoising)
# ==============================================================================

@register_keras_serializable(package="custom", name="SinusoidalTimeEmbedding")
class SinusoidalTimeEmbedding(Layer):
    def __init__(self, dim, **kwargs):
        super().__init__(**kwargs)
        self.dim = dim

    def call(self, time):
        half_dim = self.dim // 2
        embeddings = tf.math.log(10000.0) / (half_dim - 1)
        embeddings = tf.exp(tf.range(half_dim, dtype=tf.float32) * -embeddings)
        embeddings = tf.cast(time, tf.float32) * embeddings[None, :]
        embeddings = tf.concat([tf.sin(embeddings), tf.cos(embeddings)], axis=-1)
        return embeddings

    def get_config(self):
        config = super().get_config()
        config.update({"dim": self.dim})
        return config

@register_keras_serializable(package="custom", name="FiLM_Modulate")
class FiLM_Modulate(Layer):
    def call(self, inputs):
        x, gammas, betas = inputs
        return (x * (1.0 + gammas)) + betas

@register_keras_serializable(package="custom", name="ResidualBlock")
class ResidualBlock(Layer):
    def __init__(self, width, dropout=0.1, **kwargs):
        super().__init__(**kwargs)
        self.width = width
        self.dropout_rate = dropout
        self.norm1 = LayerNormalization()
        self.dense1 = Dense(width, activation="swish")
        self.drop1 = Dropout(dropout)
        self.norm2 = LayerNormalization()
        self.dense2 = Dense(width, activation="swish")
        self.drop2 = Dropout(dropout)
        self.film_proj = Dense(width * 4, activation=None)

    def call(self, x, conditions):
        residual = x
        film_params = self.film_proj(conditions)
        gam1, bet1, gam2, bet2 = tf.split(film_params, num_or_size_splits=4, axis=-1)
        x = self.norm1(x)
        x = FiLM_Modulate()([x, gam1, bet1])
        x = self.dense1(x)
        x = self.drop1(x)
        x = self.norm2(x)
        x = FiLM_Modulate()([x, gam2, bet2])
        x = self.dense2(x)
        x = self.drop2(x)
        return Add()([residual, x])

    def get_config(self):
        config = super().get_config()
        config.update({"width": self.width, "dropout": self.dropout_rate})
        return config

class DiffusionScheduler:
    def __init__(self, timesteps=1000, beta_start=0.0001, beta_end=0.02):
        self.timesteps = timesteps
        self.betas = tf.linspace(beta_start, beta_end, timesteps)
        self.alphas = 1.0 - self.betas
        self.alphas_cumprod = tf.math.cumprod(self.alphas)
        self.sqrt_alphas_cumprod = tf.sqrt(self.alphas_cumprod)
        self.sqrt_one_minus_alphas_cumprod = tf.sqrt(1.0 - self.alphas_cumprod)

    def add_noise(self, original_samples, noise, timesteps):
        sqrt_alpha_prod = tf.gather(self.sqrt_alphas_cumprod, timesteps)
        sqrt_one_minus_alpha_prod = tf.gather(self.sqrt_one_minus_alphas_cumprod, timesteps)
        sqrt_alpha_prod = tf.reshape(sqrt_alpha_prod, [-1, 1])
        sqrt_one_minus_alpha_prod = tf.reshape(sqrt_one_minus_alpha_prod, [-1, 1])
        return sqrt_alpha_prod * original_samples + sqrt_one_minus_alpha_prod * noise

@register_keras_serializable(package="custom", name="LatentDiffusionModel")
class LatentDiffusionModel(tf.keras.Model):
    """ Stage 2: Latent Diffusion Model (Updated with CFG and RAG Support) """
    def __init__(self, vae_encoder, vae_decoder, denoiser, timesteps=1000, **kwargs):
        super().__init__(**kwargs)
        self.vae_encoder = vae_encoder
        self.vae_decoder = vae_decoder
        self.denoiser = denoiser
        self.timesteps = int(timesteps)
        self.scheduler = DiffusionScheduler(timesteps=self.timesteps)
        self.loss_tracker = tf.keras.metrics.Mean(name="loss")

    def call(self, inputs, training=False):
        return self.denoiser(inputs, training=training)

    def train_step(self, data):
        (text_embeds, params_in), _ = data
        batch_size = tf.shape(params_in)[0]

        # 1. Encode with Frozen VAE
        z_mean, z_log_var = self.vae_encoder([text_embeds, params_in], training=False)
        epsilon = tf.random.normal(shape=tf.shape(z_mean))
        z_0 = z_mean + tf.exp(0.5 * z_log_var) * epsilon

        # 2. Add Noise
        t = tf.random.uniform(minval=0, maxval=self.timesteps, shape=(batch_size,), dtype=tf.int32)
        noise = tf.random.normal(shape=tf.shape(z_0))
        z_t = self.scheduler.add_noise(z_0, noise, t)

        # 3. CFG: 10% Dropout
        cfg_prob = 0.1
        mask_indices = tf.random.uniform((batch_size,)) < cfg_prob
        null_embeds = tf.zeros_like(text_embeds)
        mask_indices = tf.reshape(mask_indices, [-1, 1])
        final_text_embeds = tf.where(mask_indices, null_embeds, text_embeds)

        # 4. Train Denoiser
        with tf.GradientTape() as tape:
            pred_noise = self.denoiser([z_t, t, final_text_embeds], training=True)
            loss = tf.reduce_mean(tf.square(noise - pred_noise))

        gradients = tape.gradient(loss, self.denoiser.trainable_variables)
        self.optimizer.apply_gradients(zip(gradients, self.denoiser.trainable_variables))
        self.loss_tracker.update_state(loss)
        return {"loss": self.loss_tracker.result()}

    def test_step(self, data):
        (text_embeds, params_in), _ = data
        batch_size = tf.shape(params_in)[0]
        z_mean, z_log_var = self.vae_encoder([text_embeds, params_in], training=False)
        epsilon = tf.random.normal(shape=tf.shape(z_mean))
        z_0 = z_mean + tf.exp(0.5 * z_log_var) * epsilon
        t = tf.random.uniform(minval=0, maxval=self.timesteps, shape=(batch_size,), dtype=tf.int32)
        noise = tf.random.normal(shape=tf.shape(z_0))
        z_t = self.scheduler.add_noise(z_0, noise, t)
        pred_noise = self.denoiser([z_t, t, text_embeds], training=False)
        loss = tf.reduce_mean(tf.square(noise - pred_noise))
        self.loss_tracker.update_state(loss)
        return {"loss": self.loss_tracker.result()}

    # --- UPDATED GENERATE FUNCTION (RAG SUPPORT ADDED) ---
    def generate(self, text_embeds, steps=50, guidance_scale=7.5, initial_latent=None, strength=0.8):
        """
        Generates latents using CFG.
        If initial_latent is provided, performs Image-to-Image style generation (RAG).
        strength: 0.8 means we start at 80% noise (step 800) using the reference latent.
        """
        text_embeds = tf.convert_to_tensor(text_embeds, dtype=tf.float32)
        batch_size = tf.shape(text_embeds)[0]
        latent_dim = self.vae_encoder.output_shape[0][1]

        # 1. Determine Start Point
        if initial_latent is None:
            # Standard: Pure Noise
            z = tf.random.normal(shape=(batch_size, latent_dim))
            start_timestep = self.timesteps - 1
        else:
            # RAG: Noisy Reference
            # Convert strength (0.8) to timestep (800)
            start_timestep = int(self.timesteps * strength)
            # Create noise
            noise = tf.random.normal(shape=tf.shape(initial_latent))
            t_start = tf.ones((batch_size,), dtype=tf.int32) * start_timestep
            # Add specific noise to the reference
            z = self.scheduler.add_noise(initial_latent, noise, t_start)

        # 2. Prepare unconditional embeddings
        uncond_embeds = tf.zeros_like(text_embeds)

        # 3. Loop
        for i in reversed(range(0, start_timestep + 1)):
            t = tf.ones((batch_size,), dtype=tf.int32) * i

            # Batch inputs
            latents_in = tf.concat([z, z], axis=0)
            t_in = tf.concat([t, t], axis=0)
            text_in = tf.concat([text_embeds, uncond_embeds], axis=0)

            # Predict noise
            noise_preds = self.denoiser([latents_in, t_in, text_in], training=False)
            noise_cond, noise_uncond = tf.split(noise_preds, num_or_size_splits=2, axis=0)

            # CFG
            pred_noise = noise_uncond + guidance_scale * (noise_cond - noise_uncond)

            # Step
            alpha = tf.gather(self.scheduler.alphas, i)
            alpha_cumprod = tf.gather(self.scheduler.alphas_cumprod, i)
            beta = tf.gather(self.scheduler.betas, i)
            sqrt_one_minus_alpha_cumprod = tf.sqrt(1.0 - alpha_cumprod)

            model_mean = (1 / tf.sqrt(alpha)) * (z - ((1 - alpha) / (sqrt_one_minus_alpha_cumprod)) * pred_noise)

            if i > 0:
                noise = tf.random.normal(shape=tf.shape(z))
                sigma = tf.sqrt(beta)
                z = model_mean + sigma * noise
            else:
                z = model_mean

        return self.vae_decoder([z, text_embeds], training=False)

    def get_config(self):
        config = super().get_config()
        config.update({
            "vae_encoder": serialize_keras_object(self.vae_encoder),
            "vae_decoder": serialize_keras_object(self.vae_decoder),
            "denoiser": serialize_keras_object(self.denoiser),
            "timesteps": self.timesteps
        })
        return config

    @classmethod
    def from_config(cls, config):
        vae_encoder = deserialize_keras_object(config.pop("vae_encoder"))
        vae_decoder = deserialize_keras_object(config.pop("vae_decoder"))
        denoiser = deserialize_keras_object(config.pop("denoiser"))
        return cls(vae_encoder, vae_decoder, denoiser, **config)

"""## Define Model Builders"""

# Cell 3.3 — Model Builders (Updated for High-Fidelity)

from tensorflow.keras.regularizers import l2

def build_encoder(embedding_dim, num_params, latent_dim, enc_width, dropout_rate=0.0):
    """ Builds q(z | params, text) - LINEAR VERSION """
    text_in = Input(shape=(embedding_dim,), name="encoder_text_input")
    params_in = Input(shape=(num_params,), name="encoder_params_input")
    x = Concatenate(name="encoder_concat")([text_in, params_in])

    # Layer 1
    x = Dense(enc_width, activation="linear", kernel_regularizer=l2(1e-4))(x)
    x = LayerNormalization()(x)
    x = Activation("relu")(x)
    if dropout_rate > 0: x = Dropout(dropout_rate)(x)

    # Layer 2
    x = Dense(enc_width, activation="linear", kernel_regularizer=l2(1e-4))(x)
    x = LayerNormalization()(x)
    x = Activation("relu")(x)
    if dropout_rate > 0: x = Dropout(dropout_rate)(x)

    z_mu = Dense(latent_dim, name="z_mean")(x)
    z_log = Dense(latent_dim, name="z_log_var")(x)
    return Model([text_in, params_in], [z_mu, z_log], name="encoder")

def build_decoder_film(embedding_dim, latent_dim, dec_width, unipolar_indices, bipolar_indices,
                       bool_indices, cat_indices, categorical_num_classes, dropout_rate=0.0):
    """ Builds p(params | z, text) - LINEAR VERSION """
    z_in = Input(shape=(latent_dim,), name="latent_input")
    text_in = Input(shape=(embedding_dim,), name="decoder_text_input")

    def film_block(x, text_in, width, block_id):
        x = LayerNormalization(name=f"dec_ln_pre_{block_id}")(x)
        gamma = Dense(width, kernel_initializer="zeros", bias_initializer="ones")(text_in)
        beta = Dense(width, kernel_initializer="zeros", bias_initializer="zeros")(text_in)
        x = FiLMLayer(name=f"film_{block_id}")([x, gamma, beta])
        x = LeakyReLU(alpha=0.2)(x)
        if dropout_rate > 0: x = Dropout(dropout_rate)(x)
        return x

    # Standard Stacked Architecture
    x = Dense(dec_width, kernel_regularizer=l2(1e-4))(z_in)
    x = film_block(x, text_in, dec_width, 1)
    x = Dense(dec_width, kernel_regularizer=l2(1e-4))(x)
    x = film_block(x, text_in, dec_width, 2)
    x = Dense(dec_width, kernel_regularizer=l2(1e-4))(x)
    x = LayerNormalization()(x)
    x = Activation("relu")(x)

    outs = []
    if unipolar_indices:
        outs.append(Dense(len(unipolar_indices), activation="sigmoid", name="unipolar_outputs")(x))
    if bipolar_indices:
        outs.append(Dense(len(bipolar_indices), activation="linear", name="bipolar_gate")(x))
        outs.append(Dense(len(bipolar_indices), activation="tanh", name="bipolar_value")(x))
    if bool_indices:
        outs.append(Dense(len(bool_indices), activation="sigmoid", name="boolean_outputs")(x))
    for j in sorted(cat_indices):
        outs.append(Dense(categorical_num_classes[int(j)], activation="softmax", name=f"cat_{j}")(x))
    return Model([z_in, text_in], outs, name="decoder_film")

# --- UPDATED: Deep ResMLP Denoiser (1024 width, 16 layers) ---
def build_resmlp_denoiser(latent_dim=128, text_embed_dim=512, hidden_dim=1024, num_layers=16):
    z_noisy = Input(shape=(latent_dim,), name="z_noisy")
    t_in = Input(shape=(1,), name="time_input")
    text_emb = Input(shape=(text_embed_dim,), name="text_embedding")

    # Time Embeddings
    t_emb = SinusoidalTimeEmbedding(dim=hidden_dim)(t_in)
    t_emb = Dense(hidden_dim, activation="swish")(t_emb)

    # Initial Projection
    x = Dense(hidden_dim)(z_noisy)

    # Conditioning
    cond_concat = Concatenate()([t_emb, text_emb])
    cond_mapped = Dense(hidden_dim, activation="swish")(cond_concat)
    cond_mapped = Dense(hidden_dim, activation="swish")(cond_mapped)

    # --- BLOCK 1: First Half of ResNet ---
    for i in range(num_layers // 2):
        x = ResidualBlock(width=hidden_dim, name=f"res_block_{i}")(x, cond_mapped)

    # --- BLOCK 2: SELF-ATTENTION (The Brain) ---
    # 1. Reshape: (Batch, 1024) -> (Batch, 16, 64)
    seq_len = 16
    token_dim = hidden_dim // seq_len
    x_seq = Reshape((seq_len, token_dim))(x)

    # 2. Self-Attention
    attn_out = MultiHeadAttention(num_heads=8, key_dim=64)(x_seq, x_seq)

    # 3. Add & Norm
    x_seq = Add()([x_seq, attn_out])
    x_seq = LayerNormalization()(x_seq)

    # 4. Flatten back
    x_att = Flatten()(x_seq)

    # 5. Skip Connection
    x = Add()([x, x_att])

    # --- BLOCK 3: Second Half of ResNet ---
    for i in range(num_layers // 2, num_layers):
        x = ResidualBlock(width=hidden_dim, name=f"res_block_{i}")(x, cond_mapped)

    x = LayerNormalization()(x)
    noise_pred = Dense(latent_dim, activation="linear", name="noise_pred")(x)

    return Model(inputs=[z_noisy, t_in, text_emb], outputs=noise_pred, name="attn_resmlp_denoiser")

"""## Compile and Train

### 🏆 Best Parameters So Far (The "Golden Config")

These settings achieved the lowest **Validation Loss (~130)** by combining the efficient **Linear Architecture** with **Input Sanitization**.

| Parameter | Value | Reason |
| :--- | :--- | :--- |
| **Architecture** | **Linear** (Dense + ReLU) | Outperformed ResNet on structured knob data. |
| **Latent Dim** | **64** | The "Sweet Spot" between compression and detail. |
| **Decoder Width** | **512** | Sufficient capacity without overfitting. |
| **Beta (KL)** | **0.1** | Low regularization allowed for higher audio fidelity. |
| **Input Dropout** | **0.2** | Forces the model to learn rules, not just memorize. |
| **Sanitization** | **Enabled** (Input + Target) | **Critical:** Removes "Ghost Parameters" from training. |
| **Dataset** | **Full** (~20k samples) | More data yielded significantly better generalization. |
"""

# Cell 3.4 — Final SOTA Training (Reduced Beta + EMA + Cosine Decay + Deep Net)

import tensorflow as tf
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ReduceLROnPlateau, EarlyStopping
import os

# --- SOTA CONFIGURATION ---
latent_dim = 64
width = 512
batch_size = 64
dropout_rate = 0.2
beta_max = 0.0001       # Low Beta for High Fidelity

# Training Duration
vae_epochs = 100
diffusion_epochs = 80

# --- CYCLICAL BETA CALLBACK ---
class CyclicalBetaAnnealing(tf.keras.callbacks.Callback):
    def __init__(self, cycle_epochs=20, max_beta=0.01):
        super().__init__()
        self.cycle_epochs = cycle_epochs
        self.max_beta = max_beta

    def on_epoch_begin(self, epoch, logs=None):
        cycle_pos = (epoch % self.cycle_epochs) / self.cycle_epochs
        if cycle_pos < 0.5:
            current_beta = self.max_beta * (cycle_pos * 2)
        else:
            current_beta = self.max_beta
        if hasattr(self.model, "beta"):
            self.model.beta.assign(float(current_beta))

# --- EMA CALLBACK (FIXED) ---
class EMACallback(tf.keras.callbacks.Callback):
    """ Applies Exponential Moving Average to model weights during training """
    def __init__(self, source_model, ema_model, decay=0.999):
        super().__init__()
        self.source_model = source_model  # <--- RENAMED to avoid conflict with self.model
        self.ema_model = ema_model
        self.decay = decay

    def on_train_batch_end(self, batch, logs=None):
        # Update EMA weights: new_ema = decay * old_ema + (1 - decay) * new_weights
        for weight, ema_weight in zip(self.source_model.trainable_variables, self.ema_model.trainable_variables):
            ema_weight.assign(self.decay * ema_weight + (1 - self.decay) * weight)

# --- STAGE 1: TRAIN VAE ---
print(f"\n=== STAGE 1: Training VAE (Low Beta {beta_max} | Drop {dropout_rate}) ===")

tf.keras.backend.clear_session()

# Linear Builders
enc = build_encoder(X_train.shape[1], num_params, latent_dim, width, dropout_rate=dropout_rate)
dec = build_decoder_film(X_train.shape[1], latent_dim, width,
                         unipolar_indices, bipolar_indices, boolean_param_indices,
                         categorical_param_indices, categorical_num_classes,
                         dropout_rate=dropout_rate)

# Initialize VAE
vae = VAE_Text_to_Synth_Standard(
    encoder=enc, decoder=dec,
    unipolar_indices=unipolar_indices, bipolar_indices=bipolar_indices,
    bool_indices=boolean_param_indices, cat_indices=categorical_param_indices,
    categorical_num_classes=categorical_num_classes, group_masking_map=GROUP_MASKING_MAP,
    latent_dim=latent_dim,
    beta=0.0,
    latent_dropout_rate=0.1
)

vae.compile(optimizer=Adam(learning_rate=1e-3))

callbacks_vae = [
    EarlyStopping(monitor="val_loss", patience=15, restore_best_weights=True),
    ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=5, min_lr=1e-6, verbose=1),
    CyclicalBetaAnnealing(cycle_epochs=20, max_beta=beta_max)
]

# Note: If you already ran Stage 1 successfully and saved it,
# you can comment out this .fit() line to skip re-training the VAE.
vae.fit(x=[X_train, y_train], y=y_train, epochs=vae_epochs, batch_size=batch_size,
        validation_data=([X_val, y_val], y_val), callbacks=callbacks_vae, verbose=1)

# Save VAE
vae_save_path = os.path.join(SAVE_DIR, "vae_stage1_sota_lowbeta.keras")
vae.save(vae_save_path)
print(f"✅ VAE Saved to {vae_save_path}")

# --- STAGE 2: TRAIN LATENT DIFFUSION (Deep + EMA + Cosine) ---
print("\n=== STAGE 2: Training Latent Diffusion (Deep Net + EMA + Cosine Decay) ===")

vae.trainable = False
vae.encoder.trainable = False
vae.decoder.trainable = False

# 1. Build Deep Denoiser
denoiser = build_resmlp_denoiser(
    latent_dim=latent_dim,
    text_embed_dim=X_train.shape[1],
    hidden_dim=1024, # Deep Width
    num_layers=16    # Deep Layers
)

# 2. Initialize EMA Clone
ema_denoiser = tf.keras.models.clone_model(denoiser)
ema_denoiser.set_weights(denoiser.get_weights())

# 3. Compile LDM
ldm = LatentDiffusionModel(vae_encoder=vae.encoder, vae_decoder=vae.decoder, denoiser=denoiser, timesteps=1000)

# 4. Cosine Decay Schedule
total_steps = (len(X_train) // batch_size) * diffusion_epochs
lr_schedule = tf.keras.optimizers.schedules.CosineDecay(
    initial_learning_rate=2e-4,
    decay_steps=total_steps,
    alpha=0.01
)

ldm.compile(optimizer=Adam(learning_rate=lr_schedule))

callbacks_flow = [
    EMACallback(ldm.denoiser, ema_denoiser)
]

ldm.fit(x=[X_train, y_train], y=y_train, epochs=diffusion_epochs, batch_size=batch_size,
        validation_split=0.1, callbacks=callbacks_flow, verbose=1)

# 5. SWAP WEIGHTS (Save the EMA version)
print("🔄 Swapping real weights for EMA weights before saving...")
ldm.denoiser.set_weights(ema_denoiser.get_weights())

ldm_save_path = os.path.join(SAVE_DIR, "ldm_final_sota_ema_deep.keras")
ldm.save(ldm_save_path)
best_model = ldm
print(f"✅ LDM (EMA Version) Saved to {ldm_save_path}")

"""## Evaluate and Save Model"""

# Cell 3.5 — Evaluate Diffusion Model

# Validation dataset
val_dataset = tf.data.Dataset.from_tensor_slices(((X_val, y_val), y_val)).batch(16)

total_mse_agg = tf.keras.metrics.Mean()

print("Evaluating Diffusion Model on Validation Set...")

for (text_batch, params_batch), _ in val_dataset:
    # 1. Use the internal VAE encoder (Note: attribute is 'vae_encoder' in LDM)
    z_mean, z_log_var = best_model.vae_encoder([text_batch, params_batch], training=False)

    # 2. Sample Latent (z_0)
    eps = tf.random.normal(shape=tf.shape(z_mean))
    z_0 = z_mean + tf.exp(0.5 * z_log_var) * eps

    # 3. Diffusion Forward Process (Add Noise)
    batch_size = tf.shape(z_0)[0]
    # Sample random timesteps
    t = tf.random.uniform(minval=0, maxval=best_model.timesteps, shape=(batch_size,), dtype=tf.int32)
    # Generate ground truth noise
    noise = tf.random.normal(shape=tf.shape(z_0))

    # Add noise using the scheduler
    z_t = best_model.scheduler.add_noise(z_0, noise, t)

    # 4. Predict Noise using the Denoiser
    # (The LDM stores the denoiser network in 'best_model.denoiser')
    pred_noise = best_model.denoiser([z_t, t, text_batch], training=False)

    # 5. Calculate MSE (Noise Prediction Error)
    loss = tf.reduce_mean(tf.square(noise - pred_noise))
    total_mse_agg.update_state(loss)

print("-" * 30)
print(f"Validation Diffusion MSE: {total_mse_agg.result():.4f}")
print("-" * 30)

# Save is already handled in Cell 3.4, but we can re-save if desired
# best_model.save(os.path.join(SAVE_DIR, "ldm_final_eval.keras"))

"""# Test requests to model

### Subtask:
Implement code to test the end-to-end process with new text descriptions.

"""

# Cell 4.1 — Diffusion Inference Helpers (With RAG Support)

import numpy as np
import random
import tensorflow as tf
import json
import os
from tensorflow.keras.models import load_model

# ==============================================================================
# 1. HELPER FUNCTIONS
# ==============================================================================

def _safe_probs(raw_head):
    probs = np.array(raw_head, dtype=np.float32).reshape(-1)
    probs[probs < 0] = 0.0
    s = probs.sum()
    if not np.isfinite(s) or s <= 1e-6:
        probs = np.ones_like(probs, dtype=np.float32) / probs.size
    else:
        probs = probs / s
    return probs

def reconstruct_parameters_from_heads(predicted_outputs, parameter_types, categorical_num_classes, sample_categorical=True, noise_level=0.0):
    """
    Reconstructs parameter vector from split heads.
    """
    n_params = len(parameter_types)
    reconstructed = np.zeros(n_params, dtype=np.float32)

    continuous_params = [int(i) for i, p in parameter_types.items() if p["type"] == "continuous"]
    mod_matrix_ids = set(range(170, 202))

    unipolar_indices = sorted([i for i in continuous_params if i not in mod_matrix_ids])
    bipolar_indices = sorted([i for i in continuous_params if i in mod_matrix_ids])
    boolean_params = sorted([int(i) for i, p in parameter_types.items() if p["type"] == "boolean"])
    categorical_params = sorted([int(i) for i, p in parameter_types.items() if p["type"] == "categorical"])

    head_idx = 0

    if unipolar_indices:
        uni_head = np.array(predicted_outputs[head_idx], dtype=np.float32).reshape(-1)
        for i, param_idx in enumerate(unipolar_indices):
            reconstructed[param_idx] = uni_head[i]
        head_idx += 1

    if bipolar_indices:
        gate_head = np.array(predicted_outputs[head_idx], dtype=np.float32).reshape(-1)
        val_head = np.array(predicted_outputs[head_idx+1], dtype=np.float32).reshape(-1)
        head_idx += 2
        for i, param_idx in enumerate(bipolar_indices):
            gate = 1.0 / (1.0 + np.exp(-gate_head[i]))
            val = (val_head[i] + 1.0) / 2.0
            if gate < 0.25: reconstructed[param_idx] = 0.5
            else: reconstructed[param_idx] = val

    if boolean_params:
        bool_head = np.array(predicted_outputs[head_idx], dtype=np.float32).reshape(-1)
        head_idx += 1
        for i, param_idx in enumerate(boolean_params):
            reconstructed[param_idx] = 1.0 if bool_head[i] > 0.5 else 0.0

    for param_idx in categorical_params:
        head = predicted_outputs[head_idx]
        if isinstance(head, (list, tuple)): head = head[0]
        probs = _safe_probs(head)
        num_c = categorical_num_classes[param_idx]
        if sample_categorical: choice = np.random.choice(len(probs), p=probs)
        else: choice = np.argmax(probs)
        if num_c > 1: reconstructed[param_idx] = float(choice) / (num_c - 1)
        else: reconstructed[param_idx] = 0.0
        head_idx += 1

    return reconstructed

def retrieve_closest_preset(target_emb, db_embeddings, db_params):
    """
    Finds the single closest preset in the training set using Cosine Similarity.
    """
    # Dot product (since embeddings are normalized)
    scores = np.dot(db_embeddings, target_emb.T).flatten()
    best_idx = np.argmax(scores)
    print(f"🔎 RAG Retrieval: Found match at index {best_idx} (Score: {scores[best_idx]:.4f})")

    # Return the parameters of that preset
    return db_params[best_idx:best_idx+1]

def generate_synth_parameters_vae(text_description, model, parameter_types, categorical_num_classes,
                                  sample_categorical=True, noise_level=0.0, seed=None,
                                  guidance_scale=7.5, use_rag=True, rag_strength=0.8):
    if seed is not None:
        import torch
        np.random.seed(seed)
        random.seed(seed)
        tf.random.set_seed(seed)
        torch.manual_seed(seed)

    # 1. Encode Text
    emb = clap_encode_text([text_description])

    # 2. RAG Logic (Retrieve & Encode)
    initial_latent = None
    if use_rag:
        # We access the global training data from Cell 2.1/3.1
        # X_train (Embeds) and y_train (Params)
        if 'X_train' in globals() and 'y_train' in globals():
            # Get closest params
            retrieved_params = retrieve_closest_preset(emb, globals()['X_train'], globals()['y_train'])

            # Encode them into latent space using the model's VAE Encoder
            # (Note: We pass the target text embedding, not the retrieved text embedding, for conditioning)
            z_mean, z_log_var = model.vae_encoder([emb, retrieved_params], training=False)
            initial_latent = z_mean # Use mean for stability
        else:
            print("⚠️ Warning: Training data not found in globals. Skipping RAG.")

    # 3. Generate
    print(f"Diffusion Sampling for: '{text_description}' (CFG: {guidance_scale}, RAG: {use_rag})...")

    preds = model.generate(emb, steps=1000, guidance_scale=guidance_scale,
                           initial_latent=initial_latent, strength=rag_strength)

    # 4. Reconstruct
    return reconstruct_parameters_from_heads(preds, parameter_types, categorical_num_classes, sample_categorical=sample_categorical, noise_level=noise_level)

def numpy_to_json(parameter_array, serum_parameters):
    output_json = {}
    flat_lookup = {}
    for group, params in serum_parameters.items():
        for p in params:
            flat_lookup[int(p["id"])] = p

    for idx, val in enumerate(parameter_array):
        if idx in flat_lookup:
            param_def = flat_lookup[idx]
            entry = param_def.copy()
            entry["value"] = float(val)
            output_json[str(idx)] = entry

    return output_json

# ==============================================================================
# 2. LOAD MODEL
# ==============================================================================

if 'best_model' not in globals():
    print("Variable 'best_model' not found. Attempting to load LDM...")
    saved_model_path = os.path.join(SAVE_DIR, "ldm_final_sota_ema_deep.keras")

    if os.path.exists(saved_model_path):
        custom_objects = {
            "VAE_Text_to_Synth_Standard": VAE_Text_to_Synth_Standard,
            "LatentDiffusionModel": LatentDiffusionModel,
            "SinusoidalTimeEmbedding": SinusoidalTimeEmbedding,
            "ResidualBlock": ResidualBlock,
            "FiLM_Modulate": FiLM_Modulate,
            "FiLMLayer": FiLMLayer,
            "SliceLayer": SliceLayer
        }
        best_model = load_model(saved_model_path, custom_objects=custom_objects)
        print(f"✅ Loaded: {saved_model_path}")
    else:
        print("❌ Model not found. Run Cell 3.4 to train.")

# --- Run Test ---
test_prompt = "A deep, wobbling reese bass with slow filter movement"
param_map = {int(p['id']): p for g in SERUM_PARAMETERS.values() for p in g}

if 'best_model' in globals():
    generated_params = generate_synth_parameters_vae(
        text_description=test_prompt,
        model=best_model,
        parameter_types=param_map,
        categorical_num_classes=categorical_num_classes,
        sample_categorical=True,
        seed=42,
        guidance_scale=7.5,
        use_rag=True,       # <--- Enable RAG
        rag_strength=0.8    # <--- 80% Noise (High Creativity), 20% Retrieval
    )

    preset_json = numpy_to_json(generated_params, SERUM_PARAMETERS)

    print("\n--- Generated Parameter Snippet ---")
    print(json.dumps({k: preset_json[k] for k in list(preset_json.keys())[:3]}, indent=2))

    mod_val = preset_json["170"]["value"]
    print(f"\nMod Slot 1 (Gate Check): {mod_val:.4f}")

# --- Run a Test Prediction ---
test_prompt = "A deep, wobbling reese bass with slow filter movement"
print(f"Generating preset for: '{test_prompt}'...")

# Use globals to reconstruct types map if needed
param_map = {int(p['id']): p for g in SERUM_PARAMETERS.values() for p in g}

generated_params = generate_synth_parameters_vae(
    text_description=test_prompt,
    model=best_model,
    parameter_types=param_map,
    categorical_num_classes=categorical_num_classes,
    sample_categorical=True,
    noise_level=0.0,
    seed=None
)

preset_json = numpy_to_json(generated_params, SERUM_PARAMETERS)

print("\n--- Sample Results (Gated Mod Matrix) ---")
mod_val = preset_json["170"]["value"]
print(f"Mod 1 Amt (ID 170): {mod_val:.4f} (Should be 0.0 if inactive, or high value if active)")

print("\n--- Full JSON Snippet (First 3 items) ---")
print(json.dumps({k: preset_json[k] for k in list(preset_json.keys())[:203]}, indent=2))

"""# Data Interpolation and Visualization

## Interpolations
"""

# Cell 5.4 — Latent Space Interpolation & Visualization

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

def interpolate_prompts(model, start_prompt, end_prompt, steps=10, z_seed=42):
    """
    Morphs between two text descriptions using the VAE Decoder.
    Note: This bypasses the Diffusion Denoiser to show the VAE's smooth latent manifold.
    """
    # 1. Encode both prompts
    emb_start = clap_encode_text([start_prompt])[0]
    emb_end = clap_encode_text([end_prompt])[0]

    # 2. Fixed Z (use mean 0 for "standard" representation)
    np.random.seed(z_seed)
    z_fixed = np.random.normal(size=(1, int(model.vae_encoder.output_shape[0][1]))).astype('float32')

    # 3. Linear Interpolation
    interpolated_params = []
    alphas = np.linspace(0, 1, steps)

    print(f"Morphing: '{start_prompt}' -> '{end_prompt}'")

    for alpha in alphas:
        # Interpolate text embedding
        emb_interp = (1 - alpha) * emb_start + alpha * emb_end
        emb_interp = emb_interp.reshape(1, -1)

        # !!! FIXED: Use .vae_decoder
        preds = model.vae_decoder.predict([z_fixed, emb_interp], verbose=0)

        # Reconstruct
        param_map = {int(p['id']): p for g in SERUM_PARAMETERS.values() for p in g}
        params = reconstruct_parameters_from_heads(
            preds,
            parameter_types=param_map,
            categorical_num_classes=categorical_num_classes,
            sample_categorical=False, # Deterministic for smooth plots
            noise_level=0.0
        )
        interpolated_params.append(params)

    return np.array(interpolated_params), alphas

# --- CONFIG ---
prompt_a = "Aggressive, Dubstep, Bass"
prompt_b = "Soft, Ambient, Pad"

if 'best_model' in globals():
    interp_data, alphas = interpolate_prompts(best_model, prompt_a, prompt_b, steps=20)

    # --- PARAMETERS TO TRACK ---
    params_to_plot = [
        {"id": 6,   "name": "Osc A Octave",     "color": "blue"},
        {"id": 49,  "name": "Sub Osc Level",    "color": "darkgreen"},
        {"id": 59,  "name": "Filter Cutoff",    "color": "red"},
        {"id": 60,  "name": "Filter Resonance", "color": "orange"},
        {"id": 65,  "name": "Env1 Attack",      "color": "purple"},
        {"id": 75,  "name": "LFO1 Rate",        "color": "brown"},
        {"id": 91,  "name": "Dist Wet",         "color": "pink"},
        {"id": 147, "name": "Reverb Size",      "color": "cyan"},
    ]

    # --- PLOTTING ---
    plt.figure(figsize=(12, 6))
    for p in params_to_plot:
        col_idx = p["id"]
        values = interp_data[:, col_idx]
        plt.plot(alphas, values, marker='o', label=p["name"], color=p["color"], linewidth=2, alpha=0.8)

    plt.title(f"Parameter Morphing:\n'{prompt_a}'  >>>  '{prompt_b}'")
    plt.xlabel("Interpolation Alpha")
    plt.ylabel("Normalized Parameter Value (0-1)")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.show()
else:
    print("Model not loaded.")

